open-learning-exchange/planet

Vagrantfile

Realized that the `run: "always"` section runs even the first time, so we are starting two screens when we initializing the VM.  I think the mount duplication is fine & we need it before the `npm install` regardless.
Also added some comments & split up into sections so we don't break things if this needs later modification.
I don't think this is a big issue, but it can't hurt to just have one screen running.

Only start screen in always run section so it only runs once

---

src/app/login/login.component.ts

Password type is changed to password and login message is been removed

34 password type and login message

---

docker/db-init/rpi-Dockerfile
docker/planet/rpi-Dockerfile
docker/rpi-planet-dev.yml

[#4] Create Docker for Development for Raspberry Pi

---

deploy/deploy_rpi.sh

fix docker latest then sleep

---

README.md

Based on ole-vi/planet/issues/67

Update README.md (Fixes #67)

---

README.md
Style-Guide.md

Here's a first draft.  Want to keep it short and relatively simple, and we can add to this as more things come up that we'd want a rule for.

Style guide for contributing

---

src/app/community/community.component.ts
src/app/courses/courses.component.ts
src/app/meetups/meetups.component.ts

In #170 I missed a commit to fix the `deleteClick` function in the community component before merging.  This adds in that fix.
Also removing an unnecessary console.log while I was working on this component.

Fix community delete

---

src/app/shared/couchdb.service.ts

WIP trying out some fixes for the issues Code Climate has flagged.  Working on the `shared/couchdb.service.ts` first.

Fix Code Climate Issues (connects #168)

---

src/app/variables.scss
src/planet-mat-theme.scss

Change the color palette to the following based on the UX recommendation to:
https://www.materialpalette.com/blue/amber
* Primary is now $mat-blue
* Accent is now $mat-amber
* Warn is now $mat-red (no specific recommendation on this, so reverting it to default)

Change color palette

---

.angular-cli.json
package.json
src/app/home/home.component.ts
src/app/home/navigation.component.ts
src/app/meetups/meetups.component.html
src/app/page-not-found/page-not-found.component.html

I found bootstrap class used in pagenotfound component.

211 remove bootstrap (connects #211)

---

src/app/shared/mangoQueries.ts

[#202] Made function that can take multiple json data/field (connects #202)

---

e2e/userHandler.ts

A small update to make sure the test user is deleted when the tests run locally.

Fix deletion of end to end test user 

---

docker/db-init/Dockerfile
docker/db-init/rpi-Dockerfile

[quick-fix] add python as deps in db-init docker

[quick-fix] add python as deps in db-init docker

---

src/app/login/login.component.html
src/app/login/login.scss

Removed mat-grid in favor of CSS grid layout

Fix login layout for Firefox

---

src/app/configuration/configuration.component.spec.ts
src/app/courses/add-courses/courses-add.component.spec.ts
src/app/courses/courses.component.spec.ts
src/app/courses/request-courses/courses-request.component.spec.ts
src/app/dashboard/dashboard.component.spec.ts
src/app/feedback/feedback.component.spec.ts
src/app/home/home.component.spec.ts
src/app/login/login.component.spec.ts
src/app/resources/view-resources/resources-view.component.spec.ts
src/app/users/users-profile/users-profile.component.spec.ts
src/app/users/users-update/users-update.component.spec.ts

1) Fixed new unit test errors in all components.
2) Updated test creatForm() in course-add.component.spec.ts not to check form.valid.

[#349] Update test case not to check form.valid

---

src/app/login/login-form.component.ts

redirect user to edit profile after registration

---

src/app/feedback/feedback.directive.ts

brainstroming on taking screenshot, 
i have found some packages like html2canvas, if all agrees we can add package for screenshot

[#365] Current Url to feedback (connects #365)

---

docker/README.md

I want to do some update on our docker documentation to make it possible other people improve work I've done and make it possible to improve app together.

WIP: update docker readme of planet

---

src/app/home/home.component.ts
src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts
src/app/resources/view-resources/resources-view.component.html
src/app/resources/view-resources/resources-view.component.ts
src/app/resources/view-resources/resources-view.scss
src/planet-mat-theme.scss
src/styles.scss

See #336 for resource view.  Also updates resource add to fit with list design.

[#336] New resource view & updated resource add (fixes #336)

---

src/styles.scss

Snapshot of Chrome and Mozilla respectively.

[#409] Star Rating Design (connects #409)

---

package.json
src/app/app.module.ts

Also includes a linting fix from today.

Update version number

---

.travis.yml
deploy/deploy.sh
deploy/deploy_rpi.sh

Deploy versioned docker when there is a github tag
Solved #434 
Testing stuff https://github.com/ole-vi/planet/releases/tag/v0.0.13.1-snapshot
should appear here https://hub.docker.com/r/treehouses/planet/tags

Deploy versioned docker when there is a github tag

---

README.md
Style-Guide.md
docker/planet/docker-entrypoint.sh
docker/rpi-planet.yml
src/environments/environment.prod.ts

[#400] dynamic origin host

---

design/resources/resources-mockup.json

fileName fields has been added to resources mock data according to corresponding filenames in the attachment json file.

Add filenames to resources mock data (fixes #460)

---

design/resources/resources-mockup.json
src/app/users/users.component.html

Add the word Users after arrow_back icon to be more informative and also consist with other routes' layouts.

Add the word Users after arrow_back icon in users.component.html (fixes #471)

---

.travis.yml
Vagrantfile
docker/planet-dev.yml
docker/planet.yml
docker/rpi-planet-dev.yml
docker/rpi-planet.yml

[#420] Use couchdb:2.1.1 for x86 and treehouses/rpi-couchdb:2.1.1 for arm image

---

.travis.yml
.travis/planet-travis.yml
docker/db-init/Dockerfile
docker/db-init/docker-entrypoint.sh
docker/db-init/rpi-Dockerfile
docker/planet-dev.yml
docker/planet.yml
docker/rpi-planet-dev.yml
docker/rpi-planet.yml

@lmmrssa 
fix the problem of dynamic db init address

fix hardcoded db init

---

src/app/home/home.component.html
src/app/home/home.component.ts
src/app/shared/user.service.ts
src/app/users/users-update/users-update.component.ts

@paulbert How to get value in real time ? I mean to say, when I change the profile Image , then it needs to update the top bar image as well. 
I checked **BehaviorSubject**, we can update **this.user** value in user service. So, please give me some suggestion  to follow

[#536] Profile Image in Top Bar (connects #536)

---

src/app/configuration/configuration.component.ts

Fix for the bug where admin created by configuration is "undefined"

Fix admin undefined

---

src/app/feedback/feedback-router.module.ts
src/app/feedback/feedback-view.component.html
src/app/feedback/feedback-view.component.ts
src/app/feedback/feedback-view.scss
src/app/feedback/feedback.component.html
src/app/feedback/feedback.component.ts
src/app/feedback/feedback.module.ts
src/app/home/home-router.module.ts
src/app/home/home.component.html
src/app/home/home.module.ts
src/app/shared/couchdb.service.ts

For #556 
Still have a few todos:
- The stream times out after 1 minute, so there is a possibility of conflicts if people are sending messages at the same time but intermittently
- I'd like to have it sorted the opposite way, but start out scrolled to the bottom.  Didn't have the time to implement that, so sorted the most recent message at the top.
- After inserting a message, it flickers at the bottom before resorting the list.  And if there is a conflict error the message shows up in the list even though it's failed to be added to the DB.  Something is off there...
- Need to use PlanetMessageService for error messages.

[#556] Feedback message system

---

src/app/_variables.scss
src/app/home/home.component.html
src/app/home/home.scss

Adds some depth to the top & side navbars

Add navbar shadow

---

src/app/courses/add-courses/courses-add.component.html
src/app/courses/add-courses/courses-add.component.ts
src/app/courses/add-courses/courses-add.scss
src/app/courses/add-courses/courses-step.component.html
src/app/courses/add-courses/courses-step.component.ts
src/app/courses/constants.ts
src/app/courses/courses.module.ts
src/app/shared/material.module.ts

Here's a quick start to get us in a place to split into smaller tasks.
See #604 for mode info on the other tasks.

Start course revision

---

src/app/courses/add-courses/courses-add.component.html
src/app/courses/add-courses/courses-add.component.ts
src/app/courses/add-courses/courses-step.component.html
src/app/courses/add-courses/courses-step.component.ts
src/styles.scss

Continuing work on #604.
Adds a button to add steps to the course, and a form within the step expansion panel with a title and description.

604 Add steps and step title

---

src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts

[#625] resource article date shortend (connects #625)

---

src/app/courses/add-courses/courses-add.component.html
src/app/courses/add-courses/courses-add.component.ts
src/app/courses/add-courses/courses-step.component.html
src/app/courses/add-courses/courses-step.component.ts

Actually we can also do the remove in this adding condition of new position '-1'. But this seems to add more input output events using this method

[#666] Move Up Down of step

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/meetups/meetups.component.html
src/app/meetups/meetups.component.ts
src/app/resources/resources.component.html
src/app/resources/resources.component.ts
src/app/users/users.component.html
src/app/users/users.component.ts

sor far selection of checkbox is made clear on paginate

[#675] Clear selceted checkbox on change page ( connects #675)

---

src/app/dashboard/dashboard.component.ts

More of a temporary fix since myTeams will eventually be a list of teams, not single users.
Uses catchError to catch the error returned from CouchDB when trying to do a `_find` query on the `_users` database without admin credentials.

Fix loading dashboard info for non-admin (fixes #732)

---

README.md

I don't think this is comprehensive, but it at least covers some of the things that I've experienced & have come up on Gitter.

Troubleshooting in README (connects #590)

---

src/app/feedback/feedback-view.component.html
src/app/feedback/feedback-view.component.ts
src/app/feedback/feedback.component.html
src/app/feedback/feedback.component.ts
src/app/feedback/feedback.directive.ts

* Open close feedback
* Closing and opening date
* Title edit
* Icons of feedback type

[#772] Feedback status title (connects #772)

---

src/app/courses/add-courses/courses-add.component.ts
src/app/courses/add-courses/courses-step.component.html
src/app/courses/add-courses/courses-step.component.ts
src/app/shared/dialogs/dialogs-list.component.html
src/app/shared/dialogs/dialogs-list.component.ts
src/app/shared/dialogs/dialogs-list.service.ts
src/app/shared/dialogs/planet-dialogs.module.ts

[#665] Add resource to course step (connects #665)

---

src/app/courses/add-courses/courses-add.scss

Also fixed side step section to be responsive

[#693] Course add form style (connects #693)

---

src/app/dashboard/dashboard-tile.component.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts

Fixes for lint errors that made it to master

Lint fixes

---

src/app/configuration/configuration.component.html
src/app/configuration/configuration.component.ts

Current implemenation will show the confirmation checkbox or reset option.
We can also go with dialog but we do not have dialog module for confirmation only. Also form module does not support hidden input.

[#811] Confirmation message on domain change (connects #811)

---

src/app/_variables.scss
src/app/app.module.ts
src/app/courses/courses.module.ts
src/app/courses/courses.service.ts
src/app/courses/step-view-courses/courses-step-view.component.html
src/app/courses/step-view-courses/courses-step-view.component.ts
src/app/courses/step-view-courses/courses-step-view.scss
src/app/courses/view-courses/courses-view.component.ts
src/app/resources/resources.module.ts
src/app/resources/view-resources/resources-viewer.component.html
src/app/resources/view-resources/resources-viewer.component.ts
src/app/resources/view-resources/resources-viewer.scss
src/styles.scss

Shows the resource attached to the step alongside the step description.

[#668] Resource in step view

---

src/app/courses/view-courses/courses-view.component.html

[#829] No step disable view button (connects #829)

---

src/app/configuration/configuration.component.html
src/app/configuration/configuration.component.ts

This PR introduce new variable to check confirmation checked.

[#840] Introduce new variable for configuration confirm (connects #840)

---

.travis/travis_utils.sh

I have modified the code logic a bit to push the manifests when a new version (Github tag) is pushed. Please check it.

Fix versioned multiarch Logic

---

src/app/shared/dialogs/dialogs-form.component.html

Now we can generate select text field like this
const fields = [ 
{
'label': 'label',
'type': 'selectbox',
'option': [ 'option1', 'option2', 'option3' ],
'name': 'my name',
'placeholder': 'my placeholder',
'required': true
}
]

[#653] refactor dialogs-form.component.html (connects #653)

---

src/app/courses/add-courses/courses-add.component.ts
src/app/shared/form-error-messages.component.ts
src/app/validators/custom-validators.ts

As we might want to have memberLimit to be unlimited, allowing 0 as infinite number.
Also message of min will not look nice to say `less than 0` so created new validator to check negative.
Also added message for max as it might be used at some point so keeping both min and max as message.

[#831] Custom validator for positive number (connects #831)

---

.travis.yml

Updating Ubuntu package lists in travis (Fixes #1029)

---

src/app/configuration/configuration.component.ts
src/app/home/home.component.ts
src/app/notifications/notifications.component.ts

@paulbert getNotification and readNotification are duplicated in home component and notification component. Shall we create notification service or use userservice as notification update is served by userservice right now.

[#1004] Notification for community request (connects #1004)

---

src/app/shared/dialogs/dialogs-prompt.component.html
src/app/users/users.component.ts

Added extra section on dialog to show extra message. Update dialog to add condition of user as well.

[#1037] Add extra message on dialog (connects #1037)

---

README.md

Add build status in README.md

---

src/app/manager-dashboard/manager-dashboard.component.ts

[#1047] Adding password information while resending configuration on …(connects #1047)

---

src/app/login/login-form.component.ts

We might want to remove message or change message in catchError.

[#1041] Show different message for parent login fail (connects #1041)

---

src/app/home/pulsate-icon.directive.ts

No issue because brought up with @paulbert in PM.

Minor rxjs change, icon highlight directive

---

src/app/courses/step-view-courses/courses-step-view.component.html

Seemed like a small enough change to keep the logic in the template

Take exam to Continue Exam if not first step (connects #1023)

---

src/app/courses/courses.component.ts
src/app/dashboard/dashboard.component.ts
src/app/meetups/meetups.service.ts
src/app/resources/resources.component.ts
src/app/shared/user.service.ts
src/app/users/users.component.ts

#1102 
Uses a TypeScript get/set so everytime shelf on UserService gets updated the observable runs.  Also passes shelf through the observable so we don't have to access it on UserService in the subscription.

[#1102] Fix MeetupsService shelf (fixes #1102)

---

src/app/configuration/configuration.component.ts

It is just and immediate fix for the problem. We will go with connecting to nation after login on later phase.

[#1088] immediate fix for replicator failing (connects #1088)

---

src/app/app.component.spec.ts
src/app/configuration/configuration.component.ts
src/app/courses/courses.component.ts
src/app/debug-operator.ts
src/app/feedback/feedback-view.component.ts
src/app/feedback/feedback.component.ts
src/app/feedback/feedback.directive.ts
src/app/home/home.component.ts
src/app/meetups/meetups.component.ts
src/app/meetups/view-meetups/meetups-view.component.ts
src/app/nation/nation.component.ts
src/app/resources/rating-resources/resources-rating.component.ts
src/app/resources/resources-add.component.ts
src/app/resources/resources.component.ts
src/app/resources/view-resources/resources-view.component.ts
src/app/shared/couchdb.service.ts
src/app/users/users-profile/users-profile.component.ts
src/app/users/users.component.ts
src/app/validators/validator.service.ts
src/main.ts

Angular 6 includes an upgrade to RxJS 6 which removes all chain operators in favor of pipe operators.  So as a step one in the upgrade I converted our custom debug operator from chain to pipe.

Angular 6 Step 1: Refactor debug operator

---

src/app/debug-operator.ts

Works as intended, completes those that completes, previous issue with menu animation timer keeping going after unsubscription is also not an issue, so will revert rewrite using switchLatest from other PR

Rewrites debug without new observable (connects #1122)

---

src/app/page-not-found/page-not-found.component.html

[#1162] 404 should link back to app (connects #1162）

---

src/app/courses/step-view-courses/courses-step-view.component.html

@paulbert we might have exam that we previously attempted but later on removed that course from our shelf list. So just showing attempt if its more than zero

[#1140] Show attempt if past attempt (connects #1140)

---

src/app/courses/view-courses/courses-view.component.ts
src/app/feedback/feedback.component.ts
src/app/home/home.component.ts
src/app/meetups/meetups.service.ts
src/app/notifications/notifications.component.ts

Fix observable unsubscribe (fixes #1161)

---

src/app/feedback/feedback.component.html
src/app/feedback/feedback.component.ts

[#1186] Back button of feedback page redirecting to access restricted page (connect #1186)

---

src/app/courses/step-view-courses/courses-step-view.component.ts

Fix course step resources error (fixes #1207)

---

src/app/courses/step-view-courses/courses-step-view.component.ts

Fix past attempts on all steps (fixes #1202)

---

.travis.yml
couchdb-setup.sh
src/app/courses/courses.service.ts
src/app/courses/step-view-courses/courses-step-view.component.ts
src/app/courses/view-courses/courses-view.component.ts
src/app/exams/exams-view.component.ts

Tracks the most recent step a user was on and starts from there when the user reenters course.
#1201

Simple course progress (connects #1201)

---

src/app/exams/exams-view.component.ts
src/app/submissions/submissions.component.ts
src/app/submissions/submissions.service.ts

Grading status and prefill forms (connects #1193)

---

src/app/courses/step-view-courses/courses-step-view.component.html
src/app/courses/step-view-courses/courses-step-view.component.ts
src/app/exams/exams-add.component.ts
src/app/exams/exams-view.component.ts
src/app/submissions/submissions.service.ts

Courses: Disable next step until exam passes (connects #668)

---

src/app/users/users-update/users-update.component.ts

I have renamed the levels as 'Beginner', 'Intermediate', 'Advanced', 'Expert' , same as we are using for Courses. Please advise if we need to do it differently.
Thank you.

[#937] Meaningful Level (#937)

---

src/app/configuration/configuration.component.ts
src/app/login/login-form.component.ts

[#1090] Allow non-english characters in username (connects #1090)

---

src/app/courses/view-courses/courses-view.component.html
src/app/courses/view-courses/courses-view.component.ts

Attachment Icon has been placed in course step if there is resources.

[#1195] Attachment Icon in Course Steps (connects #1195)

---

.travis/travis_utils.sh

https://github.com/open-learning-exchange/planet/issues/1236

remove nohub from travis_utils.sh (fixes #1236)

---

angular.json

Set the poll property to 2000, which translates to checking for changes every 2 seconds.

[#1268] ng serve poll for changes (fixes #1268)

---

docker/planet.yml
src/app/exams/exams-view.component.html
src/app/exams/exams-view.component.ts
src/app/exams/exams-view.scss

Show the multiple choice answers as a list

---

src/app/resources/resources.component.ts

**Before remove**
**After remove**

[#1292] Remove hardcoded color in resourcesComponent (connects #1292)

---

src/app/users/users-profile/users-profile.component.html
src/app/users/users-update/users-update.component.html
src/app/users/users-update/users-update.component.ts

For now, I have displayed dates for the last 30 years,
i.e. it will show dates starting 1988, Is that fine @paulbert  or do we need to change that ?
Please advise.
CC: @lmmrssa , @dogi 
Thank you

[#1302] UserUpdate: Do not allow birth date in the future (#1302)

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/resources/resources-add.component.ts
src/app/resources/resources.component.html
src/app/resources/resources.component.ts
src/app/resources/resources.module.ts
src/app/shared/sync.service.ts

@paulbert @dogi This is the working example of resource to pull selected resource from parent. If this approach seems good then will work on creating more generic class for any database.

[#901] Pull selected resource from parent (connects #901)

---

src/app/users/users.component.html

[#1305] Add placeholder to select in users (fixes #1305)

---

.travis.yml
couchdb-setup.sh

only change in couchdb.sh
Pending: needs to change in resource component as well.

[#847] Separate Resource Attachments DB (connects #847)

---

.travis/travis_utils.sh

This Fixes #1354 .
Instead of checking only the branch name, we now check the latest Commit hash.

Check Latest commit (Fixes #1354)

---

src/app/home/home.component.html
src/app/home/home.component.ts
src/app/shared/languages.ts

Switches between the different languages as set up by Mappuji.
- Language names are now listed in their own language (or at least what Google says it is)
- Removed the flags and added the language in text to the top bar.  Flags !== language for many cases, so I don't think we should use them.

New language menu

---

src/app/shared/form-error-messages.component.ts
src/app/users/users-update/users-update.component.ts
src/app/validators/custom-validators.ts

[#1348] Invalid future date error message (connects #1348)

---

src/app/meetups/meetups.component.html
src/app/meetups/meetups.component.ts

Shall we control **Delete** button on title bar on selection of meetups by disabling or filter delete on component function.
Or do we need to have this button at all? @paulbert @lmmrssa

[#1421] meetup check owner on delete (connects #1421)

---

src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts

attachment is there on resource update.
added list of existing resource file in update page.

[#1423] resource_attachment (connects #1423)

---

.travis.yml
couchdb-setup.sh
src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/manager-dashboard/manager-dashboard.component.html
src/app/manager-dashboard/manager-dashboard.component.ts

This is just for the testing purpose right now.
It works for any new courses pushed to community.
If you push same course again it will have conflict.
It is non-replicator approach.

Push course

---

src/app/courses/progress-courses/courses-progress-leader.component.html
src/app/courses/progress-courses/courses-progress-leader.component.ts

Matches the design better by having step 1 at bottom going up to the final step at the top.
Also noted that the total error column was off, so added the small fix for that here.

Progress bottom to top and fix total errors (connects #1201)

---

src/app/resources/resources-add.component.html

[#1508]  non-mandatory drop down issue in Resource add / update form (connects #1508)

---

src/app/shared/dialogs/dialogs-list.component.html
src/app/shared/dialogs/dialogs-list.component.ts

[#1290] Dialog List when there is no record shows **Deselect all** (connects #1290)

---

src/app/resources/rating-resources/resources-rating.component.ts

Checked whether gender is set or not and if not made users to update the profile first.

[#1547] Resubmit rating does not update other details (connects #1547)

---

src/app/courses/view-courses/courses-view.scss

[#1539] course view layout issue (connects #1539)

---

src/app/configuration/configuration.component.ts
src/app/shared/couchdb.service.ts
src/app/shared/sync.service.ts
src/environments/environment.prod.ts
src/environments/environment.test.ts
src/environments/environment.ts

Allows us to create more complicated development environments with local nation & community on http connecting to Earth or center on https if needed.

Add parentProtocol environment variable

---

src/app/home/home.component.ts

Add teams to route with background (fixes #1637)

---

src/app/dashboard/dashboard.scss

Revision of the dashboard layout to better use the horizontal space

Narrower left section of dashboard

---

docker/planet/Dockerfile
docker/planet/upgrade.sh

[#1642] Remove usage of bash in upgrade script (fixes #1642)

---

package.json
src/app/upgrade/upgrade.component.ts
src/app/upgrade/upgrade.scss

[#1647] Added retry option when the docker timeouts (fixes #1647)

---

src/app/shared/dialogs/dialogs-form.service.ts

fixes feedback form focus

---

src/app/teams/teams-view.component.html

also removed the "disabled" attribute as it affects the color and style of button.

[#1711] team view request pending highlight (connects #1711)

---

src/app/resources/resources-add.component.html
src/app/resources/resources.component.html

Realized from a conversation with Richard he would prefer tags are called labels.

Switch from tags to labels in app

---

src/app/shared/submit.directive.ts

Checking the status of SpinnerDialog before closing (#1743 , #1765)

---

src/app/dashboard/dashboard-tile.component.html

Add Links in dashboard-tile.html (fixes #1771)

---

src/app/courses/courses.service.ts
src/app/courses/progress-courses/courses-progress-learner.component.ts
src/app/courses/progress-courses/courses-progress.component.html
src/app/shared/mangoQueries.ts

1487 previous course progress

---

src/app/community/community.component.html

removed reject filter since rejecting action is actually deleting the community request.

[#1784] rejected filter on community validation (connects #1784)

---

src/app/_variables.scss
src/app/configuration/configuration.component.html
src/app/configuration/configuration.component.ts
src/app/courses/add-courses/courses-add.component.html
src/app/courses/add-courses/courses-add.scss
src/app/resources/resources-add.component.html
src/styles.scss

As we want all form fields to have spacing added margin to all mat-form-field on right side.

[#1267] Add margin-right to mat-form-field (connects #1267)

---

src/app/resources/view-resources/resources-view.component.ts

Hide details on ResourceView init (fixes #1892)

---

src/app/login/login-form.component.html

Change the "Are you new" to "Become a member" in login-form component.

Change Are you new to Become a member (connects #1894)

---

src/app/submissions/submissions.component.html

Used the i18n select syntax for the submission header change.

Submission page header: change for surveys(connects #1883)

---

src/app/exams/exams-question.component.html
src/app/exams/exams-question.component.ts

fix multiple choice width for survey (fixes #1869)

---

src/app/configuration/configuration.component.ts
src/app/configuration/configuration.service.ts
src/app/manager-dashboard/manager-dashboard.component.ts
src/app/shared/user.service.ts

1487 configuration service

---

src/app/courses/add-courses/courses-add.component.ts
src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts

Fix adding exams to multiple steps

---

src/app/exams/exams-add.component.ts
src/app/validators/validator.service.ts

Allow survey & course exam to have same name (connects #1937)

---

src/app/exams/exams-question.component.html
src/app/exams/exams-view.component.html
src/app/exams/exams-view.component.ts

Multiple answer will not work for exams, but working for surveys.

Multiple answer option for survey question (connects #1966)

---

src/app/resources/resources.component.ts

Changing the resource selection to be based on id introduced an issue with deletion of multiple resources.

Fix deleting multiple resources (fixes #1978)

---

src/app/courses/step-view-courses/courses-step-view.component.html

course step title in default value when title is not set (fixes #1874)

---

src/app/resources/resources.component.html
src/app/resources/resources.component.ts

@paulbert please review the fixes.

[1975] resource-delete-allowed-creator-manager (connects #1975)

---

src/app/users/users.component.html
src/app/users/users.component.ts

Route parameters cannot be changed hence queryparams is used.

[1916] route parameters from user notification(connects #1916)

---

couchdb-setup.sh
design/security-update/security-update-once.json
design/security-update/security-update.json
docker/db-init/docker-entrypoint.sh
docker/install.yml
src/app/configuration/configuration.service.ts
src/app/login/login-form.component.ts
src/app/shared/couchdb.service.ts

Found another issue with auto accept: the `couchdb-setup.sh` script would overwrite changes to the permissions of the `_users` database.  I made some changes to the script, and to the db-init entrypoint which will also need to be tested.

Fix auto accept (fixes #2028)

---

src/app/login/login-form.component.html
src/app/login/login-form.component.ts
src/app/login/login-router.module.ts
src/app/manager-dashboard/manager-dashboard.component.html
src/app/users/users.component.html

switch user to member

---

src/app/courses/courses.component.html

@lmmrssa Please review the fix.

[2001] credit-disabled-in-courses(connects #2001)

---

src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts

@lmmrssa @paulbert   File upload is limit to 512 MB in resource addition.

[1980] file-size-limit-512MB-in-resource-add(connect #1980)

---

.travis/planet-travis.yml
Vagrantfile
docker/planet.yml

Depends on https://github.com/treehouses/rpi-couchdb/pull/31
Solves #2092

Use couchdb 2.2.0

---

src/app/resources/resources.component.ts

Show number of resources deleted when deleting resources.

Delete many resources(connects #2085)

---

src/app/courses/courses.component.ts

Fix course select all (connects #2080)

---

src/app/resources/resources.service.ts

Found an error which was causing problems when the resources reload after changes.  This fixes that error.
Final part of #2113

Fix resources _design filter (fixes #2113)

---

src/app/submissions/submissions.component.html
src/app/submissions/submissions.component.ts

remove toggle filter since this should only show surveys (fixes #2067)

---

src/app/surveys/surveys.component.ts

[#2148]Survey title sorting (connects #2148)

---

src/app/meetups/meetups.component.html

[#2159] Meetup: time null/empty (connects #2159)

---

src/app/exams/exams-view.component.ts

Fix answering question with no auto grading (fixes #2215) (fixes #2226)

---

src/app/exams/exams-add.component.ts
src/app/exams/exams-question.component.ts
src/app/validators/custom-validators.ts

Fix multiple answer correct choices tracking (fixes #2223)

---

src/app/feedback/feedback-view.component.html
src/app/feedback/feedback-view.scss

[#2222] expand the feedback title edit field (connects #2222)

---

src/app/feedback/feedback.component.html

(connects #2052) 
also add color to emphasize urgent item in priority list.

2052-feedback status and priority list color

---

src/app/resources/view-resources/resources-view.component.html

Add "open new tab"  button to resource view.

Add open new tab in resource view(connects #2073)

---

src/app/exams/exams-view.scss

Record survey : in case of multiple choice multi select question padding should be added at bottom(connects #2069)

---

src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/manager-dashboard/reports/reports.component.ts

Some left over unused variables from #1863

Clean up unused variables

---

src/app/exams/exams-view.component.html
src/app/exams/exams-view.component.ts

Fix grading exam (fixes #2262) (fixes #2279)

---

src/app/resources/resources.component.ts
src/app/shared/dialogs/dialogs-prompt.component.html

Will show number of resources before deleting in dialog prompt.
Fixes #2156

[#2156] Pass count data for resources into dialog prompt

---

src/app/courses/courses.service.ts
src/app/submissions/submissions.service.ts

Add reporting fields to courses_progress and submissions (fixes #2298)

---

src/app/manager-dashboard/reports/reports.component.html

[2281] Manager reports link to details

---

src/app/manager-dashboard/reports/reports.service.ts

issue #2288 
Remove satellite user from the **Total Users** in the community report.

Filter satellite user from report

---

src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/manager-dashboard/reports/reports.service.ts

Some resources appear without titles and users without names as it was mentioned here #2312 .

Exclude blank data from report

---

src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts

Fixes #2249
Updated title for an exam.

Updated exam title for add and update (fixes #2249)

---

src/app/shared/forms/form-error-messages.component.ts

Remove undefined error msg

---

src/app/configuration/configuration.service.ts

basically to prevent multiple clicking, i added the spinner in both new and updated configurations.

[#2164] duplicate configuration (connects #2164)

---

src/app/courses/progress-courses/courses-progress.component.html

[#2380] course-step-title in progress is set to step_no (connects #2380)

---

src/app/resources/view-resources/resources-view.component.html

issue #2414 
Added the following to resources view:
-  Level property
-  Space between multiple items

Add level properity and spacing in resource details

---

src/app/exams/exams-question.component.html
src/app/exams/exams-view.component.html

Added long answer option to exams/courses

---

src/app/courses/add-courses/courses-step.component.html
src/app/courses/add-courses/courses-step.component.ts
src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts
src/app/exams/exams-question.component.html
src/app/exams/exams-question.component.ts
src/app/exams/exams-view.component.html
src/app/shared/forms/planet-step-list.component.ts

Rather than using the Material expansion panel, use our custom planet-step-list component for exams & surveys to make scrolling a bit easier when working with many exam questions.

Cleaner form for exam questions

---

src/app/exams/exams-add.component.ts

Fixed survey console courseTitle error 

---

package.json
src/app/_variables.scss
src/app/manager-dashboard/manager-dashboard.component.ts
src/app/manager-dashboard/reports/reports-detail.component.html
src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/manager-dashboard/reports/reports-detail.scss
src/app/manager-dashboard/reports/reports.component.ts
src/app/manager-dashboard/reports/reports.service.ts
src/app/shared/utils.ts
src/typings.d.ts

Add report charts (connects #2442)

---

src/app/resources/view-resources/resources-view.component.html
src/app/resources/view-resources/resources-view.scss

View layout was expanding beyond height of screen.  This fixes that so the view fits within the container.

Fix resources view layout

---

src/app/shared/auth-guard.service.ts
src/app/shared/state.service.ts

Loads the resources into StateService to reduce the load time of the resources table is reduced.

Load resources on login

---

src/app/_variables.scss
src/app/login/login-form.component.html
src/app/login/login.scss
src/planet-mat-theme.scss

Changed background color of the login button (fixes #2467)

---

src/app/meetups/add-meetups/meetups-add.component.html

Added required to start day field (fixes #2492)

---

src/app/resources/resources-add.component.html
src/app/resources/resources.component.html
src/app/shared/forms/planet-forms.module.ts
src/app/shared/forms/planet-tag-input-dialog.component.html
src/app/shared/forms/planet-tag-input.component.html
src/app/shared/forms/planet-tag-input.component.ts
src/app/shared/forms/planet-tag-input.scss
src/styles.scss

Adds a dialog for some preset labels to add to resources.
Currently just showing "Subjects", but will add "Language", "Level", "Media", & "Resource Type"

Add dialog for labels (connects #2502)

---

src/app/resources/view-resources/resources-view.component.html
src/app/resources/view-resources/resources-viewer.component.ts

Fix expression change error in resource view

---

src/app/resources/resources-add.component.html

New to angular, and I wanted to try out something simple to see if everything was working correctly
This PR is referencing #2402

Changing lower to Upper

---

src/app/courses/courses.service.ts
src/app/courses/progress-courses/courses-progress-chart.component.html
src/app/courses/progress-courses/courses-progress-chart.component.ts
src/app/courses/progress-courses/courses-progress-leader.component.html
src/app/courses/progress-courses/courses-progress-leader.component.ts
src/app/courses/progress-courses/courses-progress-learner.component.html
src/app/courses/progress-courses/courses-progress-learner.component.ts
src/app/courses/progress-courses/courses-progress.component.html
src/app/submissions/submissions.service.ts

Change the progress view to start with an overview of all course steps.  You can click on the chart or use the menu in the top right to view a detail on the exams in the course.

Course progress leader overview

---

src/app/exams/exams-view.component.ts

when there is previous submission, its putting that answer as string so checkbox was not being able to update that answer.
and everytime as we provide the new answer to be submitted for survey hence i removed the old answer in case of survey.
@paulbert  do you have any better feedback?

[#2526] submission send survey update response (connects #2526)

---

src/app/app.component.ts
src/app/login/login-form.component.ts
src/app/shared/auth-guard.service.ts

@yuviii While checking out another issue, I realized this may be due to the configuration on StateService not getting updated when we do the initial setup.  I made a few tweaks and I think it's working now.
#2425

Fix first logout not working (fixes #2425)

---

src/app/resources/resources.component.ts

This partially solves the sorting issue here #2525.

Sort rate in resources mat table

---

src/app/shared/forms/planet-rating.component.ts

[#2538] Change rating pop-up placeholder

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts

Disabled Send course to parent till we figure out resolving conflict.
Remove empty exams while sending courses

Send course to child (connects #2549)

---

src/app/resources/view-resources/resources-viewer.component.ts

fixes #2415 
I solved this by adding a variable to control updating the resource.

Mutli Resource Visits Entries- 2415

---

src/app/manager-dashboard/manager-dashboard.component.html
src/app/manager-dashboard/manager-dashboard.component.ts
src/app/manager-dashboard/manager.service.ts

Changed **Get Courses** **Get Resources** **Get Exams** to use single button

[#2549] Manager view of get courses (connects #2549)

---

src/app/exams/exams-view.component.html

[#2546] Show question title in exams-view component

---

src/app/resources/view-resources/resources-viewer.component.html

Switching between videos on steps

---

src/app/login/login-form.component.html
src/app/login/login-form.component.ts
src/app/login/login.scss

[#2381] Added icon to toggle password visibility

---

src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts
src/app/exams/exams-question.component.html
src/app/exams/exams-question.component.ts
src/app/exams/exams.service.ts
src/app/shared/forms/planet-step-list.component.ts
src/app/validators/custom-validators.ts

Currently validation works as expected, but I need to implement better changes to the UI so the person creating an exam can see what questions are invalid.
#2594

Fix exam question validation (fixes #2594)

---

src/app/users/users-profile/users-profile.component.html
src/app/users/users-update/users-update.component.html

Update members profile heading

---

src/app/shared/forms/planet-forms.module.ts
src/app/shared/forms/planet-tag-input-dialog.component.ts
src/app/shared/forms/planet-tag-input.component.ts

Missing commits from #2638 that didn't pass the linter & I merged before noticing...
Most of the changes are in ba26fb0, the other commit just reorganizes into a different file.

Fix adding labels

---

src/app/resources/resources.component.html
src/app/resources/resources.component.ts

Resources: add to library button only counts unjoined & selected (fixes #2623)

---

src/app/meetups/meetups.component.ts
src/app/meetups/view-meetups/meetups-view.component.html

Meetups: minor fixes (fixes #2616)

---

src/app/courses/progress-courses/courses-progress-leader.component.html
src/app/courses/progress-courses/courses-progress-leader.component.ts

[#2596] CourseProgressLeader: filter steps without exam submission

---

src/app/resources/view-resources/resources-view.component.html

Spacing resource details

---

src/app/page-not-found/page-not-found.component.html
src/app/page-not-found/page-not-found.component.ts

Change 404 page style (fixes #2645)

---

src/app/shared/forms/planet-tag-input-dialog.component.html

Disable add label button if label is invalid (fixes #2708)

---

src/app/resources/resources.component.html
src/app/shared/forms/planet-tag-input-dialog.component.html
src/app/shared/forms/planet-tag-input-dialog.component.ts
src/app/shared/forms/planet-tag-input.component.ts

before filtering label
after filtering label

[#2662] Filtering labels: hide labels with no more results (connects #2662)

---

src/app/courses/progress-courses/courses-progress-learner.component.ts

Quick fix for an error showing up in the console with CoursesProgressLearner

Fix console error in CoursesProgressLearner

---

src/app/courses/view-courses/courses-view.component.html

Some kind of text message of button: suggestions(fixes #2600)

---

src/app/courses/progress-courses/courses-progress-chart.component.ts
src/app/courses/progress-courses/courses-progress-leader.component.ts

#2683
Ungraded answers (first step: two text answers; second step: 2 multiple choice and 1 text answer): 
Graded as incorrect text answers for 1 Step:

CoursesProgressLeader: total errors (fixes #2683)

---

src/app/resources/resources.component.html
src/app/resources/resources.component.ts
src/app/resources/resources.service.ts
src/app/shared/couchdb.service.ts
src/app/shared/state.service.ts

#2496 
Also includes a small change which will fix #2860 because without that change this would be hard to test.

Find all stream (connects #2496)

---

src/app/meetups/meetups.component.html
src/app/resources/resources.component.html

[#2880] add space between button and count in resource and meetup (connects #2880)

---

src/app/courses/add-courses/courses-add.component.ts
src/app/courses/courses.service.ts

Fix new course title validation after exam add (fixes #2939)

---

src/app/home/home.component.html

Add home link to top navigation (fixes #2926)

---

src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts

refer to https://github.com/open-learning-exchange/planet/pull/2387, and implement the same operation in the question list.

Clicking add question while editing question changes to edit new question

---

src/app/shared/forms/planet-step-list.component.html

Fixing an issue where attempting to switch which exam question you are editing submits the exam instead.
#2984

Fix exam submit when changing question (fixes #2984)

---

.mdlrc

Don't want to spend too much time on this, but if it works this will make CodeClimate a little easier to navigate

Add markdownlinter config for CodeClimate (fixes #2982)

---

src/app/validators/custom-validators.ts

Required some simplification on the custom required validator
#2992

Fix exam validation not working

---

src/app/courses/add-courses/courses-add.component.ts

Fix course add overwriting previous course (fixes #2991)

---

src/app/teams/teams.component.html

Teams: sort teams by createdDate (fixes #2942)

---

src/app/feedback/feedback.component.ts

Feedback: change feedback delete msg (fixes #2799)

---

src/app/home/home.component.html
src/app/home/home.scss

Navigation: active link style (fixes #2986)

---

src/app/shared/couchdb.service.ts

We had been catching all errors from CouchDB which meant in cases (like incorrect passwords) there was no error in the app when a request failed.
This fixes that and will actually fix the validator for #2540 and #2053

Fix lack of errors from couchdb

---

src/app/configuration/configuration.service.ts
src/app/home/home.component.html
src/app/login/login-form.component.ts
src/app/meetups/add-meetups/meetups-add.component.ts
src/app/meetups/view-meetups/meetups-view.component.ts
src/app/notifications/notifications.component.html
src/app/teams/teams.service.ts

Notifications: change font-weight (fixes #3008)

---

src/app/shared/user.service.ts

Removes profile images from member information syncing to nation.

Fix for sync when _users have _attachments (fixes #3097)

---

src/app/meetups/view-meetups/meetups-view.component.html
src/app/meetups/view-meetups/meetups-view.scss

Meetups: added link to a creator of meetup (fixes #3024)

---

src/app/resources/view-resources/resources-view.component.html
src/app/resources/view-resources/resources-view.scss

Resources: hide headers if empty (fixes #3086)

---

src/app/feedback/feedback-view.component.html
src/app/feedback/feedback-view.scss

Feedback: modify feedback layout (fixes #2418)

---

src/app/feedback/feedback-view.component.html

FeedbackView: change date format (fixes #3124)

---

src/app/exams/exams-view.component.html

Exams: add whitespace (fixes #3116)

---

src/app/manager-dashboard/manager-sync.component.ts
src/app/shared/sync.service.ts
src/app/users/users-achievements/users-achievements-update.component.ts
src/app/users/users-achievements/users-achievements.component.ts
src/app/users/users-achievements/users-achievements.service.ts

To test:
1. Edit Achievements, making sure to check off **Allow your achievements to be shared with the nation**
2. Run sync
3. You will now be able to see the achievements on the parent database
Note that this PR does not change the achievements view at all, so you will not be able to see the changes in the application.  That will be included in the PR for #3129

Achievements replicate on sync (fixes #3128)

---

src/app/users/users-profile/users-profile.component.html

Improve Button for Achievements (Fixes #3141)

---

src/app/shared/forms/planet-markdown-textbox.scss

Achievements: fix textbox in fullscreen mode (fixes #3089)

---

src/app/users/users-achievements/users-achievements.component.html
src/app/users/users-achievements/users-achievements.component.ts
src/app/users/users-achievements/users-achievements.scss

Maybe we could change text alignment. In that way, we will eliminate problems with lists and quotations, and overall it might look better.
vs

Achievements: change text alignment (fixes #3062)

---

src/app/exams/exams-view.component.html
src/app/exams/exams-view.component.ts

Converts the answer to a reactive FormControl & uses the existing CustomValidators.required to make sure text answers with just whitespace are invalid.
#2845

ExamsView: Require text for answers (fixes #2845)

---

src/app/users/users.component.ts

Users: Only show accepted communities in children list (fixes #3168)

---

src/app/resources/resources-add.component.html
src/styles.scss

(Fixes #2961) Make Readonly Text Grey

---

src/app/dashboard/dashboard-tile.scss

Dashboard: split long title (fixes #3187)

---

src/app/users/users-achievements/users-achievements.component.ts
src/app/users/users-achievements/users-achievements.service.ts
src/app/users/users-profile/users-profile.component.ts

Achievements: update with no achievements (fixes #3188)

---

src/app/manager-dashboard/manager-fetch.component.ts
src/app/manager-dashboard/manager-sync.component.ts
src/app/resources/resources.component.ts
src/app/shared/sync.service.ts

Fixes #3130

---

src/app/surveys/surveys.component.html
src/app/surveys/surveys.component.ts

Surveys: sort by date (fixes #2913)

---

src/app/manager-dashboard/manager-sync.component.ts

(Fixes #2781) Show In Progress/Loading When Ryn Sync Is Clicked

---

src/app/shared/dialogs/dialogs-form.component.html
src/app/shared/dialogs/dialogs-form.component.ts

Dialogs: disable submit button (fixes #2908)

---

src/app/manager-dashboard/manager-sync.component.ts

#3114 
Catches error for missing sync and continues stream.

Fix first sync error (fixes #3114)

---

src/app/users/users-achievements/users-achievements-update.component.ts

Fixes #3219

---

src/app/home/home.component.ts

Fixes #3215

---

src/app/users/users-achievements/users-achievements-update.component.ts

[Fixes #3220] Achievement: Change the Label in the Dialog Box

---

src/app/users/users-achievements/users-achievements.component.html

[Fixes #3240] Achievement: Middle name missing in name

[Fixes #3240] Achievement: Middle name missing in name

---

src/app/users/users-achievements/users-achievements.component.html

Fixes #3239 
Adds descriptors/labels to the references.

(Fixes #3239) Achievements: My References

---

src/app/submissions/submissions.component.html
src/app/submissions/submissions.component.ts

(Fixes #3194) See Profile of User Submitting Exam or Survey

---

src/app/users/users-achievements/users-achievements-update.component.ts

Resolves remainder of #3238. Changes ```Phone #``` to ```Phone Number``` in Reference Dialog Box.

[Fixes #3272] Resolves Remainder of #3238

---

src/app/users/users-achievements/users-achievements.component.html

[Fixes #3273] Hides Title of Unavailable Data

---

src/app/resources/resources.component.ts

Request is included in ResourcesService as of #3284

Resources: Remove redundant tags request

---

src/app/shared/dialogs/dialogs-list.service.ts
src/app/surveys/surveys.component.ts

[#3190] hide unaccepeted community registration request from send sur… (connects #3190)

---

src/app/shared/dialogs/dialogs-form.component.html
src/app/shared/forms/planet-rating.component.ts

Dialog: add rating confirm button (fixes #3300)

---

src/app/submissions/submissions.service.ts

[Fixes #1301] Grading Status of Auto Correct

---

src/app/meetups/view-meetups/meetups-view.component.html

[Fixes #3327] Hide Empty Fields in Meetups

---

src/app/submissions/submissions.component.html
src/app/submissions/submissions.component.ts

[Fixes #2904] hover on pending submission

[Fixes #2904] hover on pending submission

---

src/app/surveys/surveys.component.ts

[Fixes #3301] Survey: no. of time taken should not count status "pending"

[Fixes #3301] Survey: no. of time taken should not count status "pending"

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts

@paulbert,  As suggested by Laxman, the exams which are not graded, yet complete are taken into consideration for the badge. Please let me know if there are changes or additions to be made.

Submission count(exams not yet graded) badge on dashboard(fixes #3025)

---

src/app/meetups/view-meetups/meetups-view.component.ts

[Fixes #3348] Notification: meetup fixes

[Fixes #3348] Notification: meetup fixes

---

src/app/users/users-achievements/users-achievements-update.component.html

[Fixes #3339] Edit Achievement: Uppercase fixes of reference and date

[Fixes #3339] Edit Achievement: Uppercase fixes of reference and date

---

src/app/courses/view-courses/courses-view.component.html

[Fixes #3299] Separator on Course Steps

---

src/app/teams/teams-view.component.html

[Fixes #3297] Link to User Profile of Team Members

---

src/app/users/users-achievements/users-achievements-update.component.html

[Fixes #3319] Achievement: Header shows inconsistency in terms of username

[Fixes #3319] Achievement: Header shows inconsistency in terms of username

---

src/app/dashboard/dashboard.component.html
src/app/submissions/submissions.component.html

[Fixes #3374] mySurvey: Survey title change to mySurvey

[Fixes #3374] mySurvey: Survey title change to mySurvey

---

src/app/submissions/submissions.component.html

[Fixes #3379] Remove 'Not Graded' From Survey Status Options

---

src/app/users/users-profile/users-profile.component.html

[Fixes #3245] Achievement button on my profile view

[Fixes #3245] Achievement button on my profile view

---

src/app/surveys/surveys.component.ts

[Fixes #3349] Surveys: Column widths

[Fixes #3349] Surveys: Column widths

---

src/app/news/news.component.html

Fixes some spacing issues with #3418

News: Fix indentation and spacing

---

src/app/news/news.component.html
src/app/news/news.component.ts

Commits intended to be added to #3416

News: Action button changes

---

src/app/teams/teams-view.component.html

[Fixes #3377] View User Profiles of Team Join Requests

---

src/app/dashboard/dashboard-tile.component.html
src/app/dashboard/dashboard-tile.component.ts
src/app/shared/material.module.ts

[Fixes #3098] Drag and Drop Dashboard Items

---

src/app/submissions/submissions.component.ts

[#3403] Reset Dropdown When Switching Between Exams & Surveys

---

src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts

Removed fields in add resources (connects #3438)

---

src/app/shared/user.service.ts

Fixes the issue where an admin cannot update its profile or achievements.
#3350

Fix admin update error (fixes #3350)

---

src/app/users/users.component.html

[Fixes #3457] Member Search : Change search filter placeholder

[Fixes #3457] Member Search : Change search filter placeholder

---

src/app/teams/teams-view.component.html
src/app/teams/teams.component.html

[Fixes #3431] UI improvement

---

src/app/courses/view-courses/courses-view.component.html
src/app/courses/view-courses/courses-view.component.ts
src/app/resources/view-resources/resources-view.component.html
src/app/resources/view-resources/resources-view.component.ts

Course & resource: add edit button (fixes #2719)

---

src/app/news/news.component.html
src/app/news/news.component.ts

Fixes #3432 
Displays edit date

[Fixes #3432] Add Edit Date to News Post

---

src/app/resources/resources.component.html
src/app/resources/resources.component.ts
src/app/resources/resources.service.ts
src/app/shared/forms/planet-tag-input-dialog.component.html
src/app/shared/forms/planet-tag-input-dialog.component.ts
src/app/shared/forms/planet-tag-input.component.html
src/app/shared/forms/planet-tag-input.component.ts
src/app/shared/forms/rating.service.ts

Currently can only add collections.  Will try to add full collection management (list initializes with existing collections of selected so you can add/remove) tonight.

Resources: add many collections (fixes #3385)

---

src/app/dashboard/dashboard.component.html
src/app/news/news.component.ts

[Fixes #3433] ourNews: Edit title should be changed to "New Post"

[Fixes #3433] ourNews: Edit title should be changed to "New Post"

---

src/app/shared/couchdb.service.ts
src/app/shared/utils.ts
src/app/surveys/surveys.component.html
src/app/surveys/surveys.component.ts
src/app/surveys/surveys.module.ts

Surveys: delete surveys (fixes #2751)

---

src/app/resources/resources.component.ts
src/app/shared/table-helpers.ts

fixes #3419 
@paulbert Looks like working fine in my case. Just resetting the selection as well when the reset the button is clicked.
[https://www.useloom.com/share/6dc20972f8964c7483e02406ccb364f0](https://www.useloom.com/share/6dc20972f8964c7483e02406ccb364f0)

[#3419] selection-cleared-from filter 

---

src/app/home/home.component.html
src/app/meetups/view-meetups/meetups-view.component.html

[Fixes #3324] Notification link should be disable for user with no role

[Fixes #3324] Notification link should be disable for user with no role

---

src/app/users/users-update/users-update.component.html

[#3474] beta-toggle-hidden(connects #3474)

---

src/app/news/news.component.html

[Fixes #3401] ourNews: user with no role with access to post
**Learner**
**No role**

[Fixes #3401] ourNews: user with no role with access to post

---

src/app/users/users-achievements/users-achievements-update.component.html

[Fixes #3494] Show Sort Button For More Than One Achievements

---

src/app/users/users-update/users-update.component.html

[Fixes #3490] Validation Message In Its Proper Place

---

src/app/users/users-achievements/users-achievements-update.component.ts

acheivement sort breaking fixed (connects #3408)

---

src/app/users/users-achievements/users-achievements.service.ts

Achievements: filter missing resources (fixes #3216)

---

src/app/home/home.component.ts

[#3507] logout issues fixed when offline (connects #3507)

---

src/app/courses/step-view-courses/courses-step-view.component.html
src/app/courses/step-view-courses/courses-step-view.component.ts
src/app/resources/view-resources/resources-viewer.component.ts

Courses: filter missing resources in a step view (fixes #3398)

---

src/app/shared/user.service.ts

[#3492] admin-permission-on-update-fixed

---

src/app/courses/add-courses/courses-step.component.html
src/app/courses/add-courses/courses-step.component.ts
src/app/courses/courses-router.module.ts
src/app/courses/step-view-courses/courses-step-view.component.html
src/app/courses/step-view-courses/courses-step-view.component.ts
src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts
src/app/exams/exams-view.component.html
src/app/exams/exams-view.component.ts
src/app/surveys/surveys.component.ts

todo:
prevent adding more than one survey to a course

add surveys to courses fixes #3328

---

src/app/_variables.scss
src/app/dashboard/dashboard-tile.scss
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.scss
src/app/shared/beta.directive.ts

Starts the transformation from the old dashboard layout to the new one.
Changes can be viewed in beta mode.

New dashboard layout

---

src/app/users/users.component.html

[Fixes #3519] All members : View profile icon change

[Fixes #3519] All members : View profile icon change

---

src/app/news/news.component.ts

Please recommend other sections as well.

[#3537] autofocus on input field (connects #3537)

---

src/app/resources/resources.scss

Resources: buttons overlap (fixes #3546)

---

src/app/resources/resources.component.html
src/app/shared/planet-filtered-amount.component.ts
src/app/shared/shared-components.module.ts

Resources: show number of filtered resources (fixes #3520)

---

src/app/exams/exams-question.component.html

Survey: remove checkbox for multiple choice question (fixes #3568)

---

src/app/courses/courses.service.ts
src/app/courses/progress-courses/courses-progress-chart.component.html
src/app/courses/progress-courses/courses-progress-chart.component.ts
src/app/courses/progress-courses/courses-progress-chart.scss
src/app/courses/progress-courses/courses-progress-leader.component.html
src/app/courses/progress-courses/courses-progress-learner.component.html
src/app/courses/progress-courses/courses-progress-learner.component.ts

Still working on the scrolling portion of the issue.  May need to merge without that if it is too difficult.

Learner progress updates (fixes #3574)

---

src/app/exams/exams-view.component.html
src/app/exams/exams-view.component.ts

Fixes #3460 (or partially fixes #3460) 
The 'Submit Answer' button is replaced by 'Complete' when the user is on the last question.

[Fixes #3460] Add Complete Button to Exam/Survey

---

src/app/submissions/submissions.service.ts

Once user reaches the end of the exam/survey, "Submit Answer" takes user to the unanswered questions (if there are any). 
https://www.loom.com/share/d1e303eb6e154217aa57129dbef8800a

[Fixes #3553] Unanswered Questions in Exams/Surveys

---

src/app/_variables.scss
src/app/courses/progress-courses/courses-progress-chart.component.html
src/app/courses/progress-courses/courses-progress-chart.scss
src/styles.scss

CoursesProgress: anchor labels (fixes #3591)

---

src/app/courses/courses.component.ts
src/app/shared/sync.service.ts

Hey so I'm not sure how to test this and I wanted to get some feedback. I couldn't really think of anything else that looked like it needed to be changed. Is this all that needs to be done? I imagine not

update coursesItemsToSync for surveys

---

src/app/courses/progress-courses/courses-progress-bar.component.ts
src/app/courses/view-courses/courses-view.component.html
src/app/courses/view-courses/courses-view.component.ts

CourseDetails: add an icon to attempted step (fixes #3587)

---

src/app/exams/exams-view.component.ts
src/app/home/home-router.module.ts
src/app/submissions/submissions.component.ts

[Fixes #2761] Back button from viewing a survey

[Fixes #2761] Back button from viewing a survey

---

src/app/upgrade/upgrade.component.html
src/app/upgrade/upgrade.component.ts

Empty-password handled (connects #3609)

---

src/app/shared/authorized-roles.directive.ts
src/app/users/users.component.html
src/app/users/users.component.ts

[Fixes #3488] Members: Every active member is learner
**Role: Leader**
**Role: no role**

[Fixes #3488] Members: Every active member is learner

---

src/app/exams/exams-question.component.html
src/app/exams/exams-question.component.ts

ExamsAddQuestion: modify layout (fixes #3655)

---

src/app/exams/exams-add.component.html

@lmmrssa This is an RRR request

Change exam submit button to "Save"

---

src/app/meetups/view-meetups/meetups-view.component.html

Non user url fixed (connects #3695)

---

src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts

[Fixes #3702 ] ExamsAdd: Add "Return to course/surveys" button

[Fixes #3702 ] ExamsAdd: Add "Return to course/surveys" button

---

src/app/exams/exams-question.component.html

[Fixes #3675] Course Add : making the ''add choice" seems like button

[Fixes #3675] Course Add : making the ''add choice" seems like button

---

src/app/courses/view-courses/courses-view.component.html

[Fixes #3623 ] Course Detail: Take Exam and Take Survey should be uppercase

[Fixes #3623 ] Course Detail: Take Exam and Take Survey should be uppercase 

---

.travis/planet-travis.yml
Vagrantfile
docker/volumes.yml

#2445 
In addition to the folder structure change adds CouchDB `local.ini` to volumes for dev environment and `volumes.yml`

Docker volume mount changes (connects #2445)

---

src/app/courses/add-courses/courses-add.component.html
src/app/courses/add-courses/courses-add.component.ts

[Fixes #3610 ] CoursesAdd: Remove "Member Limit" and "Method"

[Fixes #3610 ] CoursesAdd: Remove "Member Limit" and "Method"

---

src/app/courses/add-courses/courses-step.component.html
src/app/courses/view-courses/courses-view.component.html

Courses: add survey icon (fixes #3611)

---

src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts
src/app/exams/exams-add.scss

Removes Exam Title Field

---

src/app/surveys/surveys.component.ts

still need to do some testing, but i think its fixed #3646

bug fixed survey count

---

src/app/courses/view-courses/courses-view.component.html

Removed "Method" from Courses View

CoursesView: Remove Method (fixes #3748)

---

src/app/exams/exams-add.component.ts
src/app/submissions/submissions.component.ts

This PR will make sure exam/survey title is also updated on course. But all submission done so far will still have issue. So those submission needs to be cleared on db.

Exam name not saved on course (connects #3744 #3753)

---

src/app/surveys/surveys.component.html
src/app/surveys/surveys.component.ts

[Fixes #3752] Survey: sorting missing in Course Linked column

[Fixes #3752] Survey: sorting missing in Course Linked column

---

src/app/meetups/meetups.component.html
src/app/meetups/meetups.component.ts

Prevents Joining Old Meetup From Menu

---

src/app/courses/view-courses/courses-view.component.html

Added NA to Language of Instruction if empty

coursedetail updated

---

src/app/community/community.component.ts
src/app/manager-dashboard/manager-dashboard.component.html
src/app/manager-dashboard/manager-dashboard.module.ts
src/app/manager-dashboard/manager.service.ts
src/app/manager-dashboard/manger-dashboard-router.module.ts
src/app/manager-dashboard/reports/myplanet-table.component.html
src/app/manager-dashboard/reports/myplanet-table.component.ts
src/app/manager-dashboard/reports/reports-myplanet.component.html
src/app/manager-dashboard/reports/reports-myplanet.component.ts
src/app/manager-dashboard/reports/reports-pending.component.ts
src/app/manager-dashboard/reports/reports.component.ts
src/app/users/users.component.ts

Add a view on manager dashboard to look into list of myPlanet.
It will still require to group same tablets and may be other detail reports.
This PR just has a starting point to facilitate looking into myPlanet connected.

List myplanet (connects #3629)

---

src/app/exams/exams-question.component.html
src/app/exams/exams.service.ts

#3781 
Still uses built in validator, but only for the correct question types

Fix test question validation (fixes #3781)

---

src/app/courses/add-courses/courses-add.component.html
src/app/courses/add-courses/courses-add.component.ts
src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/courses/courses.service.ts
src/app/courses/progress-courses/courses-progress-learner.component.ts
src/app/courses/step-view-courses/courses-step-view.component.ts
src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts
src/app/resources/resources.component.html
src/app/resources/resources.component.ts
src/app/resources/resources.service.ts
src/app/resources/view-resources/resources-view.component.html
src/app/resources/view-resources/resources-viewer.component.ts
src/app/shared/forms/form-error-messages.component.ts
src/app/shared/forms/planet-tag-input-dialog.component.ts
src/app/shared/forms/planet-tag-input.component.ts
src/app/shared/forms/tags.service.ts
src/app/shared/table-helpers.ts
src/app/shared/utils.ts
src/styles.scss

@lmmrssa Haven't moved on to adding to courses so far, but have refactored for adding to resources in the new format for the `tags` database.
Remaining Todos:
- Fix the tag count (that's why the collections search is showing up as blank)
- Refactor for "Change Collections" in ResourcesComponent
- Add course collections

Update collections & course collections (fixes #3772)

---

src/app/courses/courses.service.ts
src/app/submissions/submissions.service.ts

Fixes #3645 Ensure that the progress bar updates automatically once an exam is graded and all answers are correct.

Course Progress Bar

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/resources/resources.component.ts
src/app/resources/search-resources/resources-search.component.ts
src/app/shared/table-helpers.ts

#3815 
After creating the issue, noticed that there was a problem with the courses search as well.  This was related to the new tag/collection organization.

Fix resources & courses search (fixes #3815)

---

src/app/shared/sync.service.ts

Requires #3837 to see it in action.
Specifically for the "Get Courses" in the parent view

Fix course sync (fixes #3840)

---

src/app/courses/courses.component.html
src/app/resources/resources.component.html

Courses & Resources: Combine Toolbar Manager Actions Into Menu

---

src/app/submissions/submissions.service.ts

Opens Previous Submission Whenever User Attempts to Retake Survey

---

src/app/shared/sync.service.ts

Courses: Fix replication without collection (fixes #3863)

---

src/app/courses/courses.component.ts

Filter Course(s) By Clicking On Tag

---

src/app/shared/user.service.ts

[Fixes #3765] New member with empty shelf has courses on dashboard

[Fixes #3765] New member with empty shelf has courses on dashboard

---

src/app/meetups/view-meetups/meetups-view.component.html

Old meetup invite

---

src/app/courses/courses.component.html
src/app/shared/planet-filtered-amount.component.ts

I added a counter to the header on the Courses page, like the one on the Library page.

Add counter to Courses page header (fixes #3822)

---

src/app/resources/resources.component.html
src/app/resources/resources.scss
src/app/shared/forms/planet-forms.module.ts
src/app/shared/forms/planet-tag-input.component.html
src/app/shared/forms/planet-tag-input.component.ts
src/app/shared/forms/planet-tag-selected-input.component.ts
src/app/shared/planet-filtered-amount.component.ts

Resources: selected collections component (fixes #3699)

---

src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts

Preview is Restricted to Valid Exams

---

docker/planet/nginx/credentials.sh

Sanitize password to add one more **$**. Having two `$$` sanitize it so use **$** else it causes issue with docker

[#3833] Sanitize password

---

src/app/resources/resources.component.html
src/app/resources/resources.component.ts

included this issue as well : https://github.com/open-learning-exchange/planet/issues/3853

[#3856] Send Resource show no of resource (connects #3856)

---

src/app/courses/add-courses/courses-add.component.html
src/app/courses/add-courses/courses-add.scss
src/app/courses/view-courses/courses-view.scss

Picking up on a branch from @singharpita to fix the UI for some of the Course components where the available height for a container was not being used, making things difficult on laptops in particular.

Courses: Fix not using available space (fixes #3296)

---

src/app/manager-dashboard/manager-fetch.component.html
src/app/manager-dashboard/manager-fetch.component.ts
src/app/manager-dashboard/reports/pending-table.component.html
src/app/manager-dashboard/reports/pending-table.component.ts
src/app/manager-dashboard/reports/reports-pending.component.html
src/app/shared/sync.service.ts

Added feature to delete pending items from send to child.
Fixed to show title based on new document.
Added time of item sent.

[#3920] Delete sent items

---

src/app/courses/add-courses/courses-step.component.ts
src/app/exams/exams-add.component.html
src/app/exams/exams-add.component.ts
src/app/exams/exams-add.scss
src/app/exams/exams-question.component.html
src/app/exams/exams-question.scss
src/app/shared/forms/planet-markdown-textbox.scss
src/app/shared/forms/planet-step-list.component.ts
src/app/shared/forms/planet-step-list.scss

Changes for the ExamsAdd form based on requests from Richard.

ExamsAdd redesign

---

src/app/home/home.module.ts
src/app/news/news-list.component.html
src/app/news/news-list.component.ts
src/app/news/news.component.html
src/app/news/news.component.ts
src/app/news/news.module.ts
src/app/news/news.scss
src/app/news/news.service.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams-view.scss
src/app/teams/teams.module.ts

Adds a feed of messages for simple communication between team members

Teams: Add feed of messages

---

src/app/meetups/add-meetups/meetups-add.component.html

Add margin-lr class to radio buttons (connects #3788)

---

src/app/news/news-list.component.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts

Changed edit success message and new post message for team news.

Connects #3931

---

src/app/exams/exams-view.component.ts

changed this.examType === 'surveys' to this.examType === 'survey'

Fix type in exams-view (fixes #3713)

---

src/app/exams/exams-view.component.html
src/styles.scss

Added space - Issue#3950

---

src/app/exams/exams-question.component.ts

Adding Exams: Update correctChoices Upon Removal Of Choice

---

src/app/manager-dashboard/reports/reports-detail.component.html
src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/manager-dashboard/reports/reports-detail.scss

Large screen
Medium screen
Small screen

Reports: modify layout (fixes #3941)

---

src/app/exams/exams-question.component.html
src/app/exams/exams-question.scss

please checkout this fixed issue. @paulbert  @lmmrssa

Moved multiple choice checkbox (fixes 3983)

---

src/app/community/community.component.html
src/app/community/community.component.ts

please check this solved issue. @paulbert @lmmrssa

Manager delete hub button triggers expansion panel (fixes 3989)

---

src/app/news/news-list.component.html

please check this fixed issue @lmmrssa @paulbert

NewsList: show time with dates (fixes 4027)

---

src/app/_variables.scss
src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/shared/forms/planet-rating.component.ts
src/styles.scss

Important notes:
1. Added another color to `_variables.scss` called `secondary light`
2. Created new class in `styles.scss` called `secondary-light-color` (Here I removed highlight so it would not effect the highlight color - this was the problem of why they both would have the same color. I created a new class to not interfere with primary-light. Please tell me if I am allowed to do this)
3. Altered rating bar class to `secondary-light-color`
**Comment any changes neccesary, Thank you!**

Add class for rating bar for different color (fixes #3961)

---

src/app/news/news-list-item.component.html
src/app/news/news-list-item.component.ts
src/app/news/news-list.component.html
src/app/news/news-list.component.ts
src/app/news/news.module.ts
src/app/news/news.service.ts
src/app/shared/forms/planet-step-list.scss
src/app/teams/teams-view.component.html
src/styles.scss

Still a work in progress, but @lmmrssa wanted to give you a chance to see the direction I was thinking and give feedback.

News item reply

---

.travis.yml
couchdb-setup.sh
src/app/dashboard/dashboard-tile.component.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/manager-dashboard/manager-sync.component.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams.component.html
src/app/teams/teams.component.ts
src/app/teams/teams.service.ts

Very much an experimental branch right now.  Opening this PR so we can have a place for comments

Teams: Syncing teams

---

src/app/exams/exams-view.component.html
src/app/exams/exams-view.component.ts

Added a message to the exam preview window when the last question is correct.

Add message to exam preview on completion (fixes #3885)

---

src/app/surveys/surveys.component.html
src/app/teams/teams.component.html

maticons has been added on surveys and teams display table @paulbert @lmmrssa

Maticon on surveys and teams table (fixes 4010)

---

src/app/courses/add-courses/courses-step.component.ts

Add width to add resources dialog (connects #4020)

---

src/app/feedback/feedback.component.html

Add tooltip on hover for title (connects #4062)

---

src/app/news/news-list.component.ts
src/app/news/news.component.html
src/app/news/news.component.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts

solved issue inside teams and ourNews. @lmmrssa @paulbert

4041 team adding message inside message replies

---

src/app/shared/forms/planet-tag-input-dialog.component.html
src/app/shared/forms/planet-tag-input-dialog.component.ts
src/app/shared/forms/tags.service.ts

Fixes #3986 [Collections: Disable "Subcollection of" if collection has attached subcollections]

Fixes #3986 [Collections: Disable "Subcollection of" if collection has attached subcollections]

---

src/app/manager-dashboard/sync.directive.ts

Update error message to error object properties reason. In that case now it's look like "Document update conflict."

4082 fix [object][object]

---

src/app/feedback/feedback-view.component.ts

Issue #4083 
The issue of the persisting re-open button is now fixed.
In addition, an error message displays if there are any problems opening the feedback.
To replicate prod, comment out line 45

(Issue #4083) feedback spinner

---

src/app/app.component.ts
src/app/dashboard/dashboard-tile.component.html
src/app/dashboard/dashboard-tile.component.ts
src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts
src/app/shared/authorized-roles.directive.ts

Adds only the links that were on the vertical bar of the first dashboard design to myLife

Replace myMeetups with myLife (connects #4103)

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.component.ts

Replaces placeholder with the name property of the planet configuration

Include community name on top of beta dashboard (connects #4103)

---

src/app/teams/teams-view.component.html

Change `Show News` to `Show Messages`

Show Messages in team (Fix #4144)

---

src/app/dashboard/dashboard-tile.component.html

I tried to solve this problem exactly as it was and used nested link.
But nested link is [illegal](https://www.w3.org/TR/REC-html40/struct/links.html).
I tried to solve with relative/absolute position but is working bad with flex elements.
So, I solved this problem  in easy way wrapped picture and text within `<a>` element

4143 issue fix

---

src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts
src/app/resources/resources-add.scss
src/styles.scss

Fix action buttons for resource-add.component (connects #4118)

---

src/app/home/home.component.ts
src/app/shared/beta.directive.ts
src/app/shared/user.service.ts

Makes the dashboard a little less harsh on the eyes by including the background that is used in much of the app.

Add gradient background to dashboard (connects #4103)

---

src/app/news/news-list.component.ts

Same as #4194 except with a new branch name. Apparently `/` in the branch name breaks the Travis build.

News: Different message for posting reply (fixes #4171)

---

src/app/resources/search-resources/resources-search.component.ts

Library search filter (fixes 4153)

---

src/app/teams/teams-view.component.html
src/app/teams/teams.service.ts

Just starting the process of adding leadership to teams.  The creator of the team is the leader, with no special privileges at this stage.

Teams: Creator is "Team Leader"

---

src/app/login/login-form.component.ts

@lmmrssa This PR cleans up a possible cause for a new member not being set up correctly.
My theory is that if the LoginComponent loads before StateService has finished its request to get the configuration information, the resulting member will not have `planetCode`, `parentCode` and the `roles` will be empty just as we saw on Somalia.
This changes it so when the user clicks to create the account we get the configuration from `StateService`.
This will be difficult to test if it fixes the issue, but as long as all of the login functions still work I think we can merge.

Fix for member without planetCode

---

src/app/manager-dashboard/manager.service.ts
src/app/manager-dashboard/reports/reports-detail.component.html
src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/manager-dashboard/reports/reports.service.ts

Add filter report by **planet** or **myplanet** to check where the log has been coming from.
#3955 also specify about having detail list of resources/courses but this PR only adds filter for now.

[#3955] Add filter by myplanet

---

src/app/dashboard/dashboard.component.ts

thanx in advance for your review.

Dashboard: mySurvey number not showing (fixes 4176)

---

src/app/users/users.component.ts

Issue #4210
Also deletes user from team when a manager deletes that user

4210 deleted user team

---

src/app/users/users.component.html
src/app/users/users.component.ts

Fixes #4152 
Adds member filtering by roles of learner, leader, monitor, and manager.

[#4152] Member Role Filtering

---

src/app/resources/resources.component.html

thank you for your review in advance

Tick icon of myLibrary does not seem so visible (fixes #4251)

---

src/app/teams/teams.component.html
src/app/teams/teams.component.ts

4253_issue_fix

---

src/app/teams/teams.component.html

Submitting updated PR with clean commits.

Update: add timestamp in Team list page (fixes #4239)

---

src/app/teams/teams.component.ts

#4234 
Team removed after archival

4234 teams leave

---

src/app/teams/teams.service.ts

thank your for your review in advance.

4235 team name duplicate

---

src/app/courses/courses.component.html

its similar to the below issue:
Tick icon of myLibrary does not seem so visible #4251

Tick icon of courses does not seem so visible

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/users/users-profile/users-profile.component.ts

Part of code is also related to #4188 but please feel free to update it for #4188 to have better representation

[#4187] Synced user profile view

---

src/app/upgrade/upgrade.component.html
src/app/upgrade/upgrade.component.ts

Only render reboot message if the mode is equal to planet

Conditionally output reboot message (Fix #4081)

---

src/app/courses/add-courses/courses-add.component.spec.ts
src/app/home/home.component.ts
src/app/login/login-form.component.ts
src/app/meetups/add-meetups/meetups-add.component.ts
src/app/notifications/notifications.component.ts
src/app/resources/resources-add.component.ts
src/app/resources/view-resources/resources-view.component.ts
src/app/shared/dialogs/dialogs-list.service.ts
src/app/shared/dialogs/planet-dialogs.module.ts
src/app/shared/forms/rating.service.ts
src/app/shared/table-helpers.ts
src/app/users/users-achievements/users-achievements-update.component.ts
tslint.json

This is an error I see popping up often, and I just noticed there is a lint rule for it.
This automatically checks for multiple spaces between text in ts files and rejects if there are any.

Add lint rule for multiple spaces

---

src/app/teams/teams.service.ts

thank you in advance for your review

team resources list should be sorted alphabetically (fixes #4286)

---

src/app/teams/teams.service.ts

while editing a team that changes the team creater (fixes #4297)

---

src/app/news/news-list-item.component.html
src/app/news/news-list-item.component.ts
src/app/news/news-list-item.scss

[Fixes# 4170] Team message: should be show more/show less button for long message

[Fixes# 4170] Team message: should be show more/show less button for long message

---

src/app/community/community-table.component.ts
src/app/courses/courses.component.ts
src/app/manager-dashboard/manager-dashboard.component.ts
src/app/meetups/view-meetups/meetups-view.component.ts
src/app/resources/resources.component.ts
src/app/shared/dialogs/dialogs-form.component.ts
src/app/shared/dialogs/dialogs-list.component.html
src/app/surveys/surveys.component.ts
src/app/teams/teams-view.component.ts

#4298 
Adds message on empty list

#4298 Message on empty list for dialog

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams.component.html
src/app/teams/teams.component.ts
src/app/teams/teams.module.ts
src/app/teams/teams.service.ts

teams leader can delete, not leave (fixes #4211)

---

src/app/resources/resources.component.html

Compares ```stateService.configuration.code``` with ```element.doc.sourcePlanet```. If not, show value of ```sourcePlanet``` or 'NA' if key doesn't exist

issue 4209 fix

---

src/app/courses/add-courses/courses-step.component.ts
src/app/shared/dialogs/dialogs-add-resources.component.ts
src/app/teams/teams-view.component.ts

Adds spinner on okClick in add resources dialog box in teams view

4309 spinner ok

---

src/app/shared/material.module.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams-view.scss
src/app/teams/teams.module.ts
src/app/teams/teams.service.ts

I moved the Requested Member template with the Joined member together so they could be under one tab. Let me know if that’s ok?

Create tabs in team view (fixes #4233)

---

src/app/users/users.component.html

Members: Show learner chip for every active member(fixes #4288)

---

src/app/validators/validator.service.ts

#4348
Allows for special characters to be used

[#4348] special char check added

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams.component.html
src/app/teams/teams.component.ts

thank you for your review in advance

confirmation before deleting team (fixes #4359)

---

src/app/shared/dialogs/dialogs-prompt.component.html
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts

4336 teams view dialogue box

---

src/app/users/users.component.html

Fixes #4370: Members: Move clear button

Fixes #4370: Members: Move clear button

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.scss

team manager can now delete form team view (fixes #4387)

---

src/app/_variables.scss
src/app/dashboard/dashboard.component.ts
src/app/exams/exams-add.scss
src/app/health/health-update.component.html
src/app/health/health-update.component.ts
src/app/health/health-update.scss
src/app/health/health.component.html
src/app/health/health.component.ts
src/app/health/health.module.ts
src/app/health/health.service.ts
src/app/home/home-router.module.ts
src/app/home/home.component.ts

The form only saves data for the duration of the session.  Once the user refreshes or another user logs in & opens their health page the information is gone.
The form can be accessed by clicking "myHealth" in the "myLife" section on the dashboard.  Note the link will only show up if beta mode is enabled.

Health beta: Form & displayed information

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/dashboard/dashboard.component.html
src/app/home/home-router.module.ts
src/app/home/home.component.ts
src/app/resources/resources.component.ts

Fixes: Planet Dashboard tiles (myCourses)

Fixes# 4339: Planet Dashboard tiles

---

src/app/resources/resources-add.component.ts

#4417 Add new resource infinite spinner fix when not all required fields filled out

#4417 infinite spinner fix

---

src/app/teams/teams-view.component.ts

#4430
You can now reroute to a new team using notifications when on a different team.

#4430 Team change on notification click

---

src/app/dashboard/dashboard.component.html
src/app/dashboard/dashboard.scss

4397 issue fix

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.scss

#4280 mat-card change made

---

src/app/users/users.component.html
src/app/users/users.component.ts

Currently there's a problem with `selection.changed`

#4358 member selection if manager

---

src/app/courses/courses.component.ts

Fixes the typo so the filter works correctly
#4445

Courses: Fix myCourses filter (fixes #4445)

---

src/app/courses/courses.component.html
src/app/resources/resources.component.html

For courses you won't see the **myCourses** header without #4454, but otherwise fixes the headers to show **Courses**, **Library**, and **myLibrary**
Issue #4444

Courses & Resources: Fix missing headers

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.scss

@paulbert made changes on Team Member and Resources. Shall we make changes on Requested Members as well?

[#4448] Change remove button to icon on team

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams-view.scss

4188 user planet

---

src/app/courses/courses.component.html
src/app/resources/resources.component.html
src/app/shared/forms/planet-tag-input.component.html
src/app/shared/forms/planet-tag-input.component.ts

Only increase the size of the button next to the main header:

Resources & Courses: Increase font size of collections button

---

src/app/teams/teams-view.component.ts

4466 teams view title validator

---

src/app/resources/resources-add.component.html
src/app/resources/resources-add.component.ts

3851 resources add file validation

---

src/app/login/login-form.component.ts
src/app/shared/database/pouch-auth.service.ts
src/app/shared/database/pouch.service.ts

I had to make some changes to PouchDB Auth to make it work it with new PouchDB 7. I also updated the service to make it more sensible to deal with Pouch's API.

Update PouchDB Service and auth 

---

src/app/shared/forms/planet-tag-input-dialog.component.html
src/app/shared/forms/planet-tag-input-dialog.component.ts

Fix issue #4449 clicking on collections with subcollections

---

src/app/dashboard/dashboard-tile.component.html
src/app/dashboard/dashboard.component.ts

thank you in advance for your review

4464 team leave dashboard

---

src/app/courses/courses.component.html
src/app/resources/resources.component.html

Preliminary PR, am only able to sort the entire table rather than just the ratings column.  Once this is fixed I'll apply it to all the other pages.

4494 Sort ratings by descending order

---

src/app/resources/resources.component.html

description now in right place (fixes #4479)

---

src/app/manager-dashboard/reports/myplanet-table.component.html
src/app/manager-dashboard/reports/myplanet-table.component.ts

count changed to totalSynced (fixes #4328)

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.scss

thanks for the review in advance

replaced with menu in teamsView (fixes #4550)

---

src/app/courses/courses.component.html
src/app/shared/forms/planet-tag-input-dialog.component.ts
src/app/shared/forms/planet-tag-input.component.ts

Based on request from RRR.  Starting with just Courses.

Courses: Select only one collection at a time

---

src/app/dashboard/dashboard.component.html
src/app/home/home-router.module.ts
src/app/home/home.component.ts
src/app/teams/teams.component.html
src/app/teams/teams.component.ts

Fixes# 4339: Planet Dashboard tiles (myTeams)

Fixes# 4339: Planet Dashboard tiles (myTeams)

---

src/app/resources/view-resources/resources-view.component.ts

#4509 Redirects to resources if resource nonexistent

---

src/app/shared/shared-components.module.ts
src/app/tasks/tasks.component.html
src/app/tasks/tasks.component.ts

4596 tasks dropdown

---

src/app/shared/dialogs/dialogs-prompt.component.html
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts

4556 remove confirmation

---

src/app/tasks/tasks.component.html
src/app/tasks/tasks.component.ts

thank you for the review.
would it be better to use unassignee inside assignee menu list?

4598 task unassigning

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts

TeamsView: Refactor DialogsPromptComponent (fixes #4396)

---

src/app/shared/user.service.ts

Teams: Fix no response after joining connected team (fixes #4587)

---

src/app/tasks/tasks.component.html
src/app/tasks/tasks.component.ts

Tasks: Fix assigning member from other planet (fixes #4630)

---

src/app/shared/forms/form-error-messages.component.ts
src/app/tasks/tasks.service.ts

team task validation in date (fixes #4636)

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/resources/resources.component.html
src/app/resources/resources.scss
src/styles.scss

description repositioned in resources and courses (fixes #4672)

---

src/app/courses/view-courses/courses-view.component.html

Noticed this branch today.  Fixed an issue but the PR was never created...

Courses: Change progress label (fixes #4223)

---

src/app/home/home-router.module.ts
src/app/home/home.component.html
src/app/home/home.component.ts
src/app/teams/teams-view-finances.component.html
src/app/teams/teams-view-finances.component.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams.component.html
src/app/teams/teams.component.ts
src/app/teams/teams.module.ts
src/app/teams/teams.service.ts

To test you will need to enable "beta" features.  "Enterprises" will replace "Meetups" in the top menu after that.
Enterprises are very similar to teams, but courses are replaced with "Finances".  Currently that tab includes a table of financial transactions that enterprise members can add to.

Enterprises beta

---

src/app/teams/teams-view.component.html

add course button shows in teams (fixes #4694)

---

src/app/teams/teams-view-finances.component.html

This fixes the negative sign problem from #4703 , and also the rounding problem from #4711

Use currency pipe in enterprise finances

---

src/app/teams/teams.component.html

delete All Member button in Enterprise(fixed #4709)

---

src/app/meetups/meetups.component.html

Raw.Github: 
https://raw.githack.com/dogeTheCoder/planet/removed-view-#4612/src/app/meetups/meetups.component.html

removed view option fixes ( #4612 )

---

src/app/dashboard/dashboard-tile.component.ts

confirmation dialog changed in dashboard (fixes #4713)

---

src/app/teams/teams-view.component.ts

TeamsView now Uses spinner for Add Members (fixes #4736)

---

src/app/teams/teams.service.ts

4695 team add plan

---

src/app/shared/forms/form-error-messages.component.ts
src/app/teams/teams-view-finances.component.ts

added positive number validator(Fixed #4692)

---

src/app/tasks/tasks.component.ts
src/app/tasks/tasks.service.ts

4764 deadline timestamp number

---

src/app/meetups/view-meetups/meetups-view.component.html

Fixes Meetups: No member message.

Update meetups-view.component.html (fixes #4608)

---

src/app/teams/teams.component.html
src/app/teams/teams.component.ts

Deleted type col (Fixed 4758)

---

src/app/submissions/submissions.component.ts

First completed:
"1. Now that this view begins filtered, we could show the message any time the filter ends up with 0 results."
Please check if everything is according to plan and if I should carry on to:
"2. We could also hide the "Tests/Surveys" button switch if only one exists. Or only show the one that exists so the label is there."

Survey/mySurveys: Add empty message for data of 0 length (Fixes #4391)

---

src/app/teams/teams-view.component.html

TeamsView course now looks different (fixes #4592)

---

src/app/dashboard/dashboard-tile.component.html

tile color modified (fixes #4554)

---

src/app/teams/teams.service.ts

change notification team type (Fixed 4793)

---

src/app/submissions/submissions.component.ts

4792 submissions table

---

src/app/teams/teams-view.component.ts

change to goback (Fixed 4761)

---

src/app/app.module.ts
src/app/courses/courses.service.ts
src/app/feedback/feedback.service.ts
src/app/manager-dashboard/manager.service.ts
src/app/notifications/notifications.service.ts
src/app/resources/resources.service.ts
src/app/shared/auth-guard.service.ts
src/app/shared/couchdb.service.ts
src/app/shared/database/pouch-auth.service.ts
src/app/shared/database/pouch.service.ts
src/app/shared/forms/rating.service.ts
src/app/shared/forms/tags.service.ts
src/app/shared/planet-message.service.ts
src/app/shared/sync.service.ts
src/app/shared/user.service.ts
src/app/submissions/submissions.service.ts
src/app/teams/teams.service.ts
src/app/validators/validator.service.ts

refactors issue 4753: https://github.com/open-learning-exchange/planet/issues/4753
should i remove the whole providers attribute?
If so what should i do about MatIconRegistry?

WIP: Issue #4753-refactor-services-declaration

---

src/app/teams/teams.service.ts

added default team type(Fixed 4827)

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams-view.scss

Members of the team and any admins can now see the day of the most recent visit for all team members.

Show most recent visit for team members

---

src/app/teams/teams-view.component.ts

I add a rule to check if the user is expecting a response to a request

4613 issue

---

src/app/health/health-event.component.html
src/app/health/health-event.component.ts
src/app/health/health-update.scss
src/app/health/health.component.html
src/app/health/health.component.ts
src/app/health/health.module.ts
src/app/health/health.service.ts
src/app/home/home-router.module.ts

Adds **Add Examination** button which leads to a form to fill in health records from a visit to a clinic.
Note this information is not saved to the database at this stage of development, so after refreshing it will no longer appear.

myHealth events

---

src/app/meetups/view-meetups/meetups-view.scss

fixed #4829 and #4869 
I only changed css to fix the issue, and arbitrarily used `height: 60vh` to limit the height. Please let me know if there is any better way to fix the issue.

change display to block(Fixed 4829)

---

src/app/manager-dashboard/sync.directive.ts
src/app/meetups/add-meetups/meetups-add.component.ts
src/app/shared/calendar.component.ts
src/app/shared/dialogs/dialogs-add-meetups.component.ts
src/app/teams/teams-view.component.html

4891 team event synced

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts

Fixes #4640 
Syntax still needs fix

Add matbadge on tasks

---

src/app/meetups/add-meetups/meetups-add.component.ts
src/app/validators/custom-validators.ts

4914 meetups add require

---

src/app/shared/dialogs/dialogs-resources-viewer.component.ts
src/app/shared/dialogs/dialogs-resources-viewer.module.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams.module.ts

resources opens in new tab in teamsView (fixes #4429)

---

src/app/teams/teams-view-finances.component.ts

changed finance order( Fixed 4895)

---

src/app/tasks/tasks.component.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams.service.ts

#4871 
I added `activeTab` to manage required tab in one place, so I also changed code in task link. Please let me know if there is a better way to do it.

change request notification link( Fixed 4871)

---

src/app/health/health-event-dialog.component.html
src/app/health/health-event-dialog.component.ts
src/app/health/health.component.html
src/app/health/health.component.ts
src/app/health/health.module.ts

Health: Events in table (fixes #4933)

---

src/app/meetups/add-meetups/meetups-add.component.ts
src/app/validators/custom-validators.ts

MeetupsAdd: Fix time validation (fixes #4928)

---

src/app/teams/teams-view-finances.component.ts

TeamsViewFinances: Fix credit/debit change (fixes #4952)

---

src/app/teams/teams-view.component.ts

TeamsView: Fix tasks changing after member change (fixes #4958)

---

src/app/shared/dialogs/dialogs-prompt.component.html
src/app/teams/teams-view-finances.component.ts

add transaction description( Fixed 4959)

---

src/app/teams/teams-view.component.ts

TeamsView: Fix member visit data display (fixes #4972)

---

src/app/shared/calendar.component.ts

Calendar: Show time in 24-hour (fixes #4819)

---

src/app/shared/user.service.ts

Dashboard: Fix missing profile image (fixes #4996)

---

src/app/teams/teams-view.component.ts

Community: Fix message replies & edit (fixes #4990)

---

src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/shared/dialogs/dialogs-form.component.html
src/app/shared/forms/form-error-messages.component.ts
src/app/validators/custom-validators.ts

report date validation(Fixed 4977)

---

src/app/health/health.component.html

made the header of the column clickable, hope that was enough to fix the issue. please review and comment. thank you

Health Condition and Treatment view in dialog (fixes #4997)

---

src/app/shared/utils.ts
src/app/teams/teams.component.ts
src/app/teams/teams.service.ts

Fixes #4916 
Changed the title on creating Team and Enterprise, which now says "Enterprise created successfully" and "Team created successfully".

Changed the title on creating enterprise and team (fixes #4916)

---

src/app/health/health.service.ts

Health: Fix incorrect member exams showing (fixes #5021)

---

src/app/shared/user.service.ts

Fixes the issue with Health by making sure that when login & logout occurs the `userChange$` observable emits an event to any listeners (including `HealthService`)

Health: Fix key after logout/login (fixes #5010)

---

src/app/teams/teams-view.component.html

#4931 
thank your for the review.

task title on members tile overlaps (fixes #4931)

---

src/app/courses/courses.component.ts
src/app/resources/resources.component.ts
src/app/shared/sync.service.ts

5034 allow push (fixes #5034)

---

src/app/manager-dashboard/reports/reports.service.ts
src/app/shared/user.service.ts
src/app/teams/teams.service.ts
src/app/users/users.service.ts

Needed to do some more fixes beyond `UserService` to make sure the private properties are not showing up in the tasks database.

UserService: Fix private props in other DBs (fixes #5062)

---

src/app/teams/teams-view.component.html

Fixes #4932 
Added office to the title of all/any enterprises.

Added Office to the title for Enterprises(fixes #4932)

---

src/app/health/health.scss

Fixes #5042 
Changed the min-width of the columns in Examination table to 100px.

Updated width of examination columns to 100px(fixes #5042)

---

src/app/users/users.component.html
src/app/users/users.component.ts

Users: Fix removing role (fixes #5104)

---

src/app/teams/teams-view.component.html
src/app/teams/teams-view.scss

Fixes# 4453: Team courses and resources tiles should be clickable

Fixes# 4453: Team courses and resources tiles should be clickable

---

src/app/meetups/add-meetups/meetups-add.component.ts

MeetupsAdd: Remove past date restriction (fixes #5097)

---

src/app/health/health.component.html
src/app/health/health.component.ts

Health: Sort exams ascending and scroll on init

---

src/app/health/health-update.component.html
src/app/health/health-update.component.ts

HealthUpdate: Add email validator (fixes #5054)

---

src/app/dashboard/dashboard-notifications-dialog.component.html
src/app/dashboard/dashboard-notifications-dialog.component.ts
src/app/dashboard/dashboard.component.ts
src/app/home/home.module.ts
src/app/login/login-form.component.ts

Adds a dialog after a member logs in if they have any surveys to complete.

Dashboard: Dialog for unfinished surveys (fixes #5147)

---

src/app/configuration/configuration.service.ts

Notifications: Fix Planet new request link (fixes #5128)

---

src/app/health/health.service.ts
src/app/shared/utils.ts

Note: This requires the database prefix from #5145.  The easiest way to have that setup is to checkout that branch, run `./v-couchdb-setup.sh`, and then checkout this branch.

Health: Use peruser databases for keys

---

src/app/teams/teams-view.component.html

added planet code( Fixed 5143)

---

src/app/teams/teams-view.component.html

chat instead of messages in teamsview (fixes #5094)

---

src/app/submissions/submissions.component.html
src/styles.scss

issue #5039 
Thank you in advance for your review.

submission table height fixed (fixes #5039)

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts

issue #5072 
thank you for your review in advance.

 add created on (fixes #5072)

---

src/app/meetups/view-meetups/meetups-view.component.html

Changed CreatedBy on MeetupsView to text (fixes #4825)

---

src/app/meetups/view-meetups/meetups-view.component.html
src/app/shared/calendar.component.ts

Added 'Completed On' to task popup on Calendar (fixes  #4935)

---

src/app/community/community.component.html
src/app/community/community.component.ts
src/app/news/news-list-item.component.ts

isssue #5201 
Thank you in advance for your review.

5201 conflit on wording message

---

src/app/teams/teams-view.component.html

issue #5127 
Thank you in advance for your review.

resources and courses show description (fixes #5127)

---

src/app/dashboard/dashboard.component.ts

console log removed from dashboaed (fixes #5214)

---

src/app/community/community-link-dialog.component.html
src/app/community/community-link-dialog.component.ts
src/app/community/community.component.ts
src/app/teams/teams.component.ts

issue #5208 
Thanks in advance for your review.

linkid added for team enterprise link (fixes #5179)

---

src/app/news/news-list-item.component.ts

issue #5210 
Thanks in advance for your review.

edit post changed to edit message/story (fixes #5210)

---

src/app/health/health-list.component.html
src/app/health/health-list.component.ts
src/app/health/health.component.html
src/app/health/health.component.ts
src/app/home/home-router.module.ts
src/app/home/home.component.html
src/app/home/home.component.ts
src/app/home/home.module.ts
src/app/shared/authorized-roles.directive.ts
src/app/tasks/tasks.component.ts
src/app/tasks/tasks.service.ts
src/app/users/users-table.component.html
src/app/users/users-table.component.ts
src/app/users/users.component.html
src/app/users/users.component.ts
src/app/users/users.module.ts
src/app/users/users.service.ts

For members with the "Health" role there is a link in the upper right that leads to a list of members.  Clicking a member opens their profile & examination information can be added from here.
Right now there is little detail on **HealthListComponent**, but if this works to update Health examinations of other members we should merge and add more detail in later PRs.
Note there is also a fairly substantial refactor of **UsersComponent** so the table could be reused for this list.

Health: Member list for provider

---

src/app/manager-dashboard/manager.service.ts
src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/manager-dashboard/reports/reports-myplanet.component.ts
src/app/manager-dashboard/reports/reports-pending.component.ts
src/app/manager-dashboard/reports/reports.component.ts
src/app/manager-dashboard/reports/reports.service.ts
src/app/manager-dashboard/reports/reports.utils.ts
src/app/manager-dashboard/requests/requests.component.ts
src/app/shared/dialogs/dialogs-list.service.ts
src/app/shared/sync.service.ts
src/app/surveys/surveys.component.ts
src/app/upgrade/upgrade.component.ts
src/app/users/users.component.ts

From work on a few issues I've noticed that we are 1 extra import away from a circular dependency in a few files.
I untangled our service dependencies a little so this does not block critical issues from being fixed.

Refactor to reduce risk of circular dependency

---

src/app/shared/user.service.ts
src/app/users/users-achievements/users-achievements-update.component.html
src/app/users/users-achievements/users-achievements.component.html

undefined middle name in achivements (fixes #5234)

---

src/app/health/health.component.html

Health username is shown (fixes #5233)

---

src/app/resources/view-resources/resources-viewer.component.ts

resource link added to resource activities (fixes #5164)

---

src/app/exams/exams-view.component.html
src/app/exams/exams-view.scss

Added span tag to ExamsView options text(fixes #5203)

---

src/app/health/health.scss

space between toolbar and main content (fixes #5251)

---

src/app/users/users-table.component.ts

users search by full name (fixes #5253)

---

src/app/health/health-list.component.ts
src/app/users/users-table.component.html
src/app/users/users-table.component.ts

Adds:
- Profile image
- Last examination
- Birthdate
- Emergency Contact
You may run into issues viewing the table until #5244 is merged.  The workaround I used was to manually make an admin account on my CouchDB for the member with the `health` role.

Health: Add more columns to table

---

src/app/manager-dashboard/manager-dashboard.component.ts

Remove v from myPlanet version (fixes #5196)

---

src/app/manager-dashboard/reports/reports-table.component.html
src/app/manager-dashboard/reports/reports-table.component.ts

Reports: time to table (fixes #4799)

---

src/app/community/community.component.html
src/app/community/community.scss

community: delete and add icon fixed style(fixes #5270)

---

src/app/surveys/surveys.component.html
src/app/surveys/surveys.component.ts
src/app/users/users-update/users-update.component.html

tooltip to clarify record survey (fixes #4704)

---

src/app/teams/teams-view-finances.component.html
src/app/teams/teams-view-finances.component.ts
src/app/teams/teams.module.ts

filter by date range in finance (fixes #5047)

---

src/app/health/health-event.component.html
src/app/health/health-update.component.html

Health: no information is saved removed (fixes #5295)

---

src/app/health/health-list.component.html
src/app/users/users-table.component.html
src/app/users/users-table.component.ts
src/app/users/users.component.html

UserTable: header and pagination made sticky (fixes #5286)

---

src/app/health/health-event.component.ts

HealthEvent: selfExamination flag added (fixes #5296)

---

src/app/health/health.service.ts

Had an issue where loading the `/health` page resulted in the creation of new keys for all members on my dev planet.  This meant their data was no longer accessible.
Making a first PR here so the only time a new key is created is when data as being posted not retrieved.

Health: Limit creation of new key to post new data

---

src/app/community/community.component.ts
src/app/news/news-list.component.ts
src/app/news/news.component.html
src/app/resources/resources-add.component.ts
src/app/resources/resources.service.ts
src/app/shared/dialogs/dialogs-form.component.html
src/app/shared/dialogs/dialogs-images.component.html
src/app/shared/dialogs/dialogs-images.component.ts
src/app/shared/dialogs/planet-dialogs.module.ts
src/app/shared/forms/planet-markdown-textbox.component.html
src/app/shared/forms/planet-markdown-textbox.component.ts
src/app/shared/forms/planet-markdown-textbox.scss
src/app/shared/utils.ts
src/app/teams/teams-view.component.ts

Allows for adding images (as resources) from the markdown editor

Markdown images

---

src/app/dashboard/dashboard.component.ts
src/app/home/home.component.html
src/app/home/home.component.ts

5291 health not in nation and earth

---

src/app/health/health-event-dialog.component.ts
src/app/health/health.component.html
src/app/health/health.component.ts
src/app/health/health.constants.ts
src/app/health/health.scss

Health: information for self exam and more(fixes #5324)

---

src/app/manager-dashboard/reports/myplanet-table.component.ts

myPlanet Reports: version sorted (fixes #5322)

---

src/app/exams/exams-view.component.html

ExamsView: Clicking next button (fixes #5352)

---

src/app/teams/teams.component.html

Teams: sort list by visit count (fixes #5342)

---

src/app/feedback/feedback-view.component.html
src/app/teams/teams.component.html

Feedback regarding enterprise (fixes #4697)

---

src/app/manager-dashboard/sync.directive.ts
src/app/news/news.service.ts
src/app/shared/forms/planet-markdown-textbox.component.html
src/app/shared/forms/planet-markdown-textbox.component.ts

Syncs images added to team & enterprise "chat" sections.  Doesn't sync community or ourNews at this time because the messages are not synced at this time.

News: Sync images in markdown (fixes #5310)

---

src/app/teams/teams.service.ts

teams enterprise unique titles (fixes #5358)

---

src/app/home/home.component.html

nation icon changed to flag (fixes #5363)

---

src/app/teams/teams-view.component.html

TeamsView: order changed(fixes #5380)

---

src/app/health/health.constants.ts

HealthEvent: Measeles addeed(fixes #5383)

---

src/app/courses/courses.component.html
src/app/courses/courses.component.ts
src/app/manager-dashboard/certifications/certifications-add.component.html
src/app/manager-dashboard/certifications/certifications-add.component.ts
src/app/manager-dashboard/certifications/certifications-router.module.ts
src/app/manager-dashboard/certifications/certifications.component.html
src/app/manager-dashboard/certifications/certifications.module.ts
src/app/manager-dashboard/certifications/certifications.service.ts
src/app/shared/dialogs/dialogs-add-courses.component.ts
src/app/shared/forms/planet-tag-input.component.ts
src/app/shared/table-helpers.ts

Note this is still in a hidden route `manager/certifications`
Adds the functionality to add & remove courses from a certification.

Certification: Add & remove courses

---

src/app/health/health-list.component.html
src/app/users/users-table.component.html
src/app/users/users-table.component.ts

HealthList: fix sort

---

src/app/manager-dashboard/sync.directive.ts

console log removed(fixes #5421)

---

src/app/manager-dashboard/certifications/certifications-add.component.html
src/app/manager-dashboard/certifications/certifications-add.component.ts

issue: #5402 
Thanks in advance for your review.

Certification UI (fixes #5402)

---

src/app/teams/teams.component.ts

removing community link (fixes #5327)

---

src/app/health/health.component.html

issue #5404 
@lmmrssa , @paulbert please review. Thanks in advance.

Changed myHealth DOB field to longDate (fixes ##5404)

---

src/app/health/health.component.html
src/app/health/health.scss
src/styles.scss

myHealth: ellipsis on long email (fixes #5452)

---

src/app/manager-dashboard/reports/reports-detail.component.ts
src/app/shared/csv.service.ts

CSV exporting device detail but header is taken from first record so if first record is from web then csv does not include device detail. So added header manually.

[#5301] Export header

---

src/app/manager-dashboard/certifications/certifications-add.component.ts

Certifications: clicking on save(fixes #5466)

---

src/app/teams/teams-view-finances.component.ts
src/app/validators/custom-validators.ts

TeamsViewFinance: validation message (fixes #5406)

---

src/app/configuration/configuration.component.ts

 Configuration: endless spinner (fixes #5125) 

---

src/app/community/community-link-dialog.component.html
src/app/community/community-link-dialog.component.ts

Community: Empty Enterprise/Teams link disable (fixes #5465)

---

src/app/manager-dashboard/certifications/certifications.component.html

CertificationComponent: Removed from beta (fixes #5494)

---

src/app/manager-dashboard/certifications/certifications-add.component.ts

Add certifications redirects (fixes #5478)

---

src/app/submissions/submissions.service.ts

Surveys: Fix first line of PDF answer formatting (fixes #5486)

---

src/app/submissions/submissions.service.ts

#5499 
Will likely cause conflict with #5500.  Let's prioritize that PR first.

Survey: Add page breaks for PDF (fixes #5499)

---

src/app/validators/custom-validators.ts

TeamsViewFinances: Fix dialog not opening (fixes #5508)

---

src/app/surveys/surveys.component.html
src/app/surveys/surveys.component.ts

Had a quick fix for this, but need to make sure we want to allow community admins access to survey results.

Surveys: Show surveys from parent planet for export (fixes #5497)

---

src/app/community/community.component.html
src/app/community/community.component.ts
src/app/community/community.scss
src/app/teams/teams-member.component.html
src/app/teams/teams-member.component.ts
src/app/teams/teams-view.component.html
src/app/teams/teams-view.component.ts
src/app/teams/teams-view.scss
src/app/teams/teams.module.ts

Adds views for the community council & finances.

Community: Council & Finances

---

e2e/login.e2e-spec.ts
src/app/community/community.component.html
src/app/community/community.scss
src/app/home/home-router.module.ts
src/app/home/home.component.html
src/app/home/home.component.ts
src/app/login/login-form.component.ts

Note: this will only open the community page if the Planet is a community.  We still open the dashboard if the Planet is a nation or earth.
Also note that the home icon is still used for the side menu (only shown for smaller width window/screen).  We can come up with a better icon in a later PR.

Login: Open community page after login

---

src/app/health/health-update.component.ts

myHealth: Email validator not working (fixes #5511)

---

src/app/teams/teams-view-finances.component.html
src/app/teams/teams-view-finances.component.ts

TeamsViewFinance: total after filter (fixes #5287)

---

src/app/teams/teams-member.component.ts
src/app/teams/teams-view.component.ts

TeamsMember: Fix task toggle error (fixes #5537)

---

src/app/community/community.component.ts

CommunityComponent: Community leader profile (fixes #5526)

---

src/app/login/login-form.component.ts
src/app/shared/auth-guard.service.ts

Login: Fix returnUrl always landing on community page (fixes #5529)

---

src/app/tasks/tasks.component.html
src/app/teams/teams-member.component.html
src/app/teams/teams-member.component.ts

TeamsView: Only allow task completion by member (fixes #5535)

---

src/app/teams/teams-view-finances.component.ts

Finances: Fix empty data message reset (fixes #5534)

---

src/app/dashboard/dashboard.component.ts

Dashboard: Fix broken resource, course, team links (fixes #5532)

---

src/app/dashboard/dashboard.component.ts
src/app/home/home.module.ts
src/app/login/login-form.component.ts
src/app/login/login.module.ts
src/app/shared/utils.ts

#5547 
Now when a member has a pending survey the dialog will popup even though we changed the page after login to **CommunityComponent**.
Should also work for nation if the page after login is **DashboardComponent**.

Login: Fix surveys dialog not appearing for community (fixes #5547)

---

src/app/community/community.component.ts
src/app/health/health-list.component.ts
src/app/users/users.component.ts
src/app/users/users.service.ts

Community: Self not showing in leaders list(fixes #5536)

---

src/app/exams/exams-view.component.ts

ExamsView: Error with multiple answer (fixes #5483)

---

src/app/manager-dashboard/reports/reports-table.component.html
src/app/manager-dashboard/reports/reports-table.component.ts
src/app/shared/table-helpers.ts

Reports: Initial sort by last sync(fixes #5454)

---

e2e/login.e2e-spec.ts
src/app/community/community-list.component.html
src/app/community/community-list.component.ts
src/app/community/community.component.html
src/app/community/community.component.ts
src/app/home/home-router.module.ts
src/app/home/home.component.html
src/app/home/home.component.ts
src/app/home/home.module.ts
src/app/home/planet.component.html
src/app/home/planet.component.ts
src/app/login/login-form.component.ts
src/app/teams/teams.service.ts

This will need some polishing in future issues, but Nation now logs into a list of communities with a button to click through to their exchange page.
#5555

Nation: Show community exchanges (fixes #5555)

---

src/app/notifications/notifications.component.html
src/app/notifications/notifications.component.ts

Disable mark all as read (fixes #5567)

---

src/app/submissions/submissions.service.ts

Survey: markdown for only long name(fixes #5485)

---

src/app/community/community.component.html
src/app/community/community.scss

header added to toolbar (fixes #5581)

---

src/app/community/community.component.html
src/app/community/community.component.ts
src/app/community/community.scss

Community: Services tab with description and links (fixes #5586)

---

src/app/teams/teams-view.component.ts

TeamsView: Redirect for invalid id (fixes #5621)

---

src/app/shared/table-helpers.ts
src/app/users/users-table.component.ts
src/app/users/users.component.ts
src/app/users/users.service.ts

issue: #5566 
Thanks for your review i advance.

filter by admin in members (fixes #5566)

---

src/app/community/community-list.component.ts

CommunityList: Fix undefined links (fixes #5610)

---

src/app/manager-dashboard/sync.directive.ts

#5459 
Makes it so we don't see `continuous` all over the **SyncDirective** and just set it once.

SyncDirective: Reduce duplication (fixes #5459)

---

src/app/dashboard/dashboard-tile.component.html

Dashboard: My Progress router link(fixes #5634)

---

src/app/community/community.component.ts

issue5580 fix

---

src/app/community/community.scss

Community: Calendar overflow(fixes #5620)

---

src/app/home/home.component.html

Notification: Notification link (issue #5657)

---

src/app/tasks/tasks.component.html

Task: Show full name in tooltip(fixes #5662)
