- docker/planet-dev.yml
Requires testing and review.
At the time this PR created, the `latest` docker image is not ready yet, will have it soon in couple of hours (long upload time)
> [#4] Use pre-built image for docker4development

- src/app/login/login.component.ts
Follow up of pull request #56
closes #53
> update login.compononent.ts to create admin on first time login 

- src/app/resources/resources-view.component.ts
- src/app/shared/couchdb.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
Related to #76, but doesn't fully add the different backend.  Uses environment variable for CouchDB/backend URL for all environments.
> Environment var for db

- .gitignore
Ignore the lock file created when running npm or yarn
> add *.lock to .gitignore

- .travis.yml
Requires nothing.
Result example: https://hub.docker.com/r/treehouses/planet/tags/
> A simple update in .travis.yml to have docker for production for x86

- src/app/community/community.component.ts
- src/app/courses/courses.component.ts
- src/app/meetups/meetups.component.ts
- src/app/nation/nation.component.ts
This built correctly on my machine with `ng build --prod`, and hopefully this will fix the build for the Dockers as well.  I changed it for the two components that had errors as well as two others that have a similar variable in case that would cause these errors in the future.
Not sure exactly why these errors pop up in production mode and not development.  There must be some optimization for Webpack in production that relies on the variable types.
> Change type for docker build (Fixes #189)

- package.json
This fixes the error pictured in #211 which appears to be caused by a recent update to the rxjs package, or is at least fixed by using version 5.5.2 exactly rather than allowing `npm install` to install the latest, 5.5.3.
More details here:
https://github.com/angular/angular-cli/issues/8724
> Fix app crashing 'EmptyError'

- src/app/courses/add-courses/courses-add.component.html
- src/app/shared/dialogs/dialogs-form.component.html
- src/app/shared/dialogs/dialogs-form.component.ts
- src/app/shared/form-error-messages.component.ts
- src/app/shared/planet-forms.module.ts
- src/app/validators/course-validator.service.ts
- src/app/validators/custom-validators.ts
- src/app/validators/nation-validator.service.ts
- src/styles.scss
Updates the `form-error-messages.component.ts` for use with Material and the i18n translations.
To get the `mat-error` component to display correctly it had to be a direct descendant of `mat-form-field`, so I had to make adjustments to the `courses-add.component` and `dialogs-form.component`.
> Update form error messages for Material and translations

- src/app/courses/add-courses/courses-add.component.html
- src/styles.scss
The course view ended up a bit off due to a mixing up PRs on my part.  This returns the view to its previous horizontal alignment of input boxes.
There are two other changes included:
* The `mat-grid-list` was not being used correctly, so I removed them in favor of `div` elements.  Please take a close look at the examples [here](https://material.angular.io/components/grid-list/overview) and note that to work correctly these require `mat-grid-tile` children.
* I added a class `margin-lr` which can be used where the material components do not leave horizontal space between elements, like the day of the week checkboxes in this component.  I think this will be useful in other situations as well.
> Fix the course add view

- README.md
Small update to the readme to bring the guidelines further up and highlight two additional points:
* Explicitly ask developers to clone rather than fork the repository.  Since the virtual interns fork for their work on the wiki, I'd like to highlight the difference here.
* Add a mention of the hooks.  This is included in the Style Guide as well, but I think it's good to mention it here, too.
> Update guidelines and move higher in readme

- src/app/users/users-profile/users-profile.component.ts
A component property was missing causing `ng build` to fail.
> Fix master build error

- package.json
It should be consistent 😄 
BTW, remindme again, is `AGPL-3.0` valid license in `package.json` format ?
> Sync license package.json like in repo

- docker/db-init/Dockerfile
- docker/db-init/rpi-Dockerfile
Links to #324 
@Rupesh87 was changing the shebang of `couchdb-setup.sh` and it breaks our `db-init` docker since it doesn't has bash (it is an alpine linux container).
Is this shebang not sufficient in our vagrant? @dogi @paulbert
> ~Use sh in our couchdb setup to make db-init docker in alpine can use it~ Add bash instead

- src/app/community/community.component.ts
- src/app/courses/add-courses/courses-add.component.ts
- src/app/feedback/feedback.directive.ts
- src/app/nation/nation.component.ts
- src/app/resources/resources-add.component.ts
- src/app/shared/dialogs/dialogs-form.service.ts
- src/app/shared/planet-rating.component.ts
- src/app/users/users-update/users-update.component.ts
- src/app/validators/validator.service.ts
Besides my pull request, I am not sure the imports listed below should be cleaned up.
1) feedback.directive.ts
BrowserModule
formsModule
2) nation.component.ts
DialogsFormComponent
3) shared/planet-rating.component.ts
forwardRef
ElementRef
NG_VALUE_ACCESSOR
FormControl
> [#404] Clean up imports

- src/app/resources/view-resources/resources-view.component.html
The full screen view for PDF is working only in Firefox, other browsers are not supporting it.
> [#392] Added fullscreen view for PDF(Connects #392)

- src/app/courses/courses.component.html
- src/app/resources/resources.component.html
- src/app/users/users.component.html
We added a few unnecessary handlers to the select checkboxes in our tables.  In the Material docs these handlers are used in the examples because they also have a click in any part of the row toggle select.
If we don't have that or another overlapping click handler, we don't need these lines.
> Remove unnecessary stopPropagation

- src/app/home/home.component.html
- src/app/home/home.component.ts
- src/app/manager-dashboard/manager-dashboard.component.ts
while setting up configuration its creating user without role, and it is adding isUserAdmin= true, therefore while checking roles its giving empty array[], thats why i have checked isUserAdmin for this issue. while creating user the value for isUserAdmin is false. so the manager setting button will be visible only if isUserAdmin is true
> [#457] hide usersetting from users connects (#457)

- docker/planet.yml
- docker/planet/docker-entrypoint.sh
- docker/rpi-planet.yml
- src/environments/environment.prod.ts
Allows us to create production versions of planet with different center/earth address quickly.
> Configure center address for docker

- .travis/travis_utils.sh
See error in https://travis-ci.org/ole-vi/planet/jobs/364898667#L544
Found an alternative way to call `docker login` from https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry
> Fix Travis docker login prompt

- src/app/users/users-update/users-update.component.html
- src/styles.scss
This branch is just to fix the profile image becoming large after uploading a new profile image. I implemented it on my 564-ProfileImageCrop branch to test it before moving it to this new branch. There seems to be some kind of issue on this branch, I was unable to upload a new profile image using the old method. Also we should make this (and probably other parts of the app) more responsive, but that might warrant its own issue.
> styling profile image update fixes #634

- src/app/shared/couchdb.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
The main problem with using relative protocol (`//`) rather than explicitly setting protocol is that our development environments use http.
> Center protocol environment variable (fixes #746)

- couchdb-setup.sh
- design/security-update/security-update.json
- src/app/users/users.component.html
- src/app/users/users.component.ts
* Updated _users _all_docs to _find as _all_docs is only accessible by system admin
* Added manager role to db as application admin not system admin. So it can be easily promoted/demoted
* Changed admin role in design docs to manager as admin label is displayed for system admin
* Added manager as admin of all databases in design doc
> [#286] Enable multiple admin (connects #286)

- docker/db-init/crosscompile_db-init.sh
- docker/db-init/rpi-Dockerfile
- docker/planet/crosscompile_planet.sh
- docker/planet/rpi-Dockerfile
This is a quick fix for the current travis build fail issue. It was caused due to the removal of the pre-installed GNU privacy guard package.
I wouldn't consider this as a permanent fix, but should be used for the time being.
I will work on making a builder image with everything pre-installed, so that these problems will not occur in future.
> Travis "build fail" fix

- .travis.yml
- .travis/deploy_rpi.sh
- .travis/travis_utils.sh
* Pushes all commits to `treehouses/planet-tags`
* Makes `treehouses/planet` multiarch compatible **(only when merged with master)**
* For `amd64`, `treehouses/planet:latest` points to `treehouses/planet-tags:latest`
* For `arm`, `treehouses/planet:latest` points to `treehouses/planet-tags:rpi-latest`
* For `amd64`, `treehouses/planet:0.1.7` points to `treehouses/planet-tags:0.1.7`
* For `arm`, `treehouses/planet:0.1.7` points to `treehouses/planet-tags:rpi-0.1.7`
There is similar structure for `db-init`
> Multiarch support for planet

- src/app/_variables.scss
- src/app/dashboard/dashboard-tile.component.html
- src/app/dashboard/dashboard-tile.component.ts
- src/app/dashboard/dashboard-tile.scss
- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
- src/app/dashboard/dashboard.scss
I can revert to the white/grey alternating for the lists, but since some of the designs have used small lines to divide instead tried that to see how it looks.
The left menu is just a placeholder for now, and on tablets it doesn't fit (it is also scrollable, however):
> [#563] Update dashboard view (connects #563)

- src/app/shared/table-helpers.ts
- src/app/users/users.component.ts
`doc` key was introduced to prevent from saving unnecessary data. But our filter only works one level. So introduced multi-level filter where `.` will act as dot separator of keys
> [#770] Add multilevel filter specific fields (connects #770)

- src/app/meetups/meetups.service.ts
- src/app/meetups/view-meetups/meetups-view.component.html
- src/app/meetups/view-meetups/meetups-view.component.ts
As a reminder, we should not use services directly in a template.  Services should be written so they are independent of the components that use them.  This allows them to be more easily used across many components.
> Refactor MeetupsService - not used in template

- src/app/users/users.component.ts
Error was that condition was reversed before.
@paulbert about using ngIf its used on dialog so it will require more detail passed. Also if we add condition on delete button it will be additional dialog which will not look good.
> [#1037] Condition reversed on message (connects #1037)

- src/app/shared/dialogs/dialogs-form.component.html
- src/styles.scss
> [#1229] Buttons in dialog moved to the right, and correct order of them (fixes #1229)

- src/app/resources/resources-add.component.html
- src/app/resources/resources-add.component.ts
Added `isSubmitted` variable and bound the `disabled` attribute of the `Submit` button to it. Now it should be impossible to add a resource multiple times.
As suggested by @lmmrssa in #1200
> as some request will take a while to return response we should have some indicator showing action being carried on.
So next step is to add some kind of loading sign. What type of loading signal do we use in other parts of the app?
> Disable submit button upon submission (fixes #1200)

- src/app/login/login-form.component.ts
Since center tries to log into the "parent" and fails, it loses the session immediately pushing you back to the login screen on every route change.
> Fix center.media.mit.edu admin

- src/app/courses/step-view-courses/courses-step-view.component.html
- src/app/manager-dashboard/manager-dashboard.component.ts
- src/app/shared/dialogs/dialogs-form.component.html
- src/app/users/users.component.html
- src/i18n/messages.ar.xlf
- src/i18n/messages.xlf
Fixing situations where `i18n` tags were used for elements with only interpolation (which should not be translated & causes errors).
> Fix translations

- src/app/dashboard/dashboard.component.ts
Added small function to check if shelf is empty, and a condition that exits from `ngOnInit` if the shelf is empty. This is meant to fix the problem where new users would make a request that they don't have permission for and thus get an error message.
I decided to exit the ngOnInit instead of wrapping its contents in an if statement because it's generally considered [better style](https://softwareengineering.stackexchange.com/questions/18454/should-i-return-from-a-function-early-or-use-an-if-statement). However, I was unsure if the call `this.couch.service.post...` does something of value even for an empty shelf, so if that's the case the solution will have to be changed.
> [#1343] Only get data for non-empty shelf (connects #1343)

- src/ngsw-config.json
Large resource upload is working in dev environment, but not production.  Seeing if removing the resources from the service worker manifest will help.
> Fix large resource upload

- src/app/courses/progress-courses/courses-progress-leader.component.ts
#1362 is already closed, but there is still an issue where the blue boxes on course progress could show up as NaN.  This change fixes that.
> Fix other NaN issue

- src/app/community/community.component.ts
- src/app/shared/couchdb.service.ts
- src/app/users/users.component.ts
Uses the bookmark returned from a _find query to recursively find all documents that match.  Implemented for UsersComponent and CommunityComponent as examples to test.
Will need to be implemented across more of the app if working (which we should do in other PRs).
> Return all documents from _find query (connects #1241)

- src/app/configuration/configuration.component.ts
- src/app/manager-dashboard/manager-dashboard.component.html
- src/app/manager-dashboard/manager-dashboard.component.ts
- src/app/users/users.component.ts
On community configuration creates a `satellite` user with the learner role and a 4 digit pin for its password that is also stored on the database configuration.  That pin is displayed on the manager dashboard.
In addition as part of cleanup when deleting the community the satellite user & the configuration pin value are deleted.
> Default user for android

- src/app/shared/form-error-messages.component.ts
- src/app/users/users-update/users-update.component.ts
- src/app/validators/custom-validators.ts
If we use datepicker, when we input alphabet (q, w..) or some special characters( @, #..), input will pass null or undefined as birthdate value. 
[Date picker input and change events](https://stackblitz.com/angular/aaledypnmljg?file=app%2Fdatepicker-events-example.ts) can show this situation.
So I revise form-error-message, error message can be suitable to input nothing or to input something not date.
> [#1419] Error for invalid date (connects#1419)

- src/app/dashboard/dashboard-tile.component.ts
- src/app/dashboard/dashboard.component.ts
The error happens if we remove the last one item from the dashboard, it can’t  update the list. Because the last one item may appear in the myLibrary, myCourses, myMeetups or myTeams, so this error may happen in in the myLibrary, myCourses, myMeetups and myTeams.
> [#1550] Removing meetup from dashboard (connects #1550)

- couchdb-setup.sh
- design/create-design-docs.js
Right now only creates `validate_doc_update` function, but currently that is the only one we are adding so it should be OK.
> Add script to convert js to json for design docs (fixes #79)

- docker/planet/Dockerfile
The x86 docker didn't have bash which is required for the use of an array in the script.
> Fix upgrade script

- couchdb-setup.sh
- src/app/configuration/configuration-guard.service.ts
- src/app/manager-dashboard/manager-dashboard.component.ts
- src/app/shared/couchdb.service.ts
- src/app/shared/user.service.ts
Uses the new `/version` endpoint rather than the database.
> Show version of parent & planet (connects #1671)

- package.json
- src/app/courses/add-courses/courses-add.component.html
- src/app/courses/courses.component.html
- src/app/courses/view-courses/courses-view.component.html
- src/app/shared/forms/planet-forms.module.ts
If this editor looks OK let's approve and merge to move on to refining the UX.  
Follow up issue:
We will need to make a custom form element for the editor to use form errors & placeholders.  We should also do sizing of the editor as part of that future issue.
> Add simple markdown editor for course description (fixes #808)

- src/app/courses/add-courses/courses-add.component.html
- src/app/courses/add-courses/courses-add.component.ts
- src/app/courses/add-courses/courses-step.component.html
- src/app/courses/add-courses/courses-step.component.ts
- src/app/exams/exams-add.component.ts
- src/app/shared/forms/planet-forms.module.ts
- src/app/shared/forms/planet-step-list.component.html
- src/app/shared/forms/planet-step-list.component.ts
Using the mat-expansion-panel for the course steps makes it difficult if you needed to scroll to see the add resource/exam buttons.  For courses with ~50 steps it would be very cumbersome trying to scroll to find the one step you have open to edit.
Added a new component which we can reuse for similar lists which opens a form when an item is clicked on to edit that item's attributes.
> Change course add steps to custom panel like list

- docker/planet/default.conf
Added `client_max_body_size` to `location /db/`.  Not sure if this will fix the problem, but it was quick to add to get a build started.
> Resource attachment fix (connects #1858)

- docker/planet/scripts/docker-entrypoint.sh
- src/app/login/login.component.ts
- src/app/shared/sync.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.test.ts
- src/environments/environment.ts
Tested it on a nation with https.  In the off chance someone sets up CouchDB with a different internal port than 5984 then there is an environment variable to customize this with.
> 1896 sync localhost

- couchdb-setup.sh
In testing, I found that increasing the `replicator/connection_timeout` configuration setting helped with the replication of large files.
> Improve replication performance

- docker/planet/scripts/build_planet.sh
Fixes #1833
Not sure if its working or not. But please check these builds
* [build with tag](https://travis-ci.org/open-learning-exchange/planet/builds/418297179?utm_source=github_status&utm_medium=notification) --> takes 19 minutes
* [build without tag](https://travis-ci.org/open-learning-exchange/planet/builds/418295245) --> takes 6 minutes (no changes, expected)
Comparison:
* [previous build with tag](https://travis-ci.org/open-learning-exchange/planet/builds/416729956) --> takes 20 minutes
* [previous build without tag](https://travis-ci.org/open-learning-exchange/planet/builds/418191589) --> takes 6 minutes (no changes, expected)
---
From my chat with @paulbert 
>the old setup run all translation build in 20+ minutes
>and new parallel takes 19 minutes
>I guess with new language …
> Run build command in parallel (#1833)

- Vagrantfile
- src/app/configuration/configuration.service.ts
The error was because the `_users` security object was not set when db-init ran which led to us trying to access properties of undefined for auto accept.
We should also update treehouses to make sure `db-init` runs the first time with:
```
environment:
- INSTALL=1
```
> Initial configuration error (fixes #2040)

- src/app/shared/couchdb.service.ts
Quick fix to solve the issue of deleted items showing up on the dashboard.
We may also need to clean up the documents on the shelf database after an item is deleted.  Not sure what the best way to do that is because it may make deleting documents from other databases very slow.
> Fix deleted items on dashboard

- src/app/resources/resources.service.ts
Using incorrect lastSeq (only storing one on the service for both parent & local db) caused the _design docs to show up as blank lines in the resources table.
Also, just in case there is an actual change to a design doc in the middle of someone's session, filtering this out so the _design doc is not inadvertently deleted.
> Fix _changes lastSeq & _design doc issues

- src/app/courses/add-courses/courses-add.component.html
- src/app/courses/add-courses/courses-step.component.html
- src/app/exams/exams-question.component.html
- src/app/meetups/add-meetups/meetups-add.component.html
- src/app/resources/resources-add.component.html
- src/app/shared/forms/planet-forms.module.ts
- src/app/shared/forms/planet-markdown-textbox.component.html
- src/app/shared/forms/planet-markdown-textbox.component.ts
- src/app/shared/forms/planet-markdown-textbox.scss
Sets up the markdown editor as a Material form component.  This improves the visuals for errors and as a side effect fixes the issue where the text doesn't initialize until you click on the editor
#1845 #2045
> Markdown editor component (fixes #1845) (fixes #2045)

- src/app/_variables.scss
- src/planet-mat-theme.scss
- src/styles.scss
Fixes #2325
Added style in styles.scss file which overwrites Angular Material style for toggle button color.
> change toggle button color (fixes #2325)

- src/app/manager-dashboard/reports/reports-detail.component.ts
- src/app/manager-dashboard/reports/reports.service.ts
#2338 only half fixed the issue with ReportsDetailComponent.  Now all of the get requests run after the route parameters set variables, most importantly the `planetCode` to fetch reports for.
> Fix ReportsDetailComponent initialization

- src/app/shared/state.service.ts
In 0.5.0 an error was introduced which breaks the initial configuration setup.  This fixes that error allowing the initial setup of a planet again.
> Fix planet setup configuration error

- src/app/shared/forms/planet-markdown-textbox.scss
To test go to any page with an editor (resource add, course add) and add enough lines into the description to go beyond the height of the editor.  You should see a scrollbar appear at that point:
> Fix scrolling for markdown editors

- src/app/courses/view-courses/courses-view.component.html
- src/app/courses/view-courses/courses-view.component.ts
Fixes #2304 
I adjusted courses-view.component.html file to hide a button for resources which don't have attachments or to exclude those resources from the list of resources.
When a step has only 1 resource with no attachments in it:
When a step has 2 resources and one doesn't have attachments:
Only resource with an attachment will appear in the list.
> No attachment hide resource button (fixes #2304)

- .travis.yml
- couchdb-setup.sh
- src/app/manager-dashboard/manager-sync.component.ts
- src/app/manager-dashboard/reports/reports-detail.component.ts
- src/app/manager-dashboard/reports/reports.service.ts
Adds a `child_statistics` database to store the count of resources & courses from child planets (communities) so when they are offline the data will still show in reports.
> Fix child total resources & courses

- src/app/home/home.component.html
- src/app/home/home.scss
- src/app/shared/forms/planet-markdown-textbox.scss
> Full screen toggle (fixes #2420)

- src/app/resources/resources.component.html
- src/app/shared/forms/planet-tag-input.component.ts
- src/app/shared/forms/tags.service.ts
To test: go to parent resources and click filter labels.  Should see labels from the parent planet.
Found the issue in testing #2523
> Show parent labels when viewing parent (connects #2523)

- src/app/courses/courses.service.ts
To test: load resources or parent resources from manager dashboard before loading courses.  There should not be new errors in the console.
> Fix console error on resources page (fixes #2278)

- src/app/courses/courses.service.ts
- src/app/courses/progress-courses/courses-progress-bar.component.html
- src/app/courses/progress-courses/courses-progress-bar.component.ts
- src/app/courses/step-view-courses/courses-step-view.component.ts
Adds one document per user per step to the `courses_progress` database so we can track when the user starts & completes each step.
To test: take course and check to make sure one and only one document is created on database for each step.  Confirm course progress bar (on CoursesComponent & CoursesViewComponent) look as they did before for this PR (grey for step not started, blue for in progress, and green for completed).
Note that any progress from previous versions will look different (all but one step will be grey).
#2554
> Courses progress database change (fixes #2554)

- .travis.yml
- couchdb-setup.sh
- src/app/resources/resources.component.html
- src/app/resources/resources.component.ts
- src/app/resources/resources.service.ts
- src/app/shared/forms/planet-tag-input-dialog.component.html
- src/app/shared/forms/planet-tag-input.component.ts
- src/app/shared/forms/tags.service.ts
Allows adding new labels from the dialog in the resource page.
Please test to make sure you can create a label and assign it to resources.
Next TODOs:
- Adding a label which is a "sublabel" or attached to other labels doesn't do anything at this moment.  Need to show this in the filter view.
- Tags on the resource list show the id for a split second before changing to the text.  Need to find ways to improve this.
- A manager list view of labels where they can edit them after they have been created.
> Add new label (fixes #2501)

- src/app/courses/progress-courses/courses-progress-leader.component.ts
fixes #2611
I removed initialization of `selectedStep` variable inside ngOnInit(). Thus, "Show full course" button is not visible during loading. 
Not sure if it is a good practice to remove initialization from ngOnInit(). But it seems that the variable is initialized successfully inside functions of the component.
> [#2611] CourseProgress: Prevent showing of the button during loading time

- src/app/shared/couchdb.service.ts
- src/app/shared/user.service.ts
Fixes loginTime being overwritten on logout and makes sure to create a new document on the `login_activites` database every login.
To test: Clear your `login_activities` database (except for the document with id starting with `_design`).  Then in the app login, logout, and login again.  You should now have 2 new documents one with `logoutTime` > `loginTime` and another with a positive `loginTime` and `logoutTime` set to 0.
#2814
> Fix login_activities data (fixes #2814)

- src/app/feedback/feedback-view.component.ts
New messages can be added to feedback conversations without error now.
#2790
> Fix adding new message to feedback (fixes #2790)

- src/app/shared/dialogs/dialogs-form.component.html
- src/app/shared/forms/planet-tag-input-dialog.component.html
- src/app/shared/forms/planet-tag-input-dialog.component.ts
- src/app/shared/forms/tags.service.ts
Initial part of #2869.  Currently editing a label is restricted to admins, but I think we can make a change later to allow the creator of the label to edit it.
I think a management page to delete labels in the manager dashboard could be another next step.  Since that is not a trivial task for the DB (each resource with that label will need to be updated), deletion should be restricted to admins only.
> Edit label in dialog (connects #2869)

- src/app/shared/forms/planet-tag-input-dialog.component.ts
To test create/modify a resource to have many labels.  Try to edit the resource again and click "Add Labels", but don't change any.  The selected labels in the "Hover" list should still match what was previously selected.
To see the difference, do the same with the master branch.  You should see the error where only one label is selected after clicking "Add Labels".
#2813
> Fix add label changing selected labels (fixes #2813)

- src/app/exams/exams-view.component.html
- src/app/exams/exams-view.component.ts
- src/app/submissions/submissions.service.ts
fixes #2570 
The learner can take the exam multiple times, and he is also able to move between questions without answering them, the issue is, if he reaches to the last question and submits the answer, the exam will be closed.
The solution here did the trick by taking track all answers, and not to close the exam until all answers were submitted.
It will be better to persist answers in the textbox of each question so learners can review their answers.
> Prevent exam to close with unanswered questions

- src/app/shared/dialogs/change-password.directive.ts
- src/app/shared/dialogs/dialogs-form.component.html
- src/app/shared/dialogs/dialogs-form.component.ts
- src/app/shared/dialogs/dialogs-form.service.ts
Changes DialogsForm so the dialog does not close automatically when the form is submitted.
This allows us to receive a response from the server before closing the form in case of errors.
Implemented for changing passwords so far, will need to implement for other forms as well.  Note the change password error requires #3042 so I will put this on hold.
#1527
> Refactor DialogsForm (fixes #1527)

- src/app/shared/forms/tags.service.ts
Gives `attachedTo` a default value of an empty array to prevent error.  I think it was caused by an older version of a document in the `tags` database, but it can't hurt to include this in case somehow documents get changed in a bad way.
> Fix fillSubTags error (fixes #3085)

- src/app/shared/dialogs/change-password.directive.ts
A normal user gets an error message on changing the password since an array is expected for the map(). 
Couldn't replicate the same error message as in the issue #3091
> Changing pswd on normal user message fixes (fixes #3091)

- src/app/shared/couchdb.service.ts
To test add some documents to the shelf and then modify the shelf document of one of your users to include a string which does not correspond to a document id in the database (`"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"` in the image below).  On master there will be no items on the dashboard, but on this branch they will appear.
> Fix missing doc causing no items in dashboard (fixes #3096)

- src/app/users/users-achievements/users-achievements.component.html
Fixes #3137 
Changes the Edit Achievements Button to Add Achievements when no achievements have been added.
> (Fixes #3137) Changes Button to Edit Achievement Button

- src/app/resources/view-resources/resources-menu.component.ts
- src/app/users/users-achievements/users-achievements.component.html
- src/app/users/users-achievements/users-achievements.component.ts
- src/app/users/users-achievements/users-achievements.scss
#3232 editing the achievements view to include the new fields.
Click on an achievement to show description and a button for each resource.  Clicking again closes the achievement.  Only on achievement should be open at a time.
> Achievements: Rearrange to include title & date (fixes #3232)

- src/app/users/users-achievements/users-achievements.component.html
- src/app/users/users-achievements/users-achievements.component.ts
- src/app/users/users-achievements/users-achievements.scss
> Achievements: add icons and isClickable check (fixes #3251)

- src/app/submissions/submissions.component.html
- src/app/submissions/submissions.service.ts
> (Fixes #2743) Submissions: Clarify Grading Status

- src/app/users/users-achievements/users-achievements-update.component.ts
formGroup.controls.date.setValue() accepts an object that matches the structure of the group.
[https://angular.io/api/forms/FormGroup#setValue](https://angular.io/api/forms/FormGroup#setValue)
> Fixing date.ValueToJson() bug in achievement-update (Fixes #3342)

- src/app/resources/resources.component.html
- src/app/resources/resources.component.ts
- src/app/resources/resources.module.ts
- src/app/resources/resources.scss
- src/app/resources/search-resources/resources-search.component.ts
- src/app/resources/search-resources/resources-search.scss
- src/app/shared/table-helpers.ts
A set of filters (click "Show Filters" on resources page to display them) for resource Subject, Level, Medium, and Language.  Populates the list based on currently selected resources.
One known issue: if you select some of these filters and then select a collection it is possible to end up with 0 resources.  This is more an issue with the collection list & I more suitable for a future PR on that feature.
It is possible to end up with no resources left with a selection filter & text search as well, but I don't think that's avoidable.
> Additional resource filters

- src/app/surveys/surveys.component.html
[Fixes #3473] Survey: hide delete button
> [Fixes #3473] Survey: hide delete button 

- src/app/shared/beta.directive.ts
User defined beta functionality (set in configuration) won't work until users explicitly set their own beta functionality in their profile.  This resulted in the dashboard, which has one version for beta and one for non-beta, not showing any content for that setting.
This fixes that issue by making sure the `isBetaEnabled()` function returns a boolean value so its type matches the type of `planetBeta`
> Fix user defined beta toggle (fixes #3532)

- src/app/resources/search-resources/resources-search.component.ts
[Fixes #3521] ResourcesSearch: Checkbox before
> [Fixes #3521] ResourcesSearch: Checkbox before

- src/app/users/users-profile/users-profile.component.html
[Fixes #3538] Member Profile: in "Change password" action button "p" should be uppercase
> [Fixes #3538] Member Profile: in "Change password" action button "p" should be uppercase

- src/app/courses/courses.service.ts
In the view for learner progress (navigated to via the **My Progress** link on dashboard) there were only a set of courses shown.  This is because the request to the `courses_progress` database was still using the `_find` endpoint, which defaults to a limit of 25.
Replaces that request with our `findAll` method which returns all items that match the query.
> Fix learner progress view (fixes #3575)

- src/app/exams/exams-view.component.html
I've fixed long title in Exam and Survey view:
However, I'm not sure if I should fix long title in MySurveys and Surveys views (list of surveys). Maybe better to keep full titles here.
vs
> Survey/Exam: fix long title (fixes #3512)

- src/app/courses/progress-courses/courses-progress-chart.scss
- src/app/courses/progress-courses/courses-progress-leader.component.html
- src/app/courses/progress-courses/courses-progress-learner.component.html
When there are fewer rows than the height of the available space, the final label rows now move up to align better with the rest of the CoursesProgress table.
> CoursesProgress: Fix spacing for fewer rows (fixes #3586)

- src/app/courses/courses.component.html
- src/app/meetups/meetups.component.html
- src/app/resources/resources.component.html
- src/styles.scss
In addition to Courses & Resources as included in #3662, I also updated Meetups since it uses a similar layout for the title & description.
> Courses, Resources & Meetups: Selection aligned with title (fixes #3662)

- src/app/exams/exams-add.component.html
- src/app/exams/exams-add.component.ts
- src/app/exams/exams-question.component.html
- src/app/exams/exams-question.component.ts
- src/app/exams/exams-question.scss
- src/app/exams/exams.service.ts
Two changes:
- "Add Question" opens a menu to select the type of question to add
- Type is moved to the same line as title so this can be changed later, but to move it out of the way of the form fields that have not been filled.
> ExamsAdd: Add question opens menu and move type

- src/app/courses/add-courses/courses-add.component.html
- src/app/courses/add-courses/courses-add.component.ts
- src/app/shared/database/pouch.service.ts
With this change courses will now save locally with PouchDB as a "draft".  Three actions will remove the draft:
1. Clicking "Submit" will save the course to CouchDB and delete PouchDB draft
2. Clicking "Cancel" will delete PouchDB draft
3. Adding an exam or survey will save the course to CouchDB and delete PouchDB draft
Note I also removed the `id` field for course steps because it is no longer used (we no longer use a `trackBy` function in CoursesAdd)
> CoursesAdd: Save as draft locally

- src/app/courses/add-courses/courses-add.component.ts
It's still hard to pin down the exact issue, but I think the _id was being saved on CoursesService even after it should have been reset.  Note that courses were not overwritten every time, but only occasionally.
To test create a lot of courses one after another each with one test.  If any of them are overwritten please try to document exactly what happened and I'll attempt another fix.
> Fix course overwrite (fixes #3600)

- src/app/courses/courses.component.html
Changed "Get course" to "Get Course" in Getting List of Courses page.
> Capitalize course in Get Course (fixes #3647)

- src/app/exams/exams-add.component.ts
(fixes #3746) add a dash to separate course name and tryNumber after submit the course survey.
> Add dash between courseName and tryNumber(fixes #3746)

- src/app/shared/state.service.ts
I noticed that sometimes data in the app ended up out of sync with the database.  I think it was because the first time using StateService the change/lastSeq id is not saved, so next time there is a chance that it skips over changes to the database when updating.
Changed so when `getAll` runs, so does `getChanges` to add the lastSeq to the service
> Fix StateService skipping changes

- src/app/shared/forms/planet-tag-input-dialog.component.ts
- src/app/shared/forms/planet-tag-input.component.ts
I made an error in the last commit of #3772 where none of the names of the collections were showing up in the list.
This also fixes the "Search Collections" list not updating correctly after editing a collection name by selecting resources/courses & clicking "Change Collections".
> Fix collections list & updates

- src/app/courses/progress-courses/courses-progress-chart.component.html
- src/app/courses/progress-courses/courses-progress-chart.component.ts
- src/app/courses/progress-courses/courses-progress-chart.scss
- src/app/courses/progress-courses/courses-progress-leader.component.html
- src/app/courses/progress-courses/courses-progress-leader.component.ts
I fixed Course Progress's chart so the label says 'Questions' instead of 'Steps' when the use navigates to the chart for specific questions.
> Fix Course Progress's course chart label (fixes #3590)

- src/app/manager-dashboard/manager.service.ts
Before this change it would only get 25 of the docs in the `send_items` database.
> Fix getting list for "Fetch Items"

- src/app/courses/courses.component.ts
- src/app/manager-dashboard/manager-fetch.component.ts
- src/app/manager-dashboard/manager-sync.component.ts
- src/app/shared/sync.service.ts
Replicates the tags along with the resources or courses object.  When replicating courses, does not replicate the tags of the resources attached to the courses.  I specifically worked on the "Get Resources" & "Get Courses" (child pull), but this might work in other replication scenarios.
Requires #3837 & #3841 to see this on courses.
> Replicate tags for "Get Resources" & "Get Courses"

- src/app/shared/forms/planet-tag-input.component.ts
Was unable to replicate in dev environment, but the errors in production led me to believe it's related to `value` somehow being set to `undefined` in the PlanetTagsInputComponent
Since it already uses a getter/setter, made a change to the setter to fallback to an empty array if something tries to set it to undefined.
> Fix CoursesAdd collections error (fixes #3830)

- Vagrantfile
- docker/planet/nginx/credentials.sh
- src/app/configuration/configuration.service.ts
- src/app/manager-dashboard/manager.service.ts
- src/app/shared/dialogs/change-password.directive.ts
- src/app/upgrade/upgrade.component.ts
In my testing I found that the production vagrant was resetting the `_users` design doc during the initial setup and every subsequent halt/up cycle after configuration if the `credentials.yml` file was not set.
Since this was only set before an upgrade, I modified this to also run the script to create/modify that file during the initial configuration and on changing passwords.  In case we add the ability to set and remove admins, I limited the script to change the yml file only if the user name matches what is in the file.  We'll need to make sure that the first admin cannot be removed.
> Fix user creation on production vagrant (fixes #3869)

- src/app/courses/courses.component.html
- src/app/courses/courses.component.ts
[Fixes #3879] Course: selected collection tag can be made similar to resource
> [Fixes #3879] Course: selected collection tag can be made similar to resource 

- src/app/shared/forms/planet-markdown-textbox.scss
[Fixes#3932] Markdown Textbox: Full screen not expanding fully
> [Fixes#3932] Markdown Textbox: Full screen not expanding fully

- src/app/shared/forms/planet-markdown-textbox.scss
[Fixes#3956] Markdown Textbox: adjust bottom margin
> [Fixes#3956] Markdown Textbox: adjust bottom margin

- src/app/courses/courses.component.html
- src/app/courses/courses.service.ts
- src/app/resources/resources.component.html
- src/app/resources/resources.service.ts
- src/app/shared/dialogs/dialogs-form.component.html
- src/app/shared/forms/planet-forms.module.ts
- src/app/shared/forms/planet-tag-input-dialog.component.html
- src/app/shared/forms/planet-tag-input-dialog.component.ts
- src/app/shared/forms/planet-tag-input.component.ts
- src/app/shared/forms/tags.service.ts
Updates layout & subcollections
Subcollections are now unique to the attached collection.  The upside is that this is less confusing: clicking on a subcollection doesn't mark the checkbox for a bunch of items in the list.  The downside is that this will require more collections on each planet and will likely end up with some duplication.
TODOs:
- Fix subcollection showing id instead of name
- Better UI for subcollection in list of resources/courses
> Collections: Update layout

- src/app/meetups/add-meetups/meetups-add.component.html
- src/styles.scss
I added two new classes. One giving space for top and bottom, another adding space for top bottom, left and right. I did this to also space out the `recurring frequency` component with the `start time - end time` component.
**Please comment any edits or suggestions!**
> Adjusted margins for meetup (issue#3992)

- src/app/courses/add-courses/courses-add.component.html
- src/app/courses/add-courses/courses-add.scss
- src/app/meetups/add-meetups/meetups-add.component.html
Fixes Issue #3985.
Adds 2px button margins to "add course", "update course", and "add meetups".
> Adds button margins to "add course", "update course", and "add meetups" (Fixes #3985)

- angular.json
Allows for viewing some of the different language files in the development server with one of the following commands:
```
ng serve --configuration=somali
ng serve --configuration=french
ng serve --configuration=nepali
ng serve --configuration=arabic
```
Made the change to review another PR anyway, so figure I can share so others can use this.
> Development serve for different languages (fixes #2363)

- src/app/teams/teams.service.ts
Fixes Issue #4016
The autofocus is on "Name" and not "Description", however. I thought this would be more apt because this "Update Team" modal is used for both editing purposes and adding descriptions, so autofocusing on the Description might not be the most frequent use. In case you do want to change the description, it is just a tab away.
> Changes "Update Team" modal word "Detail" To "Description" and adds autofocus (Issue #4016)

- src/app/feedback/feedback-view.component.ts
Fixes Issue #4061 
It is now impossible to click the Re-Open button twice on a Feedback while it is loading due to the spinner being active.
> Spinner added on re-open (Fixes #4061)

- src/app/manager-dashboard/manager-sync.component.ts
- src/app/manager-dashboard/sync.directive.ts
The **SyncDirective** won't have a list of replicators to access, so we fix this by getting the replicators from CouchDB at the start of the sync process.
> Fix sync error (fixes #4082)

- src/app/shared/forms/planet-tag-input-dialog.component.ts
Issue #4117 
Editing subcollection status no longer has an infinite spinner.
> [#4117] Stops spinner on changing collection

- src/app/shared/forms/planet-tag-input-dialog.component.html
- src/app/shared/forms/planet-tag-input-dialog.component.ts
- src/app/shared/forms/tags.service.ts
#3960
So far, clicking the `delete` button for each collection removes that collection but does not update the list of collections in the collections dialog box.
> Delete Collections (WIP)

- protractor.conf.js
Try to fix the of late common Travis failure in the automated test stage. Increases the test timeout from 11s to 110s
> Increase protractor timeout

- src/app/courses/courses.component.html
- src/app/resources/resources.component.html
[Fixes #4110] Library/Courses: manager action should be enabled only on select of entity
> [Fixes #4110] Library/Courses: manager action should be enabled only on select of entity

- src/app/dashboard/dashboard-tile.component.html
- src/app/dashboard/dashboard.component.ts
I changed the badges to overlap with the text since for submissions the badge overflowed beyond the box otherwise.
Ultimately I think we should have icons and the badges with numbers can be on the icon, but for now this adds the badge back into view, at least.
> Fix badge not showing for submissions (fixes #4175)

- src/app/manager-dashboard/reports/reports.service.ts
Fixes the request to ensure the selector contains `{ androidId: { '$exists': false } }` when **Planet** is selected in the reports
> Fix request for planet report filter

- src/app/teams/teams-view.component.ts
- src/app/teams/teams.service.ts
Adjusts how the team leader is set to prepare for allowing leadership to be passed to different member than team creator
> Teams: Set leader in membership doc (fixes #4214)

- src/app/courses/add-courses/courses-step.component.ts
- src/app/courses/courses.module.ts
- src/app/manager-dashboard/sync.directive.ts
- src/app/resources/resources-add.component.html
- src/app/resources/resources-add.component.ts
- src/app/resources/resources.component.ts
- src/app/resources/resources.module.ts
- src/app/shared/dialogs/dialogs-add-resources.component.html
- src/app/shared/dialogs/dialogs-add-resources.component.ts
- src/app/shared/dialogs/dialogs-add-resources.module.ts
- src/app/teams/teams-view.component.html
- src/app/teams/teams-view.component.ts
- src/app/teams/teams.module.ts
- src/app/teams/teams.service.ts
- src/styles.scss
Allows a resource to be linked to a team from the library, or to create a new resource with the option (default) to make it only viewable by the team.
TODOs:
- A private team resource should be editable
- A private team resource should be deleted when removed (with a prompt notifying the user that the resource will be deleted)
- Private resources should be synced (for syncing teams), and maybe the public ones should be as well?  The public ones could cause conflicts, however.  Maybe there could be a button that the nation clicks to flag a public resource as ok to sync?  Or we only sync ones created on the community?
> TeamsView: Add resource

- src/app/teams/teams-view.component.html
- src/app/teams/teams-view.scss
[Fixes #4247] Right tile contents of team could be more compact
> [Fixes #4247] Right tile contents of team could be more compact

- docker/db-init/docker-entrypoint.sh
Travis checks are still failing, so trying to increase the timeout to wait for the database to start in db-init.
> Increase timeout in db-init

- src/app/shared/dialogs/dialogs-form.component.html
If I delete ```required``` key in ```addTeamDialogField``` object, the asterisk will disappear, but the field will become required. If I remove attribute ```required``` from component - then works as it should.
> 4360_issue_fix

- README.md
- Vagrantfile
- couchdb-setup.sh
- v-couchdb-setup.sh
Updates the Vagrantfile and setup script to
1. Only run the `docker start` in the "always" script if it is not already running
2. In addition run the CouchDB setup script after the container starts with proxy _admin authentication
@dogi I think we can add the new configuration setting to our template instead of here, correct?
In addition in case this problem comes up again added a small script `v-couchdb-setup.sh` to simplify the fix and referenced this in the **Troubleshooting** section of the README
> Vagrant: Fix member creation error in development (fixes #2470)

- couchdb-setup.sh
- design/security-update/security-update.json
I just noticed that in the setup script we attempt to add an index & security for an `activity_logs` database that we never create.  Removing those lines since they are unnecessary.
> Setup: Remove activity_logs from script

- src/app/shared/forms/planet-tag-input-dialog.component.html
- src/app/shared/forms/planet-tag-input-dialog.component.ts
When adding a subcollection to a resource or course the main/parent collection is also selected to make sure the subcollection shows up in the resources/courses view.
> Collections: Fix adding a subcollection

- src/app/shared/forms/planet-tag-input-dialog.component.ts
When creating a new subcollection ensures the main collection is also selected.
Note will probably need to be adjusted after #4566 is merged
> Collections: Add new subcollection selects main

- src/app/teams/teams.component.html
In addition to **Request to Join** as noted in #4579, the **Leave** button also needed the same fix
> Teams: Stop team routing for button clicks (fixes #4579)

- src/app/manager-dashboard/sync.directive.ts
- src/app/shared/user.service.ts
- src/app/teams/teams-view.component.html
- src/app/teams/teams-view.component.ts
- src/app/teams/teams.component.ts
- src/app/teams/teams.service.ts
The goal of this is to show member images in teams for local and connected teams.
Images will be added to the `attachments` database when the member is requesting membership or a member of a connected team.  That database will sync back and forth between community & nation so images will be available.
Added images to the **Members** and **Requests** tabs.  That could have been a different PR, but otherwise there would not have been any changes in the UI.
This does not handle cleaning out images when the member is no longer associated with a connected team.  If that is a problem, we can devise another solution for that.
> User image replication

- src/app/courses/courses.service.ts
- src/app/shared/forms/rating.service.ts
- src/app/shared/mangoQueries.ts
Noticed on planet somalia that courses was taking some time to load.  This should improve that by ensuring `_find` requests use `limit: 1000`.  This may improve speed in other areas since other requests were also using the default 25 instead of 1000.
> Ratings: Decrease time to fetch course ratings

- src/app/courses/courses.component.html
- src/app/courses/courses.component.ts
- src/app/resources/resources.component.html
- src/app/resources/resources.component.ts
- src/app/shared/table-helpers.ts
@dogi noted that in Courses there's a long wait before the list is usable.  I've noted that in resources as well.
Trying to add a `trackBy` function to the tables in case the issue is that the data source is being updated too much causing the entire table to rerender.
> Courses & Resources: Improve speed

- src/app/users/users.component.html
Fixes #4252: Teams - Members: Set role UI
> Fixes #4252: Teams - Members: Set role UI

- src/app/shared/forms/planet-tag-input-dialog.component.html
#4647
Clicking the list item for a supercollection now opens dropdown instead
> #4647 Course collection button dropdown

- src/app/manager-dashboard/sync.directive.ts
- src/app/shared/sync.service.ts
The replicator ids were changed in #4265 to remove the underscores from the database name, but the ids set to be deleted before a sync starts were not also changed to reflect this change.
Not sure if that change is necessary, but I kept it.  I made a shared function for creating the id for the replicator so the deletion & creation functions use the same one.
> Sync: Fix conflict error (fixes #4740)

- .travis/travis_utils.sh
- docker/planet/scripts/build_planet.sh
- package.json
Based on a couple of solutions found:
https://travis-ci.community/t/how-to-fix-the-following-build-error-in-travis-ci-fatal-error-call-and-retry-last-allocation-failed-javascript-heap-out-of-memory/4428
https://github.com/angular/angular-cli/issues/5618#issuecomment-450151214
In Travis we set an environment variable that increases the memory limit for Node.  I also added the npm command suggested by the Angular CLI dev so we can run the build locally without memory issues.
> Travis memory fix (fixes #4804)

- src/app/validators/validator.service.ts
Fix #3276. I did not format the couchservice current time output and found a better way to do the validation
> added time to input date(Fixed 3276)

- src/app/tasks/tasks.component.ts
- src/app/teams/teams-view.component.html
- src/app/teams/teams-view.component.ts
#4864
After clicking a notification for being assigned a task, the tab selected switches to Tasks.
The switch is a little wonky (it stops at Calendar first for me), but as long as it gets to Tasks for you then let's merge.
> TeamsView: Task tab loads after notification (fixes #4864)

- src/app/shared/calendar.component.ts
#4846 
Calendar events over multiple days with recurrence will now show up for their full duration every time instead of only the first.
> Calendar: Fix recurring event over multiple days (fixes #4846)

- src/app/courses/add-courses/courses-add.component.ts
- src/app/home/home.component.ts
- src/app/login/login-form.component.ts
- src/app/shared/auth-guard.service.ts
- src/app/shared/database/index.ts
Last part missed in #4778.  There was a file that was only used to consolidate imports for two other files.   Required a few other changes to import statements to remove fully.
> Refactor: Remove unnecessary file (fixes #4753)

- src/app/feedback/feedback-view.component.html
- src/app/feedback/feedback-view.component.ts
- src/app/feedback/feedback.directive.ts
- src/app/feedback/feedback.module.ts
- src/app/shared/utils.ts
Truncated name, turned params into an object.  I'm not sure of the exact method of display, so I used JSON.stringify for a temporary fix, so please let me know what you'd like best for this.
> feedback title truncation (connects #3936)

- src/app/teams/teams-view.component.ts
fixed #4954 
I moved the spinner in `changeMembershipRequest` function to `changeMembership` function. 
Adding `leader` is not related to this issue, but it should be an error.
> fixed spinner( Fixed 4954)

- src/app/health/health-event.component.ts
- src/app/health/health.component.html
- src/app/health/health.service.ts
#5013
Fixed by adding an `id` parameter to the HealthEvent route which is used when the event/exam is submitted.
> HealthEvent: Allow adding an event before profile (fixes #5013)

- src/app/teams/teams-view.component.ts
fixed #5011 
The issue was actually caused by `setTasks` crash when the user is still not a member of team.
> Team: request notification (Fixed 5011)

- couchdb-setup.sh
- src/app/configuration/configuration.service.ts
Sets the CouchDB into couch per user mode with the "databases" named like
```
userdb-<configurationcode>-<hexofusername>
```
Creates the setting in two places
1. When the configuration is initially created
2. In `couchdb-setup.sh` if the Planet configuration has been set.  This is used to upgrade current deployments and fix in case the CouchDB setting is changed.
> Couch per user

- couchdb-setup.sh
- src/app/configuration/configuration.service.ts
- src/app/shared/utils.ts
#5122 
Change to convert the `planetCode` into a hex string as well.  This ensures the database prefix is limited to valid characters for CouchDB databases.
> Couch peruser: Fix invalid database name (fixes #5122)

- couchdb-setup.sh
We should test in production on both x86 and ARM to make sure the `db-init` docker is working.
> Fix blank planet code in userdb prefix (fixes #5159)

- src/app/health/health-event-dialog.component.ts
#5307 
Not as bad of an error as I initially thought since this will only affect exams created before 0.9.31.
> Health: Fix old exam dialog open (fixes #5307)

- src/app/news/news-list-item.component.html
- src/app/news/news-list-item.component.ts
- src/app/shared/forms/planet-markdown-textbox.component.ts
- src/app/shared/planet-markdown.component.ts
- src/app/shared/shared-components.module.ts
@lmmrssa I know the suggestion was to use `/db/`, but looking into the documentation for the markdown parser we are using, the `[hostedUrl]` property is required for relative links anyway so I just set that to `environment.couchAddress`.
> News: Relative links for images (fixes #5328)

- src/app/shared/planet-markdown.component.ts
The `hostedUrl` property for `td-markdown` requires a closing `/` otherwise it cuts off part of the url.
> Markdown: Fix markdown image base url (fixes #5343)

- src/app/health/health.service.ts
Making a change to the strategy if multiple keys were created for a user by mistake.
If they already have a health document, it was created with the first key.  This way we hopefully avoid them not being able to access their data because the system is using the wrong key.
> Health: If many keys use first created (fixes #5305)

- src/app/resources/resources.service.ts
- src/app/resources/view-resources/resources-view.component.ts
#5294 caused a regression on the library loading.  Previously the loading spinner would stop after the first 1000 resources were loaded and the table would continue to update as more batches of 1000 resources were fetched from the database.  After that PR the loading spinner waits for all resources before closing.
There are two things to test here 
- On the Library page hit refresh to see if the resources again load in batches of 1000.
- On a page viewing a resource not in the first batch of 1000, refresh to make sure the resource loads.  #5294 fixed an issue where that resource would not load on refresh & the app would navigate to the resource list.
> Resources: Fix gradual load of library

- src/app/health/health-list.component.html
- src/app/health/health-list.component.ts
- src/app/health/health.service.ts
- src/app/users/users-table.component.html
- src/app/users/users-table.component.ts
Since the health list loads each individual's health record with a separate request to the database, we limit the requests to only the members on the current page of the table.
> HealthList: Only load health data on current page (fixes #5285)

- src/app/shared/forms/planet-markdown-textbox.component.ts
#5365 
Rather than doing the full refactor, I made some tweaks to fix the version of the component that only has text and no images.
Thinking it over more thoroughly I realized there would be a risk of creating more issues with a full refactor, so would rather make a small change here.
> Markdown: Fix value for inputs without images (fixes #5365)

- src/app/surveys/surveys.component.ts
#5590 
I realized the issue is that we did not have a `sourcePlanet` field in the exams database so older surveys were being duplicated or added to the list even if they were not from the nation/parent planet.
Since the main survey in the field we are working with has that field (and future surveys will have it, too), I think we can safely ignore those submissions for the purpose of exporting nation survey data from the list.
> Surveys: Fix submissions in survey list (fixes #5590)

- src/app/surveys/surveys.component.ts
#5606 
A little more about that issue: it's most noticeable on Somalia where there are many submissions.  Fetching 25 at a time meant there were a lot of requests to the database which made loading the survey list very slow.
> Surveys: Fix slow loading (fixes #5606)

- src/app/community/community.component.html
#5628 
Turns out the links were working, but only if you clicked on the text.  Now clicking anywhere along the row in the list will direct to the linked team or enterprise.
> Community: Fix services links (fixes #5628)

- src/app/courses/add-courses/courses-add.component.ts
@paulbert tried to check different approach. It was updating courseservice with initaltags and resetting course, so not sure why it was done so. But after looking for some options I came to update course if courseservice was not intially set which happens when you are not coming back from course view or edit such as reload.
Could you test with some more cases to make sure it works with all.
> [#3718] Course update reload

- src/app/surveys/surveys.component.ts
#5590
Another pass at this because on planet.dev.ole.org there were still many surveys on the list from communities that should not appear there.
Explicitly only shows surveys created on the parent planet.  Note this means that surveys passed between nations, like the challenge survey copied from somalia to dev, will no longer show up in communities unless the `sourcePlanet` property is changed to match the planet it was moved to.
> Surveys: Only show parent not any other planet (fixes #5590)

- src/app/community/community.component.ts
#5648 
The selector for the replication of the `teams` documents means that doing a DELETE request to remove a link removes it from replication.
Doing a POST request with `_deleted: true` deletes the document but keeps the metadata so the replication will still work.
> Community: Delete links for nation replication (fixes #5648)

- src/app/community/community.component.ts
#5645 
The **CommunityComponent** was fetching its news before the configuration was set.  That means if `planetCode` was not set, it would show all news on the page instead of the ones based on the current planet configuration.
> Community: Only show specific planet news (fixes #5645)

- src/app/community/community.component.html
#5661 
Fixed the condition for showing the editing buttons for Services and Finances.  They were not showing up because the `planetCode` is based on the route parameters, and for `/` that is `null`.
> Community: Show editing for local admins (fixes #5661)

- src/app/teams/teams.service.ts
#5678 
Removed a section that was causing the error but no longer used.
That piece of code was from when the Community section was the same as an Enterprise, but with all members of the Community in the Members tab.  Now we only show the leaders & use different functions to do that.
> Community: Fix missing links & finances (fixes #5678)

- src/app/teams/teams-view.component.ts
#5709 #5711 
That section of code is called when initializing a dialog in **TeamsViewComponent** even when it is not used, so we needed to account for `memberDoc.userDoc` being undefined.
> TeamsView: Fix breaking removal error (fixes #5709 fixes #5711)

- src/app/courses/step-view-courses/courses-step-view.component.html
Seems like the conditional needs to be `true` or `false` because the `*ngIf` in the line returns `0` but still shows when there are no questions on the exam.
> CoursesStepView: Fix empty exam blocking progress

- src/app/submissions/submissions.service.ts
The page with all learner progress for a course (from the `Progress` choice in the three dot menu for a course) was not loading in my production environment.
I realized myPlanet had put photos in the `submissions` database with a different format than the other documents.  I know myPlanet no longer does that, but there may be similar documents in the field.  Rather than try to remove those, we can ignore them where they would throw errors.
> CoursesProgress: Fix spinner stuck (fixes #5724)

- src/app/community/community.component.ts
- src/app/news/news-list-item.component.html
- src/app/news/news-list-item.component.ts
- src/app/news/news-list.component.html
- src/app/news/news-list.component.ts
- src/app/news/news.component.ts
- src/app/news/news.service.ts
- src/app/teams/teams-view.component.ts
Adds a "share time" which is set differently for the different communities the story was shared with.
Since this should only be present for community news, the sorting only runs for community news.
There's a larger change to the news components to keep the database document in a `doc` property with other calculated metadata like `avatar` and `sharedDate` separate.  This makes sure the news document is not affected after editing or adding a label.
> News: Add & sort by share time (fixes #5799)

- src/app/courses/courses.service.ts
Ensures that any extra documents in the `courses_progress` database are deleted, even if they all have the correct value for `passed`.
> CoursesStepView: Fix never ending _find requests (fixes #5824)

- src/app/news/news-list-item.component.ts
Did not realize the first `ngOnChanges` gets called before `ngOnInit`, so the share button was not showing on nation news.
> NewsItem: Fix nation share button not showing

- src/app/manager-dashboard/reports/reports-myplanet.component.ts
There were no subscriptions that needed to be completed with the final commit in #5594.  Removing the `OnDestroy` and other unused properties.
> ReportsMyPlanet: Clean up unused component properties

- src/app/submissions/submissions.service.ts
The issue was only when a course had some steps without exams.  `step.exam` was undefined so `step.exam._id` was throwing an error.
> Submissions: Fix course progress update after grading (fixes #5863)

- src/app/shared/table-helpers.ts
Found an error with table filters if one of the filtered field values is an empty string (or 0 in theory).  This error would break the table completely and it was not shown at all.
> Tables: Fix case if filter field is blank string

- src/app/manager-dashboard/sync.directive.ts
#5895 
If a document has fields that should not exist in `replicator_users`, they will be removed after syncing.
> Sync: Clear passwords from replicator_users (fixes #5895)

- src/app/community/community.component.html
- src/app/news/news-list-item.component.ts
- src/app/news/news-list.component.html
- src/app/news/news-list.component.ts
- src/app/teams/teams-view.component.html
- src/app/teams/teams-view.component.ts
Allows people outside of the team or enterprise to post messages.  These messages can be viewed by anyone else in the community, also.
Replies for that message can also be viewed by anyone in the community.
> TeamsView: Public news messages (fixes #5923)

- .travis.yml
- couchdb-setup.sh
- src/app/courses/courses.component.ts
- src/app/resources/resources.component.ts
- src/app/shared/forms/search.service.ts
- src/app/shared/utils.ts
Creating a `search_activities` database to keep this separate since this may become the largest database very quickly.
Includes data for the text searches, collections/tags, and the filter fields for Courses and Resources.
Changes are debounced for 5 seconds or until the user leaves the Courses or Resources pages.  If after the 5 seconds the search is the same as it was previously, nothing is written to the database.
> Resources & Courses: Track searches (fixes #5893)

- src/app/teams/teams-member.component.html
This is a small quick fix for #6061 
As noted in the issue, the full fix will require handling the case where there are two members with the same username (one from nation one from community)
> TeamsMember: Show leader from other planets (connects #6061)

- src/app/shared/couchdb.service.ts
#6149 
A specific resource was missing from the dashboard on Somalia (Mr. Smith Goes to Washington) because the `_bulk_get` request was returning two revisions, one of which was `_deleted`.
It's possible there are other cases where this would happen and in those cases the docs may not be sorted by revision, so we check all of them and pick the latest.
> Dashboard: Fix missing resource (fixes #6149)

- src/app/dashboard/dashboard.component.ts
#6178 
This is the quick patch so the dashboard information appears.  Leave the issue open so we know to investigate why there are `null` values in the shelf database for some members.
> Dashboard: Fix empty row error (connects #6178)

- src/app/tasks/tasks.component.html
- src/app/tasks/tasks.component.ts
#6174
Went with a simple solution: clicking the list opens the dialog the same as the calendar, so you need to click exactly on the checkbox to complete the task.
I think we could add more to the dialog for completion, reassignment, and editing functionality but this is a good start.
> Tasks: Click task to open details (fixes #6174)

- src/app/tasks/tasks.service.ts
issue: #6224 
When editing tasks any past date can be added.
> Tasks: Past date allowed in edit (fixes #6224)

- src/app/shared/forms/planet-forms.module.ts
- src/app/shared/forms/planet-number-validator.directive.ts
#6263 
In researching I found that you can also enter something just `+` in Chrome which should trigger a validation error without a number after.
Also found that this is a longstanding issue with Angular.  Added a little workaround that will automatically be in place for any `<input type="number">` fields.
> Health: Fix number validation (fixes #6263)

- design/resources/resources-design.js
- design/resources/resources-design.json
- src/app/resources/resources-add.component.ts
- src/app/shared/utils.ts
- src/app/validators/validator.service.ts
#6353 
Indexes won't work with regex, and I think because of the uppercase/lowercase issue we wouldn't be able to do an equality `_find`.  I went with the view approach, and this should be a lot faster/less intensive on the RasPi.
> ResourcesAdd: Faster resources check unique (fixes #6353)

- src/app/shared/calendar.component.ts
Fixes #6345 
[Full Calendar Docs](https://fullcalendar.io/docs/buttonText) provides a way to change the text in any of the default buttons.
> Capitalize today button (fixes #6345)

- src/app/submissions/submissions.component.html
- src/app/submissions/submissions.component.ts
…. Issue #6210
Added two buttons to the toolbar header to allow to switch between searching by person(user) or by title(name).
This might not be what is needed or correct, but this is the only way I could think of making it work. Because, the Resource search uses data from the db and the submissions search has a mat-table-data source.
This is not the final commit that should be merged. I just wanted to push my changes, so that others would be able to look them over.
> Added FilterSpecificFieldsByWord function to setupTable to make it possible to search for separate words

- src/app/health/health-event.component.ts
- src/app/shared/forms/planet-round.directive.ts
Fixes #6337 
JavaScript wasn't recognizing zero as a number, so the `onFocusOut()` in **planet-round.directive** would fail at the first check. This was causing strange behavior where the zero would be converted into an empty string, but the input element would still have the `ng-valid` attribute, allowing the form to be submitted.
I updated the check in **planet-round.directive** to pass if the value entered is a zero in addition to checking the type. Now the minimum validator in **HealthEventComponent** will show the error `The number cannot be below zero` when zero is entered.
> Fix rounding and input validation (fixes #6337)

- src/app/community/community-list.component.ts
Since the two fixes overlap in code, combined #6490 and #6495.
When there are no other communities left in the share list, the hub community still shows up.
Conversely, if the post has already been shared with the hub community, the hub will no longer show up.
> CommunityList: Show and hide hub correctly (fixes #6490 fixes #6495)

- src/app/submissions/submissions.service.ts
Thanks @paulbert for your review,  as I was looking through this issue. I found out all the new courses that we create recently attached to surveys are not having problem. I have newly created community so I was unable to replicate in my development environment. I work with with these specific case in planed.dev and planet.somalia which were not being exported.
1. In planet.dev. there is survey ‘DEMO-Courses with surveys’ which when we export gives console error answers[index] is undefined. 
2. In planet.somalia also there is a survey ‘Your Reading Pledge’  whose submissoin.length was 0. Which was also not being exported.
> Surveys: Can't export some surveys attached to course(fixes #5775)

- src/app/manager-dashboard/reports/reports-detail.scss
- src/app/manager-dashboard/reports/reports-health.component.html
- src/app/manager-dashboard/reports/reports-health.component.ts
Fixes #6500 
The reason the `mat-select` didn't have an underline was because it wasn't wrapped in a`mat-form-field`, so I added that. However, that brought a lot of spacing that I was unable to figure out how to disable/reduce. So I tried to vertically center the span in relation to its parent div to align with the `mat-select` field.
> Fix underline (fixes #6500)

- src/app/exams/exams-add.component.html
**Issues:** #6458 
**Description:**
The PR  changed Return button to _Save & Return._
**Image:**
> Changing Return button to Save & Return fixes  #6458

- src/app/teams/teams-view-finances.component.ts
@paulbert we were not allowing decimal before so kept integer validator. If you want to remove integer validator and allow upto 0.1 then please let me know
> [#6569] Finance do not allow zero

- src/app/exams/exams-add.component.ts
Fixes #5091 
So the query works, however I'm having a strange issue where planet updates the amount of times a survey has been taken, but the `submissions` database doesn't reflect that.
This doesn't make sense to me because that data in **SurveysComponent** is coming from the `submissions` database. @paulbert @lmmrssa could you shed some light on what's happening here or tell me if I'm misunderstanding?
> Survey: Append copy (fixes #5091)

- src/app/courses/view-courses/courses-view.component.ts
- src/app/resources/view-resources/resources-view.component.ts
Fixes #6638 
Remove the edit option when a user tries to view **Resources** and **Courses** from the **Manager** page.
> Remove edit from Manager (fixes #6638)

- src/app/teams/teams-view.component.html
Fixes #6693 
The **Reject** button should be enabled when at max members. Only the **Accept** button should be disabled.
> Enable reject when at max members (fixes #6693)

- couchdb-setup.sh
- src/app/configuration/configuration.service.ts
#6710 
Once a Planet has been setup with Health it has the database correctly configured.  This fixes the setup for new Planets or ones that have not been setup with Health yet.
> Health: Fix database setup without beta (fixes #6710)

- src/app/courses/add-courses/courses-add.component.ts
#6833 
The error will no longer occur because blank markdown will now correctly block the form from being submitted, but I'm not sure if this fixes all cases where this error shows up hence the "connects" in the title.
> CoursesAdd: Fix description requirement (connects #6833)

- src/app/dashboard/dashboard.scss
- src/app/shared/calendar.component.ts
Fixes #7074 
For mobile devices rating star was unresponsive and stayed on the side instead of moving down as the date moved for smaller screens
Issue is with grid template rows specifying the rating star row position
Idea was to make the rating star closer to the date on larger screens as was initially set, hence the commented out media query
> dashboard rating mobile screen (fixes #7074)

- src/app/resources/resources.service.ts
- src/app/resources/search-resources/resources-search.component.ts
Fixes #7195 & #7196 
- Update the categories label from `mediaType` to `medium`. Medium is the correct field in use in couch.
Other updates
- Remove empty constructor
- Removed unused imports in the `resources.service.ts`
> library: activate video filter (fixes #7195)(fixes #7196)

- package.json
- src/app/chat/chat.component.html
- src/app/chat/chat.component.ts
Fixes #7235 
Prevent the spinner from loading when the chat form is invalid
Other updates
- Changed the Validators class in use
- Refactor the onSumbit function
- Add scrolling effect on error detection
> chat: only spin on valid submission (fixes #7235)

- package.json
- src/app/chat/chat.component.html
- src/app/chat/chat.component.ts
Fixes #7234 
- Clear the chat text area on chat submission
- Rename message label to avoid duplication with the textaeea placeholder
> chat: clear textarea on submit (fixes #7234)

- package.json
- src/app/courses/courses.component.html
Fixes #7253 
Restrict the courses progress menu item to be visiblle to admin users only
> courses: progress menu item admin only (fixes #7253)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/courses.component.ts
- src/app/courses/courses.scss
- src/app/resources/resources.component.html
- src/app/resources/resources.scss
- src/styles.scss
Courses & Resources
Resizing the tables and the table item sizes for $screen-md sizes and below
Resizing the non-title fields:
> courses: reactive table resizing (fixes #7260)

- package.json
- src/app/courses/step-view-courses/courses-step-view.component.html
- src/app/courses/view-courses/courses-view-detail.component.html
- src/app/courses/view-courses/courses-view.component.html
- src/app/shared/planet-markdown.scss
Fixes #7272 
Building on #6150 
- Create a new css class that only resizes the images -> This will have them using the default **block display**.
- Apply this new css class to specific areas: **Courses view**, **view-detail** and **step-view**
- Maintain the text wrap around images for the Courses & Resources pages(Table)
- Add padding to separate Images that are in text wraps
> courses: markdown block images (fixes #7272)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/courses.scss
- src/app/resources/resources.component.html
- src/app/resources/resources.scss
- src/styles.scss
- Rework the table column sizes: Make the rating grid smaller in the courses & resources pages
Courses page
Resources page
> courses: better table sizes (fixes #7279)

- package.json
- src/app/courses/courses.component.html
- src/app/resources/resources.component.html
- src/styles.scss
Fixes #7259
Courses & Resources: Handle the title overlap in 2 ways
- Set the grid row height of the title row to auto when the title exceeds 50 chars
- Cut off the title when it exceeds 180 char(courses) & 200 chars(resources)
**Before**
**After**
> courses: better handling long titles (fixes #7259)

- package.json
- src/app/courses/courses.component.ts
- src/app/shared/table-helpers.ts
Fixes #7261 
Courses: Resolve the filter bug that occurs when the **grade level** or **subject level** are not defined during course creation.
- Check if the value is a string before calling _toLowerCase_ which was throwing an error
- Remove unused imports in the `courses.component.ts`
> courses: improve filter stability (fixes #7261)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.html
- src/app/chat/chat-sidebar/chat-sidebar.component.ts
- src/app/chat/chat-window/chat-window.component.html
- src/app/chat/chat-window/chat-window.component.ts
- src/app/shared/chat.service.ts
Fixes #7297 
- Ensures that the latest conversations are added to the top
- Auto updates the chat history list when a new chat is added
- Adds a message if there are no chats in the history.
- Add internationalization to chat(and related) components
> chat: last is first with auto refresh (fixes #7297)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.html
- src/app/chat/chat-window/chat-window.component.html
- src/app/chat/chat-window/chat-window.component.ts
Fixes #7302
Improve the chat form submission validation
- Prevent submission of only blank spaces
- Remove the mat-error message and disable the button in its place
- Handle the conversations length issue being thrown
> chat: improve submission validation (fixes #7302)

- package.json
- src/app/community/community.scss
- src/app/shared/calendar.component.ts
Fixes #7308
- Improve how multiple events in a single day are displayed using a popover.
- Improve the handling of the titles length
> calendar: showing maximum 2 events a day (fixes #7308)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/courses.component.ts
- src/app/resources/resources.component.html
- src/app/resources/resources.component.ts
Fixes #7310 
For mobile or tablets add a responsive toggle to show or hide the filter rows - allows us to capture more screen real estate.
> courses: responsive filter toggle (fixes #7310)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/courses.scss
- src/app/resources/resources.component.html
- src/app/resources/resources.scss
Fixes #7312
Reposition the checkbox cell for mobile devices in the courses and the resources.
> courses: improve responsive mobile layout (fixes #7312)

- package.json
- src/app/community/community.scss
- src/app/shared/calendar.component.ts
- src/styles/calendar.scss
Fixes #7326 
- Remove unused imports and comments
- Clean up the `calendar.scss` styles
- Move calendar related styles from the `community.scss` to the `calendar.scss`
> community: calendar cleanup (fixes #7326)

- package.json
- src/app/community/community.scss
- src/app/teams/teams-view.scss
Fixes #7334 
In the Community Leaders & Team Members tabs
Fix the inconsistent height issue of the cards showing the members
Community Leaders
Teams Members
> teams: better members view (fixes #7334)

- package.json
- src/app/teams/teams-reports-detail.component.ts
- src/app/teams/teams-view-finances.component.ts
Fixes #7336 
When the currency is not in the configurations db, null is not displayed, it displays $.
> enterprises: better finances currency handling (fixes #7336)

- package.json
- src/app/community/community.component.ts
Fixes #7348 
Community services form now shows previously existing content while editing
> community: better services edit experience (fixes #7348)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.html
- src/app/chat/chat-sidebar/chat-sidebar.component.ts
- src/app/chat/chat-sidebar/chat-sidebar.scss
- src/app/shared/shared-components.module.ts
Fixes #7319 
Advanced `Full Conversation Search` options i.e to search through the questions only or the responses only.
> chat: advanced search (fixes #7319)

- package.json
- src/app/meetups/add-meetups/meetups-add.component.ts
- src/app/shared/calendar.component.ts
Fixes #7364 
Make the dates selectable to set events with date info preloaded.
> calendar: selectable meetup dates (fixes #7364)

- package.json
- src/app/courses/step-view-courses/courses-step-view.component.html
Fixes #7372
- Hide the step changes if course has only one step
- Disable the `Finish` button if test has not been completed
> courses: better step changes (fixes #7372)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.html
- src/app/chat/chat-sidebar/chat-sidebar.component.ts
Fixes #7383 
Chat list ordering based on the `createdDate` and `updatedDate` db fields.
The latest(either by creation time or update time) shows up first
> chat: better order (fixes #7383)

- package.json
- src/app/news/news-list-item.component.html
Fixes #7343
Allow any user to add a label for a news item.
Affects the Community , Teams & Enterprises.
> community: labeling for everbody (fixes #7343)

- package.json
- src/app/teams/teams-view-finances.component.html
- src/app/teams/teams-view-finances.component.ts
Fixes #7411 
Add an `export transactions` button in the teams and community finances
> enterprises: add finances export (fixes #7411)

- docker/chatapi/amd64-Dockerfile
- docker/chatapi/arm-Dockerfile
- docker/chatapi/arm64-Dockerfile
- package.json
- src/app/chat/chat-window/chat-window.component.html
Fixes #7426 
Update the the node versions to 18 
Enables running of Gemini, Perplexity and streaming functionality for openai
> chat: node 18 on alpine 3.16 (fixes #7426)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.html
- src/app/chat/chat-window/chat-window.component.ts
- src/app/manager-dashboard/manager-dashboard.component.html
- src/app/manager-dashboard/manager-dashboard.component.ts
Fixes #7439
Add a switch to turn on/off chat streaming.
> chat: add streaming option in manager dashboard (fixes #7439)

- chatapi/src/index.ts
- package.json
Fixes #7449 
Fix data availability and return errors in the chatapi container.
> chat: smoother api (fixes #7449)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.html
- src/app/chat/chat-sidebar/chat-sidebar.component.ts
- src/app/chat/chat-window/chat-window.component.html
- src/app/chat/chat.module.ts
- src/app/news/news-list-item.component.html
- src/app/news/news-list-item.scss
- src/app/news/news.service.ts
- src/app/shared/dialogs/dialogs-chat-share.component.html
- src/app/shared/dialogs/dialogs-chat-share.component.ts
- src/app/shared/dialogs/dialogs-chat-share.module.ts
- src/app/shared/label.component.ts
Fixes #7455 
Enable chat sharing with communities and teams.
- Custom label for shared chats.
- Send a message with the chat.
> chat: sharing (fixes #7455)

- package.json
- src/app/news/news-list-item.component.html
- src/app/news/news-list-item.scss
- src/app/shared/dialogs/dialogs-chat-share.component.html
- src/app/shared/dialogs/dialogs-chat-share.component.ts
Minor Improvements to the chat sharing.
- Allow sharing with the team/enterprise without a message
- Allow the users to edit the message of the shared chat
- Mobile/Tablet responsiveness of the Shared chat
Tablet view:
Mobile view:
> chat: sharing improvements (fixes #7466)

- package.json
- src/app/users/users-achievements/users-achievements-update.component.ts
- src/app/users/users-achievements/users-achievements.component.html
- src/app/users/users-achievements/users-achievements.service.ts
Fixes #7469
- Fix issue in myAchievements summary page resulting from adding an achievement
- Cleanup post removal of resources support
> mylife: smoother achievement summary (fixes #7469)

- package.json
- src/app/users/users-achievements/users-achievements-update.component.html
- src/app/users/users-achievements/users-achievements-update.component.ts
- src/app/users/users-achievements/users-achievements.component.html
- src/app/users/users-achievements/users-achievements.scss
Fixes #7442
Add 2 types of links:
- General links for the entire achievements page i.e portfolio link and similar
- Links under specific achievements.
General link
Achievement link:
> mylife: add links to achievements (fixes #7442)

- package.json
- src/app/shared/chat.service.ts
Fixes #7472 
Fixes the blank page that happens on redirecting from the chat
To replicate: streaming is set to off on the manager dashboard
Caused by websocket trying to be closed when it is not defined
> chat: smoother redirection (fixes #7472)

- package.json
- src/app/news/news-list-item.component.html
Fixes #7486
- Limit adding label and community sharing to the user who created the message 
- Allow admin to have override permissions
> news: more admin permissions (fixes #7486)

- package.json
- src/app/teams/teams-view.component.html
Fixes #7513
- Slice course/resource titles and desciptions to avoid text-overflow.
> teams: smoother courses view (fixes #7513)

- package.json
- src/app/courses/step-view-courses/courses-step-view.component.html
- src/app/courses/step-view-courses/courses-step-view.scss
Fixes #7527 
- Adjust the grid view to only show 2 columns when the chat window is active. The resource-viewer & markdown appear in flex view  when the chat window is active
- Only show the flex/grid view toggle when the chat window is not active
> courses: smoother chat view (fixes #7527)

- package.json
- src/app/resources/view-resources/resources-viewer.component.html
- src/app/resources/view-resources/resources-viewer.component.ts
- src/app/resources/view-resources/resources-viewer.scss
Fixes #7531 
Update the resources-viewer to support full-screen mode when working with pdfs
> resources: fullscreen for pdfs (fixes #7531)

- package.json
- src/app/chat/chat.component.ts
- src/app/shared/chat.service.ts
Fixes #7558
Implement state management for providers to avoid calls to the `checkproviders` endpoint on every chat component init, Instead have it once on app init
> chat: smoother provider management (fixes #7558)

- chatapi/README.md
- chatapi/src/utils/chat-helpers.utils.ts
- package.json
Fixes #7571
Default empty context to avoid getting curl error
> chat: smoother api context default (fixes #7571)

- package.json
- src/app/manager-dashboard/reports/reports-detail.component.ts
Fixes #7596 
Ensure that the setStepCompletion is called when this.progress.steps has been initialized
> manager: smoother coursesteps report (fixes #7596)

- package.json
- src/app/manager-dashboard/reports/reports-detail.component.ts
Fixes #7601
We have both user and userId column when exporting `courses progress`
> manager: smoother courses progress export (fixes #7601)

- package.json
- src/app/manager-dashboard/manager-dashboard.component.html
Fixes #7609 
Makes nation status messages (loading, deleted, pending) more visible. Also added the word "yet" to the pending message to clarify that the request has not been rejected.
> manager: smoother planet status (fixes #7609)

- package.json
- src/app/manager-dashboard/reports/reports.component.html
- src/app/manager-dashboard/reports/reports.component.ts
- src/app/manager-dashboard/reports/reports.components.scss
Fixes #7620
For Small Screen ($screen-sm)
For Tablet ($screen-md)
For Desktop
P.S, I didn't change out anything for Tablet ($screen-md) and Desktop since the button didnt overflow for the secondary toolbar. However, I did found out that the ipad mini (which I found as a tablet) still falls under small screen sizes, so it follows the small screen layout
> manager: smoother reports navigation (fixes #7620)

- package.json
- src/app/surveys/surveys.component.html
- src/app/surveys/surveys.component.scss
- src/app/surveys/surveys.component.ts
Made the Surveys page responsive and improved button alignment and text overflow. 
web:
$screen-md:
$screen-sm:
Fixes #7621
> surveys: smoother list (fixes #7621)

- package.json
- src/app/teams/teams-reports.component.html
export to csv button only appears if there are reports available now
> community: smoother reports export (fixes #7670)

- package.json
- src/app/courses/courses.component.ts
- src/app/resources/resources.component.ts
> courses: smoother search (fixes #6733)

- package.json
- src/app/courses/view-courses/courses-view.component.html
- src/app/courses/view-courses/courses-view.component.ts
Fixes #6744 
Here is a video starting at 0:08, since its very hard to see, you should pause at 0:09
https://www.loom.com/share/90d8709658a342d2ad0c01a0493d6f4a?t=9&sid=fd1fcc4e-304d-4456-9bfa-9c71f4a21934
Here's a screenshot also:
**Now it will only display `No Content on Courses` when it finsihed loading the courses**
> courses: smoother details loading (fixes #6744)

- package.json
- src/app/community/community.component.html
- src/app/community/community.component.ts
Added loading message to Voices (fixes #7691). Video is quick, so see around 6 seconds. 
[community-voices-screen-record.webm](https://github.com/user-attachments/assets/feaccd54-dd59-4146-91fa-a29befff876b)
Wrapped no voices, services, links placeholders in an i18n span to make them translate (fixes #7682). I don't know how to test translations on my dev environment, but it seems simply having the i18n tag in a paragraph tag wasn't translating. Having it in a span works elsewhere, so it should work here too.
> community: smoother voices (fixes #7691) (fixes #7682)

- package.json
- src/app/resources/view-resources/resources-view.component.html
- src/app/resources/view-resources/resources-view.component.ts
Library resources no longer say "There is no content for this resource while loading." A loading message appears instead. 
fixes #7706 
[Library loading content.webm](https://github.com/user-attachments/assets/4f8b6422-1b9d-4460-b70b-fe1a23b0c1d5)
> resources: smoother loading (fixes #7706)

- package.json
- src/app/teams/teams-view-finances.component.html
Fixes #7702 
When there is no transaction, export button is hidden
When there is transaction, then export button is visible
> teams: smoother finances export (fixed #7702)

- package.json
- src/app/shared/diacritic-insensitive-match.ts
- src/app/shared/table-helpers.ts
Fixes #7689 
When searching courses and library, characters a and á, e and é, n and ñ, etc, are now treated as equivalent. This makes searching Spanish titles easier and requires less precision from the user.
> resouces: smoother search (fixes #7689)

- src/app/shared/dialogs/dialogs-announcement.component.html
- src/app/shared/dialogs/dialogs-announcement.component.scss
Problem:
Fixes:
If there is enough space for the label, it will act as previous code
> challenges: smoother progress bar label

- src/app/shared/dialogs/dialogs-announcement.component.html
- src/app/shared/dialogs/dialogs-announcement.component.scss
- src/app/shared/dialogs/dialogs-announcement.component.ts
This is the first iteration of the success message after all steps are completed. Obviously, this needs to be changed and updated based off of the specific user reqs. Just figured I would start working on it to get an idea of where we want to go with this.
> 7712 challenge success message trigger mechanics (Not final ui)

- package.json
- src/app/community/community.component.html
- src/app/community/community.scss
added spacing for community description fixes #7762
> community: smoother services (fixes #7762)

- package.json
- src/app/courses/add-courses/courses-add.component.html
- src/app/courses/add-courses/courses-add.component.ts
- src/app/resources/resources-add.component.html
- src/app/resources/resources-add.component.ts
- src/app/shared/table-helpers.ts
Courses/resources now have a dynamic label based on the action (Add or Edit). 
Fixes #7728
> resources: smoother edit title (fixes #7728)

- package.json
- src/app/shared/forms/planet-tag-input-dialog.component.ts
Fixes #5776 
After deleting a tag, if the tag is available, you can instantly add it to the collection.
If you delete `b` but trying to insert `a` while `a` is still exist, it will not let you do it
> resources: smoother collection tags (fixes #5776)

- package.json
- src/app/dashboard/dashboard.component.html
- src/app/dashboard/dashboard.component.ts
> dashboard: smoother avatar linking (fixes #4532)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.ts
- src/app/shared/dialogs/dialogs-chat-share.component.ts
Fixes #7812
When you click on share, it doesn't marked as share, it waits until you complete an action (either sharing into community or team / enterprise).
> chat: smoother share (fixes #7812)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.ts
- src/app/chat/chat-window/chat-window.component.ts
- src/app/chat/chat.component.ts
- src/app/shared/chat.service.ts
Fixes #7638
Fixes #7809 
New chat:
If you are currently on a chat with a specific provider, then switching provider will create a new chat.
If you haven't selected an existing chat with a model, than switching chat does nothing.
Select existing chat:
If you select an existing chat, it will switch over to the model that the chat previously used (since we want to let a chat be tied to a specific model)
> chat: smoother provider switching (fixes #7638)(fixes #7809)

- package.json
- src/app/courses/view-courses/courses-view-detail.component.html
fixes #7839 
Course detail now has a date to show when course was created.
> courses: smoother details creation date (fixes #7839)

- package.json
- src/app/chat/chat-sidebar/chat-sidebar.component.ts
- src/app/chat/chat-window/chat-window.component.html
- src/app/chat/chat-window/chat-window.component.ts
Fixes #7836 
When navigating to the chat page, creating a new chat, or selecting an existing one, the input field is focused so the learner can begin typing immediately.
> chat: smoother input autofocus (fixes #7836)

- package.json
- src/app/courses/view-courses/courses-view.scss
fixes #7870 
Icons are now aligned to the right and have a little bit of extra space between them.
> courses: smoother steps icons (fixes #7870)

- package.json
- src/app/courses/add-courses/courses-step.component.html
fixes #7867
Added a max length for creating a step title at 150 characters. If we feel like this is too short or too long, I can always make adjustments.  I don't think that there will be an actual need to create titles over 150 chars for steps.
> courses:  limit step titles length (fixes #7867)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/courses.component.ts
- src/app/courses/enroll-courses/courses-enroll.component.html
- src/app/courses/enroll-courses/courses-enroll.component.ts
- src/app/feedback/feedback.component.html
- src/app/feedback/feedback.component.ts
- src/app/health/health-list.component.html
- src/app/health/health-list.component.ts
- src/app/manager-dashboard/certifications/certifications.component.html
- src/app/manager-dashboard/certifications/certifications.component.ts
- src/app/manager-dashboard/manager-fetch.component.html
- src/app/manager-dashboard/manager-fetch.component.ts
- src/app/meetups/meetups.component.html
- src/app/meetups/meetups.component.ts
- src/app/notifications/notifications.component.html
- src/app/notifications/notifications.component.ts
- src/app/resources/resources.component.html
- src/app/resources/resources.component.ts
- src/app/submissions/submissions.component.html
- src/app/submissions/submissions.component.ts
- src/app/surveys/surveys.component.html
- src/app/surveys/surveys.component.ts
- src/app/teams/teams.component.html
- src/app/teams/teams.component.ts
- src/app/users/users-table.component.html
- src/app/users/users.component.html
- src/app/users/users.component.ts
Fixes #7882
-  Move from using `emptyData` variable to track table data to using mat-tables native `matNoDataRow`
- Display a `No 'Item' Found` error in all affected tables
This fixes the table sort and pagination disruption caused by the re-render of the table when using emptyData
It also affects the following PRS:
#7767
#7775
#7856
#7805
#7851
> all: smoother empty tables (fixes #7882)

- package.json
- src/app/teams/teams-reports.component.ts
- src/app/teams/teams-view-finances.component.ts
fixes #7887, #7888
It no longer says 'undefined' when you export transactions or reports from the community page. Now it says whether the export comes from a community or a nation and supplies the name of the community/nation. If you export directly from the team, it still supplies the team name.
> enterprises: smoother csv exports (fixes #7887)(fixes #7888)

- package.json
- src/app/teams/teams.component.html
- src/app/teams/teams.scss
The "Toal visits from last 30 days" column in team/enterprises and when adding links on the services tabs will be more centered and less shifted to the left. Fixes #6546
> teams: smoother list (fixes #6546)

- package.json
- src/app/teams/teams-reports-dialog.component.html
- src/app/teams/teams-reports-dialog.component.ts
fixes #6946 changed blue close button to grey default close button to match consistency
> enterprises: smoother report dialog (fixes #6946)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/courses.scss
fixes #7664 
Long titles without spaces now get truncated
> courses: smoother titles (fixes #7664)

- package.json
- src/app/dashboard/dashboard-tile.component.html
fixes #7924
Long single words truncate when dragged, similar to other long titles.
> dashboard: smoother tiles (fixes #7924)

- package.json
- src/app/meetups/add-meetups/meetups-add.component.html
- src/app/meetups/add-meetups/meetups-add.component.ts
- src/app/shared/calendar.component.ts
- src/app/validators/custom-validators.ts
Fixes #7858
Recurring events now auto populate with the day of week currently selected in Start Date.
A validator prevents creation of recurring weekly events that do not have a day of the week selected
Works by both clicking the calendar cells or using the Add Event button.
> teams: smoother calendar recursions (fixes #7858)

- package.json
- src/app/courses/progress-courses/courses-progress-chart.component.html
- src/app/courses/progress-courses/courses-progress-learner.component.html
- src/app/courses/progress-courses/courses-progress-learner.component.ts
fixes #7911, #7936
Clicking on a course in myProgress now links to that course. Also, cleaned up messy tooltip from long course names.
> courses: smoother progress navigation (fixes #7911)(fixes #7936)

- package.json
- src/app/exams/exams-view.component.html
fixes #7949 
Previewing a test now has a more specific header. 
Works as before when it's a submission.
> courses: smoother exam preview header (fixes #7949)

- package.json
- src/app/resources/resources-add.component.html
- src/app/resources/resources-add.scss
> resources: smoother create (fixes #7798)

- package.json
- src/app/meetups/meetups.service.ts
- src/app/shared/forms/planet-tag-input-dialog.component.ts
- src/app/users/users-achievements/users-achievements.component.html
- src/app/users/users-achievements/users-achievements.scss
Fixes #7996 
Add width spacing between the link/achievement and the link/date
> mylife: smoother achievements spacing (fixes #7996)

- package.json
- src/app/news/news-list.component.ts
- src/app/news/news.service.ts
- src/app/shared/dialogs/dialogs-prompt.component.html
fixes #8016, #8017
Fixed dialog prompt when deleting a Voice. 
Opted to refer to the Voices/news/posts/messages as just "message" in all the snackbars for consistency.
> teams: smoother voices deletion (fixes #8016)(fixes #8017)

- package.json
- src/app/teams/teams.component.html
- src/app/teams/teams.scss
> teams: smoother list titles (fixes #8028)

- package.json
- src/app/health/health.component.html
fixes #8034)
Moved Emergency Contact to its own row, in order to avoid messy uneven rows.
> mylife: smoother myhealth emergency contact (fixes #8034)

- package.json
- src/app/shared/forms/planet-tag-input-dialog.component.ts
fixes #8058
It's now the same size for admins and non admins.
> resources: smoother collections dialog (fixes #8058)

- package.json
- src/app/shared/dialogs/dialogs-prompt.component.html
- src/app/teams/teams.component.ts
fixes #8083
Now it dynamically refers to it as an enterprise or a team in the dialog and snackbars.
> enterprises: smoother delete dialog (fixes #8083)

- package.json
- src/app/shared/dialogs/dialogs-images.component.html
- src/app/shared/dialogs/dialogs-images.component.scss
- src/app/shared/dialogs/dialogs-images.component.ts
fixes #8099
Now, when inserting a previously upload image to a course or resource , you don't have to scroll a potentially long alphabetical list of images. You can use the new search bar to filter filenames accordingly.
> resources: smoother markdown image search (fixes #8099)

- README.md
Adding a note in the troubleshooting section of the README reiterating the Node v14 prerequisite.
See #8124
> README: Add npm install troubleshooting note (fixes #8124)

- package.json
The @types/ms package was recently updated and is no longer compatible with TypeScript <4.6.3.
```
ERROR in node_modules/@types/ms/index.d.ts:58:9 - error TS1110: Type expected.
58         `${number}`
~~~
** Angular Live Development Server is listening on 0.0.0.0:3000, open your browser on http://localhost:3000/ **
Date: 2025-01-22T21:05:35.731Z - Hash: a6a6ed05705400319e05
5 unchanged chunks
Time: 1652ms
ERROR in node_modules/@types/ms/index.d.ts:58:11 - error TS1110: Type expected.
58         | `${number}`
~~~
```
> all: smoother dependencies (fixes #8139)

- package.json
- src/app/shared/forms/planet-tag-selected-input.component.ts
fixes #8144
Fixed an issue where this message was not appearing when multiple collections were selected.
> resources: smoother collections message (fixes #8144)

- package.json
- src/app/chat/chat-window/chat-window.component.ts
- src/app/courses/step-view-courses/courses-step-view.component.html
- src/app/courses/step-view-courses/courses-step-view.component.ts
Fixes #8107 
Now when you type something in course chat, it persist until you switch to another step, or when you navigate away.
> courses: smoother chat persistence (fixes #8107)

- package.json
- src/app/home/home.component.html
- src/app/shared/planet-language.component.html
fixes #8167, #8168
Made icons consistent in mobile and desktop view. 
Translate nav bar icon should work on mobile view now.
> all: smoother navigation icons (fixes #8167)(fixes #8168)

- package.json
- src/app/manager-dashboard/manager-dashboard.component.html
- src/app/manager-dashboard/manager-dashboard.component.ts
fixes #7893 
Moved the Delete Community button to the end of the list, made it red, and made the confirmation prompt a little more clear. We could in theory make the confirmation stronger, such as having a second dialog prompt, making them type out the community name, etc, but  I think this is an improvement for now.
> manager: smoother community delete warning (fixes #7893)

- package.json
- src/app/resources/resources-add.component.ts
- src/app/shared/forms/file-input.component.ts
fixes #8212
Long file name previews no longer overflow in the add/edit courses page.
> resources: smoother creation filename preview (fixes #8212)

- package.json
- src/app/exams/exams-add.component.ts
- src/app/surveys/surveys.component.html
- src/app/surveys/surveys.component.ts
Fixes #8186
Manage various access controls for the surveys:
**Teams**: community surveys can no longer be edited & deleted
**Admin**:  team surveys cannot be edited, deleted, sent or recorded
> teams: smoother surveys access managing (fixes #8186)

- package.json
- src/app/resources/resources-add.component.ts
- src/app/submissions/submissions.service.ts
- src/app/surveys/surveys.component.ts
Fixes #8229
Enhance the data boundaries of the teams and manager surveys
- `No of times taken` for teams only shows the times taken in teams
- In teams, can only export surveys data taken from teams
- In manager surveys, can view all the `no of times taken` and export all data
> teams: smoother surveys rights (fixes #8229) 

- package.json
- src/app/exams/exams-add.component.html
- src/app/exams/exams-add.scss
fixes #8242
Fixed an issue where placeholder text was overflowing the buttons. 
Gave the buttons consistent margins.
Put the required fields warning text on its own line for a cleaner look.
> teams: smoother surveys form layout (fixes #8242)

- package.json
- src/app/manager-dashboard/manager-dashboard.component.html
- src/app/manager-dashboard/manager-dashboard.component.ts
fixes #8244, #8247
Added some padding between the text and toggle.
Move the information icon next to the text, so it's clearer what it provides information about.
> manager: smoother chat streaming toggle (fixes #8244)(fixes #8247)

- package.json
- src/app/courses/add-courses/courses-add.component.ts
- src/app/shared/forms/planet-step-list.component.ts
fixes #8135
Making changes to any of the form fields, tags, or add/removing steps and then trying to navigate away via the cancel button results in a popup to let the user know there are unsaved changes. If the user navigates away via any other method (back button, refresh, nav bar, etc), the changes are saved anyway, so no popup is necessary.
> courses: smoother creation forms (fixes #8135)

- package.json
- src/app/app-router.module.ts
- src/app/community/community.component.html
- src/app/community/community.component.ts
- src/app/home/home-router.module.ts
- src/app/home/home.component.html
- src/app/home/home.component.ts
- src/app/resources/resources-add.component.ts
- src/app/shared/auth-guard.service.ts
- src/app/shared/beta-then-auth-guard-service.ts
- src/app/shared/user-guard.service.ts
- src/app/shared/user.service.ts
Makes the community page available to a not logged in client if the community is set to beta mode.
1. Set Planet to be in beta mode (advanced options in configuration).
2. Logout
3. Go to `localhost:3000` (or whatever your domain is)
Voices & Calendar can be viewed.
Images are not showing up in voices, this can be a follow up.
User menu in upper right is changed only have "Login" option in the dropdown. Could be a better UX to just have a login button. Also good for a follow up.
Fixes #8220
> community: smoother public access (fixes #8220)

- package.json
- src/app/courses/add-courses/courses-add.component.ts
- src/app/submissions/submissions.service.ts
Fixes #8282
More robust error catching and handling when exporting survey csvs and pdf
Initially the issue resulted from myPlanet survey submission data being added to the db via emulator so might be tricky to replicate.
Can manually be replicated by updating a submission doc and removing the questions array
> manager: smoother survey export (fixes #8282)

- package.json
- src/app/surveys/surveys.component.html
fixes #8268
When edit, send, record buttons are disabled due to teams/community permissions issues, a tooltip lets the user know why.
> manager: smoother surveys tooltips (fixes #8268)

- package.json
- src/app/meetups/add-meetups/meetups-add.component.ts
- src/app/shared/dialogs/dialogs-add-meetups.component.ts
fixes #8293
Navigation from the meetup input via browser, clicking away, or cancel button with unsaved changes in any of the text fields, times, or dates will result in a popup confirmation. Reverting changes stops it from popping up.
> community: smoother calendar forms (fixes #8293)

- package.json
- src/app/meetups/add-meetups/meetups-add.component.html
- src/app/meetups/add-meetups/meetups-add.component.ts
- src/app/meetups/view-meetups/meetups-view.component.html
fixes #8320
Links section can be blank, but if there content there, it is validated with the regex
> community: smoother calendar links (fixes #8320)

- package.json
- src/app/manager-dashboard/reports/logs-myplanet.component.ts
fixes #8343
The versions are listen in descending order, so we can more easily choose at the most recent one.
> manager: smoother myplanet logs filter versions (fixes #8343)

- package.json
- src/app/manager-dashboard/reports/logs-myplanet.component.ts
fixes #8349
Fixed an issue where, for example, version 0.22.59 was coming before 0.22.6 when sorting by version descending in the version dropdown.
> manager: smoother myplanet logs version dropdown (fixes #8349)

- package.json
- src/app/manager-dashboard/reports/logs-myplanet.component.ts
fixes #8370
This had broken again, so 0.22.59 was above 0.22.6 in version descending. Opted to just compare versions as strings for sorting.
> manager: smoother myplanet logs version dropdown (fixes #8370)

- package.json
- src/app/shared/forms/tags.service.ts
- src/app/submissions/submissions.component.ts
fixes #8367
Sorting submissions by name or courseTitle ignores leading whitespace.
Collections, which is alphabetical by default, ignores leading whitespace in its sorting.
> resources: smoother collections sorting (fixes #8367)

- package.json
- src/app/community/community.component.html
Updated the community to check whether the configuration is nation or community and accordingly made the changes to display the Nation Leaders label.
> community: smoother navigation leaders (fixes #8376)

- package.json
- src/app/courses/courses.component.html
Updated the courses file, like if the language is not set, it doesn't appear in the course information tab
> courses: smoother list language (fixes #8374)

- package.json
- src/app/shared/label.component.ts
fixes #8334, #8391
Fixed an issue where some disease labels were showing up as blank. 
Also fixes an issue where temperature range validator popup was missing label
> manager: smoother reports health (fixes #8334) (fixes #8391)

- package.json
- src/app/news/news-list-item.component.ts
- src/app/news/news.service.ts
fixes #8421, #8423
Edit dialog for a shared AI chat no longer populates with '< / br >'
Clearing the text for shared AI chat reflects immediately.
> teams: smoother voices editing (fixes #8421)(fixes #8423)

- package.json
- src/app/resources/resources-add.component.ts
fixes #8401 
https://github.com/user-attachments/assets/fea963a2-cc7c-4410-a5e4-155414923cdf
The File downloadable checkbox now works fine as the user deletes the attached pdf file.
> resources: smoother creation file downloadable (fixes #8401)

- package.json
- src/app/community/community.component.ts
- src/app/login/login-dialog.component.ts
- src/app/shared/auth-guard.service.ts
- src/app/shared/user.service.ts
Allows the login dialog to be closed. If the user was navigating directly to a guarded route via a pasted url, they will be redirected to the community page.
To test:
1. Open the community page in a logged out state.
2. Click a guarded link like resources.
3. Click out of the dialog to close.
4. Dialog should be closed
5. Paste a guarded route.
6. Click outside the login dialog.
7. Dialog should be closed and you should be routed to the community page.
>  login: smoother dialog closing (fixes #8389)

- package.json
- src/app/shared/authorized-roles.directive.ts
Fix for double icons showing up on the toolbar. Easiest way to test is to update your user profile and check if any toolbar icons have doubled.
Another testing option is to logout in another tab and go back to the original tab and log back in. Icons should not double.
Fixes #8427
> all: less navigation is more (fixes #8427)

- package.json
- src/app/users/users-profile/users-profile.component.html
- src/app/users/users-profile/users-profile.scss
fixes: #8441 
Aligned teams and enterprises cards list side by side, along with text wrapping for the names with slightly longer text.
> dashboard: smoother profile groups (fixes #8441)

- package.json
- src/app/users/users-profile/users-profile.component.html
fixes #8430
When viewing a profile as a dialog (e.g. from clicking the user icon in voices) and navigating to the team, the dialog closes upon navigation.
> community: smoother profile dialog closing (fixes #8430)

- package.json
- src/app/home/home.component.html
The sync button on the navbar now shows up again. It seems the `planetAuthorizedRoles` directive was not running correctly with no input.
I think it is a question if we want to restore this since it's been gone for so long, but I figured I would open this PR since it's such a small fix.
Fixes #8403 (or at least makes it irrelevant.)
> all: smoother navigation admin sync (fixes #8403)

- package.json
- src/app/submissions/submissions.service.ts
Fixes #8477
Improve formatting for exported pdfs
- Add an info page with the submission name, description(was previously getting cut off in the header) and no of submissions
- Simplify the question headers for more straightforward info
- Add more data to the submissions
- Improve overall formatting of Question - Response structure
Info page:
Page format:
> manager: smoother surveys export formating (fixes #8477)

- package.json
- src/app/configuration/configuration.component.html
- src/app/configuration/configuration.component.ts
Fixes #8487
Implement an autocomplete dropdown for the configurations language field
> manager: smoother configuration language dropdown (fixes #8487)

- package.json
- src/app/shared/auth-guard.service.ts
To test:
1. Go to community page in not logged in state
2. Click the calendar to try to create a meetup
3. When you see the login dialog, click outside to close it
4. You should not see the meetup dialog open
5. In the console, you should see a `Not authorized` error
fixes #8496
> community: smoother login dialog (fixes #8496)

- package.json
- src/app/teams/teams-member.component.html
- src/app/teams/teams-member.component.ts
- src/app/teams/teams-view.scss
fixes #8493
Added truncation to the members name. Made the cards a bit bigger to make room for an additional line of content.
> teams: smoother members card (fixes #8493)

- package.json
- src/app/exams/exams-view.component.html
fixes #8492
The exam info in the toolbar no longer shows premature inaccurate info. Now it waits for the data to load before showing it. 
[recording(7).webm](https://github.com/user-attachments/assets/ada16015-cda9-4f1d-8110-b6404c880794)
> courses: smoother exams navigation (fixes #8492)

- package.json
- src/app/manager-dashboard/reports/logs-myplanet.component.ts
- src/app/manager-dashboard/reports/reports-detail.component.ts
- src/app/manager-dashboard/reports/reports-myplanet.component.html
- src/app/manager-dashboard/reports/reports-myplanet.component.ts
- src/app/manager-dashboard/reports/reports.service.ts
fixes #8502
Added a dropdown menu for date filtering to match the other reports pages. Currently, All Time is the default range, but this can be adjust if something else makes more sense or is more convenient.
> manager: smoother myplanet reports date filtering (fixes #8502)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/courses.component.ts
- src/app/courses/courses.scss
- src/app/shared/planet-markdown.component.ts
- src/app/shared/planet-markdown.scss
- src/styles.scss
Fixes #8521
Improvements on the courses list
- Use mat table expansions instead of scrollbars & allow for more flexible table row length
- Upgrade planet markdown component to support new image gallery for preview mode in non-expanded mode
- While expanding using `img-resize` class for planet markdown as well as reduce image resizing to 25%
- Move the source info to the information column
https://github.com/user-attachments/assets/6ad467eb-0bf2-401e-9ae6-7b481af42e81
> courses: smoother list images preview (fixes #8521)

- package.json
- src/app/community/community.component.ts
fixes #8551 
It appears that sometimes in production the request for voices runs before the configuration is set on `stateService`. Since we are already fetching the configuraiton in `CommunityComponent`, we can use that configuration to make sure it is up to date.
> community: smoother voices loading (fixes #8551)

- package.json
- src/app/courses/courses.component.html
- src/app/courses/view-courses/courses-view-detail.component.html
fixes: #8522 
Now ff a language is not in the language list, we will not end up having a blank field.
> courses: smoother list data language (fixes #8522)

- package.json
- src/app/users/users-achievements/users-achievements.component.html
- src/app/users/users-achievements/users-achievements.component.ts
fixes #8557
The empty achievements is not clickable now. I also optimized the logic that the isclickable method will also test the link
https://github.com/user-attachments/assets/8400dff5-2738-48d3-af8b-923125c78d6c
> mylife: smoother achievements view (fixes #8557)

- package.json
- src/app/meetups/meetups.component.html
Fixes #8553 
Meetups list now renders correctly without the infinite looping
> teams: smoother calendar events list (fixes #8553)

- package.json
- src/app/submissions/submissions.service.ts
fixes #8570
When the chatapi is unavailable, such as when the container is not running, the error message is now more accurate.
> manager: smoother survey error message (fixes #8570)

- package.json
- src/app/community/community.component.ts
- src/app/news/news-list.component.ts
- src/app/news/news.service.ts
- src/app/users/users-achievements/users-achievements.component.ts
Fixes #8580
Main: Fix the **team** replies redirecting to the community voices.
- Should be able to view the voice reply in the teams
Sub issue: Improve **community voices** state management on url routing
- Should be able to switch community tabs and return to the reply voice which updates with the correct url
> teams: smoother voices replies (fixes #8580)

- package.json
- src/app/dashboard/dashboard-tile.component.html
- src/app/dashboard/dashboard-tile.component.ts
- src/app/dashboard/dashboard.component.spec.ts
- src/app/dashboard/dashboard.component.ts
- src/app/shared/user.service.ts
fixes #4653, #7884
Reordering tiles no longer gets reverted.
Navigation is briefly blocked while reordering to prevent accidentally navigating away.
> dashboard: smoother tile ordering (fixes #4653)(fixes #7884)

- package.json
- src/app/dashboard/dashboard-tile.scss
- src/app/users/users-achievements/users-achievements.component.ts
fixes #8577
If the very last tile in the dashboard is white, I added a subtle right border to prevent it from blending in with the background. 
The linter also prompted me to make this unrelated fix to users-achievements.
> dashboard: smoother tile visibility (fixes #8577)

- package.json
- src/app/shared/calendar.component.ts
Fixes #8624 
Better null checks for the community calendar events, particularly for myPlanet defined events
Currently tested directly on Planet Learning as a hot fix. Is tricky to test given it requires myPlanet generated events to trigger
> teams: smoother calendar events display (fixes #8624)

- package.json
- src/app/home/home.component.html
fixes #2398
Longer labels such as Manager Settings or any number of translated versions now truncate more gracefully via ellipsis.
> all: smoother navigation icon labels (fixes #2398)

- package.json
- src/app/teams/teams-view-finances.component.ts
- src/app/validators/custom-validators.ts
fixes #8637
You can now now add a $0 transaction, so the validation message is accurate. 
Note that a $0 transaction makes sense as a valid option, as it allows user to include a reminder, a placeholder, status update, etc in the books, in which case there is no associated dollar amount.
> enterprises: smoother finances transactions (fixes #8637)

- package.json
- src/app/resources/resources.component.html
- src/app/resources/resources.component.ts
- src/app/resources/resources.scss
fixes #8643
Formatted the levels, so there is space after the commas and they don't get cut off
> resources: smoother list details (fixes #8643)

- package.json
- src/app/news/news-list.component.ts
I went with a solution that fixes both #8671 and #8672 with one change.
The maximum number of posts viewed for each reply thread is stored in an object `pageEnd`. This means that while the user stays on the community page (or teams) the next time they go to that reply thread it will load up to that many posts.
In theory this could cause issues in load time if the user had opened a lot of posts in a reply thread and then returns to the reply thread.
It's also not ideal at this point for when the user looks at replies of an older post and then goes back to the main conversation. The older post will be rendered, but well below the scroll instead of in the users view.
> teams: smoother voices pagination (fixes #8671)(fixes #8672)

- package.json
Bumping the version on ramda to confirm the prebuild step is working as intended when merging into master.
Checking the upgrade guide for ramda none of the functions we use are mentioned when going from 0.28.0 -> 0.29.0
https://github.com/ramda/ramda/issues/3369
Functions we use
```
isEmpty
filter
pluck
head
```
> all: bump `ramda` to 0.29.0

- package.json
- src/app/submissions/submissions.service.ts
Fixes #8674
Normalize the data to handle cases where the parent.questions is not previosly defined.
> teams: smoother survey exports (fixes #8674)

- package.json
- src/app/meetups/view-meetups/meetups-view.component.html
- src/app/meetups/view-meetups/meetups-view.component.ts
- src/app/meetups/view-meetups/meetups-view.scss
- src/app/shared/calendar.component.ts
- src/app/tasks/tasks.service.ts
fixes #7971 and sub issues
- Can now edit and delete tasks directly from the teams calendar
- Tasks list is always ordered by deadline ascending. If deadlines are edited, list reorders immediately
- Improved formatting of edit/delete buttons in meetups/tasks dialog by pinning them to the top right
> teams: smoother tasks (fixes #7971)

- package.json
- src/app/community/community.component.html
- src/app/community/community.component.ts
- src/app/news/news-list.component.ts
When navigating with the browser back/forward on the community voices page the thread that you are viewing will now change.
To test create some voices posts with replies (and maybe replies of the replies). Click through to the different post threads to build up a browser history then use back/forward on the browser. The voices conversation being viewed should change with the browser navigation.
I tested it 2 replies deep.
> teams: smoother voices replies navigation (fixes #8670)

- package.json
- src/app/exams/exams-view.component.ts
- src/app/submissions/submissions.component.html
- src/app/submissions/submissions.service.ts
- src/app/surveys/surveys.component.ts
Fixes #8707
- Ensure only complete surveys are taken into consideration with the surveys count and displayed correctly in the submissions list
- Handle undefined exports of csv surveys missing the questions array
Difficult to replicate on local dev systems since issues are generated from myPlanet submissions.
Tested on [Planet Learning](https://planet.learning.ole.org)
> manager: smoother survey count (fixes #8707)

- package.json
- src/app/shared/dialogs/dialogs-images.component.html
- src/app/users/users-update/users-update.component.html
fixes #8800
Now when we upload images (from voices, profile, course description, anywhere there is an "add image" prompt), only  `/image` filetypes populate the dialog (jpg, png, webp, etc).
General file upload dialogs are unchanged
> all: smoother image uploads (fixes #8800)

- package.json
- src/app/exams/exams-view.component.html
- src/app/exams/exams-view.component.ts
- src/app/exams/exams-view.scss
Fixes #8798
Ensure we properly manage the state of the 'other' field to avoid question to question state leaks.
To test, use a survey with the `other` field enabled, test 2 consecutive choice questions of the same type and ensure the input doesn't persist in the next choice question
> teams: smoother survey choice other (fixes #8798)

- package.json
- src/app/submissions/submissions.service.ts
- src/app/surveys/surveys.component.ts
Fixes #8816
Surveys complete without the user details will be displayed correctly in the myDashboard/mySubmissions
> manager: smoother surveys submissions view (fixes #8816)

- package.json
- src/app/home/home.component.html
- src/app/home/home.component.ts
Fixes #8827
Improves the state of the icons across the home on login.
- Notification count displayed on login (via the community page)
- Manager Settings wheel & notification icons no longer visible on logout (also in the mobile sidebar)
> all: smoother icons permissions (fixes #8827)

- package.json
- src/app/users/users-update/users-update.component.html
- src/app/users/users-update/users-update.component.ts
Fixes #8837
Implement button to reset image selection
> dashboard: smoother profile image reset (fixes #8837)

- .gitignore
- README.md
- angular.json
- chatapi/README.md
- dev-env.sh
- docker/README.md
- package.json
- src/environments/environment.template
Fixes #8760
- Allow port selection in dev env
- Update the docker readme file
To test:
1. Ensure your dev chatapi is running(reference `/chatapi/README.md`)
2. Create a .env file in the planet root dir and set the `CHAT_PORT` variable. Ensure that the `CHAT_PORT` set in the .env is the same as the `SERVE_PORT`  in the `/chatapi/.env`.
Visit localhost:{{port}}/checkproviders to confirm
> chat: smoother dev port (fixes #8760)

- package.json
- src/app/home/home.component.html
- src/app/home/home.scss
- src/styles.scss
Fixes #8849
- Fix svg icon active color
- Add active state to bottom sidenav icons
> all: smoother active svg icon colors (fixes #8849)

- package.json
- src/app/courses/view-courses/courses-view-detail.component.ts
- src/app/courses/view-courses/courses-view.component.ts
- src/app/resources/view-resources/resources-view.component.ts
- src/app/shared/dialogs/dialogs-resources-viewer.component.ts
- src/app/teams/teams-view.component.ts
Fixes #8860
In the teams and enterprises, allow redirection from courses/resources view  after viewing course/resource
Steps to test:
- Go to teams, click on resources tab
- Select resource, the dialog opens and click `View resource`
- Click the back button in the resources view, you should be back in the team
Similarly test the courses and then the enterprises(documents & courses).
> teams: smoother courses linking (fixes #8860)

- angular.json
- package.json
- src/app/dashboard/dashboard.component.ts
fixes #8911
Adding the space around "my" grabs the singular version, which is what we want for myProgress.
> dashboard: smoother spanish translation (fixes #8911)

- package.json
- src/app/community/community.component.html
- src/app/community/community.component.ts
Fixes #8931
- Active voice reply persists even with switching between community tabs
- Hide the community board from display in the reply thread
> community: smoother voices reply (fixes #8931)

- package.json
- src/app/courses/add-courses/courses-add.component.html
- src/app/courses/add-courses/courses-add.component.ts
- src/app/courses/add-courses/courses-add.scss
- src/app/courses/add-courses/courses-step.component.ts
Fixes #8952
Improve the courses add/edit draft workflow. This is more intuitive for users & accomodates the unsaved changes dialog. Previously, changes were being auto saved.
> courses: smoother creation workflow (fixes #8952)

- package.json
- src/app/users/users-update/users-update.component.ts
fixes #8959
Unsaved changes guard no longer fires when submitting the user profile info
> teams: smoother survey submissions (fixes #8959)

- package.json
- src/app/teams/teams-member.component.html
- src/app/teams/teams-member.component.ts
fixes #8913
Added a bit of space between the avatar and the user name. Affects how it's displayed in Teams and Community Leaders. Had to truncate after 2 fewer characters to make room.
> teams: smoother member cards (fixes #8913)

- package.json
- src/i18n/messages.spa.xlf
fixes #8960
Fixed a mistranslation for the Last Upgrade header, which was also causing the boldness to go away.
> manager: smoother spanish translations (fixes #8960)

- package.json
- src/app/manager-dashboard/reports/logs-myplanet.component.html
- src/app/manager-dashboard/reports/logs-myplanet.component.ts
- src/app/manager-dashboard/reports/reports-myplanet.component.html
- src/app/manager-dashboard/reports/reports-myplanet.component.ts
Fixes #9022
The myplanet logs clear button now displays correctly -> When the selected option is not '24h'
- Remove old show all time and use new `defaultTimeFilter`
> manager: smoother reports navigation filter clearing (fixes #9022)

- package.json
- src/app/manager-dashboard/reports/reports-detail.component.ts
- src/app/shared/csv.service.ts
Fixes #9049
Add the `Voices Created` to the CSV summary export
> manager: smoother voices summary export (fixes #9049)

- package.json
- src/app/community/community.component.html
Fix #9095.
- Disabled the "Remove Description" button in community.component.html when team.description is empty or whitespace.
- Ensures button only enabled when a description exists.
Tested:
- Empty description → button disabled.
- Non-empty description → button enabled and works as expected.
> community: smoother services description removing (fixes #9095)
