open-learning-exchange/planet

src/app/courses/courses.service.ts, src/app/shared/user.service.ts
=> CoursesView: Fix error on refresh (fixes #5673)

src/app/community/community.component.ts, src/app/shared/shared-components.module.ts, src/app/tasks/tasks.component.html, src/app/tasks/tasks.component.ts, src/app/teams/teams-member.component.html, src/app/teams/teams-view.component.ts, src/app/teams/teams.service.ts
=> TeamsView: User member name message(fixes #5659)

src/app/teams/teams-view.component.html, src/app/teams/teams-view.scss
=> TeamsView: Teams card size resize (fixes #5565)

src/app/teams/teams-view.component.html
=> TeamsView: Full name for request(fixes #5682)

src/app/community/community.component.ts
=> Community: Change leader title (fixes #5679)

src/app/teams/teams-member.component.html, src/app/teams/teams-member.component.ts, src/app/teams/teams-view.component.html, src/app/teams/teams-view.component.ts, src/app/teams/teams.service.ts
=>  TeamsView: add role to member(fixes #5684)

src/app/teams/teams-view.component.html
=> TeamsView: Fix error if userDoc missing (fixes #5708)

src/app/teams/teams.service.ts
=> TeamsView: Fix error if team resource not found (fixes #5714)

src/app/submissions/submissions.service.ts
=> Survey: Spinner keeps on loading on empty reports(fixes #5669)

src/app/teams/teams.service.ts
=> Notification: use full name (fixes #5687)

src/app/community/community.component.html, src/app/community/community.component.ts
=> Community: Toggle disable on empty link (fixes #5614)

src/app/teams/teams-member.component.html, src/app/teams/teams-member.component.ts, src/app/teams/teams-view.component.ts
=> TeamsView: On empty role Add Role (fixes #5710)

src/app/teams/teams-view-finances.component.ts
=> 5672 edit header and message is now fixed (fixes #5672)

src/app/community/community-link-dialog.component.ts, src/app/community/community.component.html, src/app/community/community.component.ts
=> Community: Update UI for services & finances changes (fixes #5713)

src/app/news/news-list-item.component.html
=> NewsList: Member from another planet(fixes #5746)

src/app/surveys/surveys.component.html, src/app/surveys/surveys.component.ts
=> Surveys: Disable Export if no submission (fixes #5739)

src/app/community/community.component.ts
Issue: #5743 
Thanks for review in advance.
=> Community: Toggle mode to false when empty(fixes #5743)

src/app/manager-dashboard/manager-dashboard.component.html, src/app/manager-dashboard/manager-dashboard.component.ts
=> ManagerDashboard: Upgrade planet apk(fixes 5734)

src/app/teams/teams-view.component.html
=> TeamsView: Button to edit team(fixes #5761)

src/app/community/community-list-dialog.component.html, src/app/community/community-list-dialog.component.ts, src/app/community/community-list.component.html, src/app/community/community-list.component.ts, src/app/community/community.component.html, src/app/community/community.component.ts, src/app/home/home.module.ts, src/app/manager-dashboard/sync.directive.ts, src/app/news/news-list-item.component.ts, src/app/news/news-list.component.ts, src/app/news/news.module.ts, src/app/news/news.service.ts, src/app/shared/shared-components.module.ts
Allows sharing from a parent (nation, mainly) to child (community) planet.
=> News: Share from parent to child

src/app/resources/resources.component.ts
=> Resources: Space in search(fixes #5755)

src/app/community/community.component.ts
=> Services: Link delete mode(fixes #5771)

src/app/news/news-list-item.component.html, src/app/news/news-list-item.component.ts, src/app/news/news-list.component.html, src/app/news/news-list.component.ts
=> News Label: Remove functionality (fixes #5793)

src/app/courses/courses.service.ts, src/app/courses/step-view-courses/courses-step-view.component.ts
Docs in the `courses_progress` database should now be unique by `userId`, `courseId`, and `stepNum`
=> CoursesProgress: Fix duplicate docs (fixes #5293)

src/app/news/news-list-item.component.ts
=> News: Label list update after change (fixes #5814)

src/app/manager-dashboard/certifications/certifications-view.component.ts
=>  CertificationsView: Remove console log and few lines (fixes #5823)

src/app/manager-dashboard/certifications/certifications-add.component.ts
=> Certification: Success message in save (fixes #5819)

src/app/resources/resources-add.component.ts, src/app/resources/resources.service.ts
Issue #5073 
@paulbert , @lmmrssa please review. Thanks in advance.
=> New resource notification feature added (connects #5073)

src/app/courses/courses.component.html
=> Certification: Course valid link(fixes #5822)

src/app/community/community-list-dialog.component.html, src/app/community/community-list.component.html
=> Community: Pointer for share dialog(fixes #5791)

src/app/courses/step-view-courses/courses-step-view.component.html, src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/courses/view-courses/courses-view.component.html
=> CourseView: Re-take test (Fixes #5847)

src/app/logs-myplanet/logs-myplanet.component.ts, src/app/manager-dashboard/reports/myplanet-table.component.html, src/app/manager-dashboard/reports/myplanet-table.component.ts
=>  myPlanetTable: sorting fix in crash log(fixes #5843)

src/app/manager-dashboard/reports/reports-myplanet.component.ts
After making the issue I noticed there wasn't a nested subscription, but it is an observable nested in another.  Flattened this out so there isn't as much nesting.
=> ReportsMyPlanets: Refactor nested observables (fixes #5871)

src/app/manager-dashboard/certifications/certifications.component.html, src/app/manager-dashboard/certifications/certifications.component.ts
=> Added message for empty certifications (fixes #5818)

src/app/manager-dashboard/certifications/certifications.component.html, src/app/manager-dashboard/certifications/certifications.component.ts
=> Certifications: Certifications search by name(fixes #5860)

src/app/courses/view-courses/courses-view.component.html, src/app/courses/view-courses/courses-view.component.ts
=> CoursesViewComponent: retake test (fixes #5847)

src/app/courses/add-courses/courses-add.component.ts
=> CoursesAdd: Fix overwrite case (fixes #5884)

src/app/courses/courses.component.ts, src/app/manager-dashboard/certifications/certifications-view.component.html
=> CertificationView: checkbox in view page (fixes #5880)

src/app/manager-dashboard/certifications/certifications-view.component.ts
=> CertificationView: Self in Member list (fixes #5825)

src/app/courses/courses.component.ts, src/app/dashboard/dashboard-tile.component.ts, src/app/dashboard/dashboard.component.html, src/app/dashboard/dashboard.component.ts, src/app/health/health.component.ts, src/app/home/home-router.module.ts, src/app/news/news.component.html, src/app/resources/resources.component.ts, src/app/submissions/submissions.component.ts, src/app/teams/teams.component.html, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.component.ts, src/app/users/users-profile/users-profile.component.html, src/app/users/users-router.module.ts
=> myLife component redirects to dashboard (fixes #5865)

src/app/manager-dashboard/certifications/certifications-view.component.ts, src/app/manager-dashboard/certifications/certifications.service.ts, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.component.ts
#5901 
We can build on this towards how to show what the certification was (dialog, link, etc), but this is a start.
=> UsersAchievements: Show completed certifications (fixes #5901)

src/app/courses/courses.module.ts, src/app/courses/step-view-courses/courses-step-view.component.html, src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/exams/exams-preview.component.ts, src/app/exams/exams-view.component.html, src/app/exams/exams-view.component.ts, src/app/exams/exams.module.ts, src/app/shared/dialogs/dialogs-submissions.component.ts, src/app/shared/dialogs/dialogs-submissions.module.ts, src/app/submissions/submissions.component.html, src/app/submissions/submissions.component.ts, src/app/submissions/submissions.module.ts
#5897 
Adds a dialog to review the test attempts for a course step.
=> CourseStepView: Review test attempts (fixes #5897)

src/app/courses/view-courses/courses-view.component.html
=> CoursesView: No survey discription (fixes #5915)

src/app/manager-dashboard/certifications/certifications-add.component.html, src/app/manager-dashboard/certifications/certifications-add.component.ts
=> Remove Course button on cetifications-add page enabled only when course option is enabled (issue  #5820)

src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/courses/view-courses/courses-view.component.ts, src/app/exams/exams-view.component.html, src/app/exams/exams-view.component.ts, src/app/exams/exams-view.scss, src/app/submissions/submissions.service.ts
=> ExamsView: Finish Test button added (fixes #5910)

src/app/courses/courses.service.ts
#5921 
Now if a person takes an exam 2+ times and it is first graded passing, the second failing, the passing grade sticks and the person is still counted as completing that step.
=> Courses: Passed step remains passed (fixes #5921)

src/app/meetups/view-meetups/meetups-view.component.html, src/app/meetups/view-meetups/meetups-view.component.ts
=> Changed Task-username to link and direct to profile (fixes #5913)

src/app/shared/dialogs/dialogs-form.component.html, src/app/shared/dialogs/dialogs-form.component.ts, src/app/surveys/surveys.component.ts
=> Surveys: Remove vertical scrollbar (fixes #5742)

src/app/teams/teams-view.component.ts, src/app/teams/teams.component.ts, src/app/teams/teams.service.ts
=> TeamsView: Delete button deleting teams link. (fixes #5935)

src/app/teams/teams-view.component.html
=> TeamsView: Change Position of add course (fixes #5927)

src/app/teams/teams.service.ts
=> Community: Deleted link removed from nation (fixes #5956)

src/app/manager-dashboard/sync.directive.ts
Not the ideal solution, but the quick one.
Community news images send from nation to community require 2 syncs to replicate
1. First sync replicates the news post from the nation to community
2. Second sync will inspect that post and replicate any images included in the post
=> Community: Sync images from nation news

src/app/exams/exams-view.component.ts
=> ExamsView: Multiple choice submit resets (fixes #5959)

src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/shared/dialogs/dialogs-submissions.component.ts, src/app/submissions/submissions.component.ts
=> Submissions: Review attemps remove table column (fixes #5970)

package.json
Revert to an older version of the Angular builder (see https://github.com/angular/angular-cli/issues/17262)
=> Fix Angular build error

src/app/teams/teams-view.component.ts
=> Teams/Enterprise update message (fixes #5992)

src/app/submissions/submissions.service.ts
=> Survey: Completed survey notification link (fixes #5995)

src/app/courses/enroll-courses/courses-enroll.component.ts
=> CoursesEnroll: Community enrollment from nation (fixes #5975 fixes #5998)

src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports.service.ts, src/app/shared/csv.service.ts
Fixing issue we saw on Planet Somalia on Friday.  All resource views were attributed to the same resource in the community views.
=> ReportsDetail: Fix most visited resources

src/app/community/community.component.html, src/app/community/community.component.ts
=> Community Services: Add and Edit Community Description (Fixes #5904)

src/app/manager-dashboard/certifications/certifications-view.component.html, src/app/manager-dashboard/certifications/certifications-view.component.ts
=> CertificationsView: Enhancements(fixes  #5864)

src/app/dashboard/dashboard-tile-title.scss, src/app/dashboard/dashboard-tile.component.html, src/app/dashboard/dashboard-tile.component.ts, src/app/dashboard/dashboard-tile.scss, src/app/home/home.module.ts
=> DashboardTile: myLife link pointer (fixes #6017)

src/app/health/health.scss, src/app/manager-dashboard/certifications/certifications-view.component.html, src/app/meetups/view-meetups/meetups-view.scss, src/styles.scss
=> CertificationView: UI fixes (fixes #6014)

src/app/resources/resources.component.html
=> Resource: Change 'profile' to 'Filter' (fixes #6021)

src/app/courses/courses-router.module.ts, src/app/courses/progress-courses/courses-progress-learner.component.ts, src/app/dashboard/dashboard-tile.component.html, src/app/home/home-router.module.ts
=> myDashboard: myProgress redirects inconsistancy (fixes #6019)

src/app/teams/teams.component.html, src/app/teams/teams.component.ts
=> Teams: Reset filter (fixes #5905)

src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/courses/view-courses/courses-view.component.ts
=> Courses: Fix Continue Test not showing correctly (fixes #6051)

src/app/teams/teams.service.ts
=> Teams: Add teams plan (fixes #6037)

src/app/courses/view-courses/courses-view.component.ts
=> CoursesView: Fix step test button text (fixes #5958)

src/app/resources/resources.component.ts
=> Mypersonal empty error #6035

src/app/manager-dashboard/reports/reports-detail-activities.component.html, src/app/manager-dashboard/reports/reports-detail-activities.component.ts, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
=> ReportsDetail: Open dialog for resource view (fixes #5740)

src/app/submissions/submissions.service.ts
=> CoursesProgressLeader: Fix endless spinner if question skipped (fixes #6090)

src/app/exams/exams-view.component.html, src/app/exams/exams-view.component.ts, src/app/exams/exams.model.ts
A first starting point to write tests for surveys: Define exam objects for our reference and @leomaxi to follow.
=> Exams model

src/app/manager-dashboard/reports/reports-detail-data.ts, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports-detail.scss, src/app/manager-dashboard/reports/reports.service.ts, src/app/manager-dashboard/reports/reports.utils.ts, src/app/shared/csv.service.ts, src/styles.scss
=> ReportsDetail: Date filter (fixes #6086)

src/app/teams/teams-view.component.html
=> TeamsView: Vertical alignent of Request Pending (fixes #6087)

src/app/resources/resources.component.ts
=> Resources: Disable clear button (fixes #6020)

src/app/courses/view-courses/courses-view-detail.component.ts, src/app/courses/view-courses/courses-view-detail.module.ts, src/app/dashboard/dashboard.component.ts
#6052 
@paulbert , @lmmrssa please review the PR. Thanks!
=> Course badge dialog- Added View Course and Close Buttons (#6052)

src/app/community/community.component.html, src/app/community/community.component.ts, src/app/teams/teams-member.component.html, src/app/teams/teams-member.component.ts, src/app/teams/teams-view.component.html
=> Community Leader: Add/Change title (fixes #6073)

src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
=> report detail filter reset (connects #6115)

src/app/manager-dashboard/reports/reports-detail-activities.component.ts, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
=> ReportsDetail: Use dialog for course (fixes #6120)

src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
=> ReportsDetail: Back button to list (fixes #6124)

src/app/manager-dashboard/reports/reports-detail-data.ts
=> ReportsDetail: Fix end date not inclusive (fixes #6113)

src/app/news/news-list-item.scss, src/app/users/users-table.component.html, src/styles.scss
=> CoursesEnroll: Label in Planet list (fixes #6122)

src/app/resources/resources-add.component.ts
=> ResourcesAdd: Dialog init & no public to private (fixes #6103)

src/app/news/news-list-item.component.html, src/app/shared/planet-markdown.component.ts, src/app/shared/planet-markdown.scss
=> NewsListItem: Wrap text around images (fixes #6148)

src/app/courses/courses.component.ts
=> Courses: Number of courses deleted (fixes #6145)

src/app/manager-dashboard/manager.service.ts
=> ManagerDashboard: Total rating of last 30 days (fixes #6140)

src/app/resources/resources.component.ts
=> Resource: Single resource delete message (fixes #6144)

src/app/dashboard/dashboard.component.ts
=> Dashboard: No badges for empty course (fixes #6147)

src/app/health/health.component.html, src/app/health/health.component.ts
=> myHealth: Examination detail link (fixes #6159)

src/app/_variables.scss, src/app/health/health-event.component.html, src/app/health/health-update.scss, src/styles.scss
=> HealthEvent: Label for checkboxs(fixes #6166)

src/app/manager-dashboard/reports/reports.component.ts
#6183 
Note commit on this branch has wrong issue number
=> Reports: Fix Earth report list on Nation (fixes #6183)

src/app/manager-dashboard/manager.service.ts, src/app/manager-dashboard/reports/reports.component.ts, src/app/manager-dashboard/reports/reports.service.ts
=> Reports: Fix hub seeing children in list (fixes #6182)

src/app/health/health-event-dialog.component.html
=> Health: Show time in dialog (fixes #6164)

src/app/courses/view-courses/courses-view-detail.component.ts, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/teams/teams-view.component.html, src/app/teams/teams-view.component.ts
=> TeamsView: dialog in courses tab (fixes 6193)

src/app/health/health-event-dialog.component.ts
=> myHealth: Conditions sorted alphabetically (fixes #6190)

src/app/resources/resources.service.ts
=> ResourceAdd: Notification if not unread (fixes #6167)

src/app/health/health.constants.ts
=> Health: Add COVID-19 as condition (fixes #6207)

src/app/dashboard/dashboard.component.ts
=> Dashboard: Badges endless spinner (fixes #6228)

src/app/manager-dashboard/reports/reports-detail.component.ts
#6116
@lmmrssa, @paulbert please review the PR. Thanks!
=> Added fixes for showing member full names  for community reports on nation

docker/planet/default.conf, docker/planet/nginx/set_health_security.sh
#6211 
The script will run & get the database list, but it doesn't run anything in the `if [[ $DB =~ ^userdb- ]]; then` clause.  Will look into it later.  I have to call it a night.
=> Health: Userdb access script (fixes #6211)

src/app/community/community-link-dialog.component.html, src/app/community/community-link-dialog.component.ts
Fixes #5268
Add a cancel button for Add Link dialog form.
=> Add cancel button (fixes #5268)

src/app/login/login-form.component.ts, src/app/shared/dialogs/change-password.directive.ts, src/app/shared/forms/form-error-messages.component.ts, src/app/validators/custom-validators.ts
=> LoginForm: Do not allow space as password(fixes #6106)

src/app/health/health-event.component.html
fixes #6239 
Add the cancel button for the Add Examination page.
=> Add the cancel button (fixes #6239)

src/app/logs-myplanet/logs-myplanet.component.ts, src/app/manager-dashboard/reports/reports-myplanet.component.ts
fixes #5872 
Update error message.
=> Update error message (fixes #5872)

src/app/health/health-update.component.html, src/app/health/health-update.scss
fixes #6231 
Add the cancel button for the Update Details page.
=> Add cancel button (fixes #6231)

src/app/shared/dialogs/dialogs-form.component.html
=> DialogsForm: Rearrange buttons (fixes #6240)

src/app/health/health-event.component.ts
fixes #5297 
Remove ngOnInit and OnInit.
=> Remove ngOnInit and OnInit (fixes #5297)

src/app/health/health-event-dialog.component.html, src/app/health/health-event.component.html, src/app/health/health-event.component.ts, src/app/health/health.scss, src/app/shared/forms/form-error-messages.component.ts, src/app/shared/label.component.ts, src/app/validators/custom-validators.ts
=> myHealth: Unit for few elements(fixes #6158)

src/app/tasks/tasks.service.ts
=> Tasks: Completation date change on edit (fixes #6242)

package.json
Hope that #6257 is good to merge because that contains the change that bumps to 0.11
=> Version 0.11.0

src/app/tasks/tasks.component.html
=> TeamsView: Disable task checkbox for public team(fixes #6266)

src/app/shared/dialogs/dialogs-resources-viewer.component.ts, src/app/shared/dialogs/dialogs-resources-viewer.scss
Fixes #6250 
Remove the X icon, instead, add the **Close** button for consistency.
=> Add close button (fixes #6250)

src/app/health/health-event.component.ts, src/app/validators/custom-validators.ts
=> HealthEvent: Field with warning are not submitted (fixes #6261)

src/app/manager-dashboard/reports/reports-detail.component.html
=> ReportsDetail: Date filter only after minDate (fixes #6118)

src/app/shared/dialogs/dialogs-add-courses.component.html, src/app/shared/dialogs/dialogs-add-courses.component.ts, src/app/shared/dialogs/dialogs-add-resources.component.html, src/app/shared/dialogs/dialogs-add-resources.component.ts
#6268
@lmmrssa , @paulbert please review the PR. Thanks!
=> Teams/View- Enable/Disable AddResources/AddCourses dialog button based on selection (#6268)

src/app/shared/forms/planet-rating-stars.component.ts, src/app/shared/forms/planet-rating.component.ts
=> Reviews: Give rating by clicking in between stars(fixes #6269)

src/app/users/users-profile/users-profile.component.html
=> UsersProfile: Last login time included (fixes #6286)

src/app/health/health-update.component.html
=> myHealth: Subheding for emergency contact (fixes #6285)

src/app/shared/dialogs/dialogs-form.component.html
- vertical scroll bar is removed from all those where 'dialog-form-component' is being used.
Team,enterprise and so on
=> [#5989] remove vertical scrollbar

src/app/health/health.service.ts, src/app/manager-dashboard/manager-dashboard.module.ts, src/app/manager-dashboard/reports/reports-detail-activities.component.html, src/app/manager-dashboard/reports/reports-detail-activities.component.ts, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports-detail.scss, src/app/manager-dashboard/reports/reports-health.component.html, src/app/manager-dashboard/reports/reports-health.component.ts, src/app/manager-dashboard/reports/reports.service.ts, src/app/manager-dashboard/reports/reports.utils.ts, src/app/shared/label.component.ts
=> Reports: Add health section (fixes #6293)

src/app/health/health-event.component.html, src/app/health/health-update.component.html, src/app/users/users-update/users-update.component.html
Issues #6289 & #6309 
Fixed button spacing using reusable .action-buttons on containers
=> HealthUpdate & HealthEvent & UsersUpdate: Fix buttons spacing (Fixes #6289 and Fixes #6309)

src/app/manager-dashboard/certifications/certifications.component.html
Added i18n attribute to the tags that did not have one.
=> Add i18n attribute. Issue #6317

src/app/shared/dialogs/dialogs-form.component.html
=> Community: Fix extra scrollbar in add story dialog (fixes #6010)

src/app/manager-dashboard/certifications/certifications.component.html
Issue #5821 
Added a span element with cursor-pointer style class.
Hope this is a correct way to do a pull request. Sorry if I messed it up.
=> Add span element with class for styling. Issue #5821

src/app/meetups/view-meetups/meetups-view.component.html
=> TeamsView: Close button on event dialog(fixes #6312)

src/app/manager-dashboard/reports/reports-detail-data.ts, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports-health.component.ts, src/app/manager-dashboard/reports/reports.utils.ts
=> Reports: Refactor date filter end date inclusive (fixes #6305)

src/app/health/health-event.component.html, src/app/health/health-event.component.ts
Issue #6284 
Added validation to prevent temperature, blood pressure, height and weight from being 0.
=> Update input validation (fixes #6284)

design/security-update/security-update.json
=> Health: Add learner security to database (fixes #6349)

src/app/manager-dashboard/reports/reports-detail.component.html
Issue #6330
Applied structural directive  " *planetBeta "  to health reports tab on reports-detail-components.html.
=> Added *planetBeta to mat-tab health in reports. Issue #6330

src/app/configuration/migration.component.ts
@paulbert @lmmrssa could not do testing in development environment. So could you explain how to test migration.
=> [#6296] Userdb migration

src/app/news/news-list.component.html, src/app/news/news-list.component.ts
Fixes #6089 
Share button now can be seen after showing the replies if the main post has not been shared before.
=> Fix share button (fixes #6089)

src/app/health/health-event.component.ts, src/app/health/health.service.ts
#6332 
Adds age, gender and creatorId fields
=> Health: Add new event fields

src/app/exams/exams-view.component.ts
=> [#6363] test preview multiple choice value fixes

src/app/shared/dialogs/dialogs-list.component.ts, src/app/teams/teams-view.component.ts
Fixes #6371 
In the teams component: Allows search by username & full name
=> Teams: search by full name to add to teams (Fixes #6371)

src/app/shared/dialogs/dialogs-add-courses.component.html, src/app/shared/dialogs/dialogs-add-resources.component.html, src/app/shared/dialogs/dialogs-list.component.html, src/app/shared/dialogs/dialogs-prompt.component.html
Issue #6347
Updated button style in the following files:
1. DialogsListComponent
2. DialogsPromptComponent
3. DialogsAddCoursesComponent
4. DialogsAddResourcesComponent
=> Update button style. Issue #6347

src/app/news/news-list.component.ts
=> [#6361] news fixing console error

src/app/news/news-list-item.component.ts
Fixes #6342 
Remove notifications when replying to your own message.
=> Remove notifications (fixes #6342)

package.json, src/app/shared/forms/planet-round.directive.ts
issue: #6391
@paulbert i have implemented math.js library but i am unable to see its implementation for #6399. After we enter 22th place number or more round method returns NaN value.
=> Implementation of mathjs for for runding. (fixes #6391)

src/app/shared/forms/planet-rating-stars.component.ts, src/styles.scss
=> PlanetRating: Clicking between stars triggers rating (fixes #6301)

src/app/exams/exams-view.component.html
=> Disable radio on review (fixes #6366)

src/app/health/health-event.component.ts, src/app/shared/dialogs/dialogs-prompt.component.html
=> [#6400] show value in dialog

src/app/health/health-list.component.ts
#6410 #6367 #5284 
Looks like this also gracefully handles the error if the encryption key is incorrect
=> HealthList: Handle undefined events (fixes #6410 fixes #6367 fixes #5284)

src/app/manager-dashboard/reports/reports-detail.component.ts
=> ReportsDetail: Fix resources & courses export error (fixes #6407)

src/app/community/community-link-dialog.component.html, src/app/community/community-link-dialog.component.ts
=> Community: Service link title unique (fixes #5861)

src/app/meetups/add-meetups/meetups-add.component.html, src/app/meetups/add-meetups/meetups-add.component.ts
=> Update button spacing (fixes #6431)

src/app/manager-dashboard/reports/reports-detail.component.ts
fixes #6396 
The **Show All Time** button is disabled when the page loads.
=> disable show all time button (fixes #6396)

src/app/submissions/submissions.service.ts
=>  Surveys: Planet Name in exported pdf (fixes #6418) 

couchdb-setup.sh, src/app/users/users-update/users-update.component.ts
Issue: #6390 
@paulbert I am able to fix the problem of not updating until we logout and login but i am unable to update in myHealth UI for the first time until we reload the page. After first reload every update in Birthplace updates in myHealth UI.
=> myHealth: Birthplace field not updated until logout and login(fixes #6390)

src/app/notifications/notifications.component.html
Fixes #6310 
Adds time to notifications in the notifications component
=> Notifications: Add time for notifications (fixes #6310)

src/app/manager-dashboard/reports/reports-detail.component.ts
Issue #6395
Changed where the start date value is coming from, for exporting reports.
=>  Start date value in reports. Issue #6395

src/app/users/users-achievements/users-achievements-update.component.ts
=> AddAchievements: Reqired field sign added in UI(fixes #6432)

src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-health.component.html, src/app/manager-dashboard/reports/reports-health.component.ts, src/app/manager-dashboard/reports/reports.utils.ts
#6469 
Starts with simply COVID-19 by week.
=> ReportsHealth: Add trend chart (fixes #6469)

src/app/manager-dashboard/reports/reports.component.html, src/app/manager-dashboard/reports/reports.component.ts, src/app/manager-dashboard/reports/reports.utils.ts
looks like branch being there for a while without update so will do review of it
=> [#6189] View report detail of hub

src/app/news/news-list.component.ts, src/app/news/news.service.ts
=> Nation: No success message for empty news shared(fixes #6487)

src/app/manager-dashboard/reports/reports-health.component.html, src/app/manager-dashboard/reports/reports-health.component.ts
Fixes #6339 
Hides details when total examination is 0
=> Health report: Hides diagnoses details when exam is not in range 

src/app/health/health-event.component.ts, src/app/shared/dialogs/dialogs-prompt.component.html
Fixes #6341 
Capitalizes Ok & Cancel
=> Capitalize ok & Cancel (Fixes #6341)

src/app/shared/forms/planet-round.directive.ts
issue: #6457
Thanks for your review in advance. 
I have been experiencing few problem in this issue.
1. When I enter 17th place number digit it auto rounds.
2. When I enter 22th place number it converts into scientific notation number and I am unable to convert it into normal number.
=> myHealth: NaN is allowed in form submit (fixes #6457)

src/app/manager-dashboard/reports/reports-detail-activities.component.html, src/app/manager-dashboard/reports/reports-detail-activities.component.ts
fixes #6441 
Change the default sorting to descending for week dates.
=> Change default sorting (fixes #6441)

src/app/exams/exams-add.component.html, src/app/exams/exams-add.component.ts, src/app/exams/exams-preview.component.ts, src/app/exams/exams-view.component.ts
Fixes #5955 
Pass the examType Reference to the the setExamPreview function.
=> Pass the examType Reference to the the setExamPreview function. (Fixes #5955)

src/app/courses/courses.service.ts, src/app/courses/step-view-courses/courses-step-view.component.html, src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/courses/view-courses/courses-view.component.html, src/app/courses/view-courses/courses-view.component.ts, src/app/exams/exams-view.component.html
Issue #6398
Created functions to check when the preview menu needs to be displayed. To eliminate the unnecessary preview menu from showing up, when there is only survey or only test present.
=> Change preview UI behavior. Issue #6398

src/app/users/users.component.ts
=> Users: Search not working (fixes #6520)

src/app/manager-dashboard/reports/reports-health.component.ts, src/app/manager-dashboard/reports/reports.utils.ts
@paulbert, @lmmrssa please review. Thanks!
=> Added Reports health xaxis label(#6478

src/app/users/users-table.component.html, src/app/users/users-table.component.ts
fixes #6447
1. The "Action" column should not be there in the dialog.
2. The cursor should remain default on the image.
3. No roles should be changed in this view.
=> Change member table UI (fixes #6447)

src/app/users/users-table.component.ts, src/app/users/users.component.ts
#6554 
This one is a little broad, but want to make sure this is all working since the same table is used for sending surveys.
=> Users: Fix search community, admin, & clear (fixes #6554)

src/app/manager-dashboard/reports/reports-health.component.html, src/app/manager-dashboard/reports/reports-health.component.ts
=> Reports: Show/Hide empty diagnosis charts (Fixes #6507)

src/app/courses/progress-courses/courses-progress-leader.component.ts
#6524
@lmmrssa, @paulbert please review the PR. Thanks!
=> Changing Steps to Quest. on selecting step in View Test Progress(#6524)

src/app/health/health-event-dialog.component.html, src/app/health/health-event-dialog.component.ts, src/app/health/health-event.component.ts, src/app/health/health.component.html, src/app/health/health.component.ts, src/app/health/health.service.ts
Issue: #6514 
@paulbert i dont how what do do with UI in myHealth. I have added editable in header but there is sign for click here for detail too.
=> HealthEvent: Allow editing in health examination (fixes #6514)

src/app/community/community.component.html, src/app/teams/teams-view.component.html, src/app/teams/teams-view.scss, src/styles.scss
=> TeamsView: Tab body top margin (fixes #6501)

src/app/health/health-event-dialog.component.html, src/app/health/health-event-dialog.component.ts
Fixes #6515 
Provide the information about **Health Provider** if it is not a self examination.
=> Update provider info (fixes #6515)

src/app/health/health-event-dialog.component.html
=> HealthEventDialog: Edit button shows for 5 minutes only (fixes #6560)

src/app/health/health-event.component.ts
=> HealthEvent: Route away if exam is older than 5 min (fixes #6573)

src/app/manager-dashboard/reports/reports-health.component.ts
=> ReportsHealth: Handle conditions undefined (fixes #6519)

src/app/surveys/surveys.component.ts
=> Surveys: Exclude send member from dialog (fixes #6563)

src/app/health/health-event-dialog.component.ts
=> Health: Edit countdown resets after updating (fixes #6611)

src/app/teams/teams-view-finances.component.ts, src/app/teams/teams-view-finances.scss
Fixes #6566 
The PR only contains one of these four style changes.
=> Change style of total row(fixes #6566)

src/app/exams/exams-add.component.ts, src/app/exams/exams-view.component.ts, src/app/submissions/submissions.service.ts
=> Survey: Notification on update (fixes #6191)

src/app/manager-dashboard/reports/reports-detail-activities.component.html, src/app/manager-dashboard/reports/reports-detail-activities.component.ts, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports.service.ts
Calculated steps and exam from progress as we were already getting course detail there. If it needs to be separate function then let me know
=> [#6637] course report

src/app/courses/courses.component.ts, src/app/resources/resources.scss, src/styles.scss
=> Resources/Courses: Padding for long description overflow (fixes #6632)

src/app/health/health-event.component.ts
=> HealthEvent: Fix console error for new exam (fixes #6649)

src/app/users/users-profile/users-profile.component.ts
Fixes #6605 
Update the route after viewing a profile for teams in a non-admin user account
=> 6605 users profiles

src/app/health/health-event-dialog.component.html, src/app/health/health-event-dialog.component.ts
=> HealthEventDialog: Countdown for "Edit" (fixes #6571)

src/app/users/users-table.component.html, src/app/users/users-table.component.ts
#6516
@paulbert , @lmmrssa  please review the PR. Thanks!
=> Remove selectbox for non-admin members(#6516)

src/app/shared/dialogs/dialogs-ratings.component.html
=> DialogsRatings: Show date of rating (fixes #6625)

src/app/shared/dialogs/dialogs-add-table.component.ts, src/app/surveys/surveys.component.ts, src/app/teams/teams-view.component.ts, src/app/users/users-table.component.html, src/app/users/users-table.component.ts, src/app/users/users.component.ts
=> UsersTable: Fix selection when parent has same id (fixes #6643)

src/app/teams/teams-member.component.html, src/app/teams/teams-view.component.html, src/app/teams/teams-view.component.ts, src/app/teams/teams.utils.ts
=> TeamsView: Fix nation/community same userId (fixes #6061)

src/app/meetups/add-meetups/meetups-add.component.html
changed style of buttons on add event page to stay consistent with other pages.
fixes issue #6504
=> changed style of buttons

src/app/users/users-update/users-update.component.ts
=> UsersUpdate: Record Survey's update link (fixes #6628)

src/app/health/health-event.component.html, src/app/health/health-update.scss
Fixes #6657 
Remove redundant vertical scrollbar
=> Remove repeated scrollbar (fixes #6657)

src/app/dashboard/dashboard-tile.component.html
=> myDashboard: Tooltip in close button for more clarity (fixes #6702)

src/app/community/community.component.ts
#6542
@paulbert , @lmmrssa please review the PR. Thanks!
=> Success Message updated based on Community leaders title is added/updated/deleted #6542

src/app/news/news-list-item.component.html, src/app/news/news-list-item.component.ts, src/app/teams/teams-view.component.html, src/app/teams/teams-view.component.ts
=> Teams: Add profile link

src/app/shared/dialogs/dialogs-ratings.component.html, src/app/shared/dialogs/dialogs-ratings.component.ts
=>  DialogsRatings: Obtion for sorting rating (fixs #6692) 

src/app/health/health.constants.ts
**Issues:** #6636
**Description:**
The PR added Trauma to condition list
**Image:**
=> 6636-Trauma-to-conditions-list fixes #6636

src/app/health/health.service.ts
#6663 
This won't fix adding the error into the database, but it should help prevent the error from occurring in the first place.
=> HealthEvent: Fix adding two keys with self exam (connects #6663)

src/app/health/health-event-dialog.component.ts
=> [#6700] examination timer update

src/app/community/community.component.html, src/app/community/community.component.ts, src/app/community/community.scss
=> 6703 calendar tab

src/app/health/health-update.component.html, src/app/health/health-update.component.ts, src/app/shared/user.service.ts, src/app/users/users-achievements/users-achievements-update.component.html, src/app/users/users-achievements/users-achievements-update.component.ts, src/app/users/users-update/users-update.component.html, src/app/users/users-update/users-update.component.ts
**Issues:** #6508
**Description:**
User can no longer choose a date lower than 1/1/1900 in myHealth update datails dialog
**Image:**
=> myHealth-birthdate fixes #6508

src/app/users/users-profile/users-profile.component.html
#6732 
Show username and gender in the **Member Profile** dialog box.
=> Show user info in dialog (fixes #6732)

src/app/teams/teams-view-finances.component.ts, src/app/teams/teams-view.component.ts
=> Enterprises: Finance not showing negative balance

src/app/courses/view-courses/courses-view.component.html, src/app/courses/view-courses/courses-view.component.ts
=> CoursesView: Fix Take Test disabled condition (fixes #6565)

src/app/shared/label.component.ts
=> Health: Trauma is missing from Diagnoses table(fixes #6723)

src/app/manager-dashboard/reports/reports-detail-data.ts, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
issue: #6731 
@paulbert Can you review once. I am stuck in filter and don't know if i am suppose to do filter in  ReportDetailFilter component.
=> ReportsDetail: Filter by team (fixes #6731)

src/app/login/login.component.html, src/app/login/login.scss
=> Login: Add link to myplanet on Play Store(fixes #6699)

src/app/feedback/feedback.component.ts
=> Feedback: Remove chip transitions

src/app/manager-dashboard/reports/reports-detail.component.ts
=> ReportsDetail: Fix member filter not appearing (fixes #6788)

src/app/courses/add-courses/courses-add.component.ts
=> CoursesAdd: Fix back button error (fixes #6806)

src/app/shared/dialogs/dialogs-submissions.component.ts, src/app/submissions/submissions.component.html, src/app/submissions/submissions.component.ts
issue #6795 
Under what component is the view shown when clicking Review Submissions?
=> 6795 add graded date column in my submissions

src/app/teams/teams-view.component.ts, src/app/teams/teams.utils.ts
Fixes #6754 
Members are sorted alphabetically except for the **Team Leader**.
=> Sort members alphabetically (fixes #6754)

src/app/tasks/tasks.component.html, src/app/tasks/tasks.component.ts
=> TeamsView: Task assignee UserProfileDialog (fixes #6792)

src/app/shared/dialogs/dialogs-submissions.component.ts, src/app/submissions/submissions.component.html, src/app/submissions/submissions.component.ts
=> 6766 submission grade

src/app/community/community.component.ts
=> Comunity Leaders: Leaders from Nation shows up in community. (fixes #6695)

src/app/courses/courses.service.ts
=> CoursesAdd: Fix error on init (fixes #6832)

src/app/courses/courses.component.html, src/app/courses/courses.component.ts, src/app/teams/teams.service.ts
Issue #6763 
Was not able to use similar code ([disabled]="isDialog || isForm) to disable the button in HTML. Kept getting an error “Can't bind to 'disabled' since it isn't a known property of ...”
Found an example on stack overflow to make it work, since only html tags that have actions, could be disabled.
=> Add conditional statement to class. Issue #6763

src/app/submissions/submissions.component.ts
=> Submissions: Fix object references (fixes #6827)

src/app/shared/sync.service.ts
=>  Courses: Replicate images resources (fixes #6829) 

src/app/feedback/feedback.component.html, src/app/feedback/feedback.component.ts, src/app/news/news-list-item.component.html, src/app/submissions/submissions.component.html, src/app/teams/teams-view.component.html, src/app/users/users-table.component.html, src/styles.scss
=> Styles: Add class to remove mat-chip styles

src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports.service.ts
=> ReportsDetails: Update member count when member filter active(fixes #6783)

src/app/shared/calendar.component.ts
Fixes #6814 
Show dates without any events or tasks.
=> Show dates (fixes #6814)

src/app/courses/add-courses/courses-add.component.ts
=> CoursesAdd: Fix recently saved course cached as new (fixes #6157)

src/app/courses/enroll-courses/courses-enroll.component.ts, src/app/users/users-table.component.html
=> EnrolledList: Error loading enroll list in certain courses. (fixes #6784)

src/app/users/users-profile/users-profile-dialog.component.ts
Fixes #6740 
Add a button to allow admins to go to the members' list in manager settings.
=> Add admin button to go to members' list in manager settings (Fixes #6740)

src/app/meetups/view-meetups/meetups-view.component.html, src/app/meetups/view-meetups/meetups-view.component.ts
=> MeetupsView: Use UserProfileDialog (fixes #6845)

src/app/manager-dashboard/certifications/certifications-view.component.html
=> [#6782] add ellipsis to lengthy certification title

src/app/courses/courses.service.ts, src/app/submissions/submissions.component.ts
Fixes #6816 
Still has a routing problem. Click on a survey and go back, the page goes to **Tests** submissions.
=> Fix initial columns (fixes #6816)

src/app/manager-dashboard/reports/reports-detail.component.ts
=> ReportsDetail: Filter members for count correction(fixes #6849)

src/app/courses/courses.component.html, src/app/shared/planet-markdown.component.ts
=> Courses: View parent images in local (fixes #6846)

src/app/exams/exams-view.component.ts
Fixes #6789 
Fix the loading issue when previewing a survey/test.
=> Fix preview loading issue (fixes 6789)

src/app/shared/dialogs/dialogs-images.component.html
Fixes #6848 
Add header for the image dialogs.
=> Add image dialogs header (fixes #6848)

src/app/meetups/add-meetups/meetups-add.component.ts, src/app/meetups/view-meetups/meetups-view.component.html
=>  AddMeetups: Add sourcePlanet field for opening user profile dialog (fixes #6877)

src/app/courses/add-courses/courses-add.component.html, src/app/courses/add-courses/courses-add.component.ts
=> Courses: Add autocomplete for language (fixes #6847)

src/app/manager-dashboard/reports/reports-health.component.html, src/app/manager-dashboard/reports/reports-health.component.ts
=> HealthReport: Diagnosis trend reverts to COVID selected after changing time filter(fixes #6888)

src/app/courses/view-courses/courses-view-detail.component.html, src/app/courses/view-courses/courses-view-detail.component.ts, src/app/courses/view-courses/courses-view.component.html
=> CoursesView: View parent images in local (fixes #6846)

src/app/users/users-profile/users-profile-dialog.component.ts
=> UsersProfileDialog: Open profile button routes to own profile (fixes #6885)

src/app/users/users-profile/users-profile.component.ts
=> UsersProfile: Fix edit first admin information (fixes #6921)

src/app/shared/dialogs/dialogs-prompt.component.html
=> DialogsPrompt: Fix console error when opening (fixes #6925)

src/app/shared/couchdb.service.ts, src/app/teams/teams-reports.component.html, src/app/teams/teams-reports.component.ts, src/app/teams/teams.service.ts
=> TeamsReports: UTC dates -> no time zone switches (fixes #6934)

src/app/teams/teams-reports.component.ts
=> TeamsReports: Initialize start & end date to last month (fixes #6909)

src/app/teams/teams-reports.component.ts
=> TeamsReports: Fix deletion (fixes #6913)

src/app/meetups/view-meetups/meetups-view.component.ts, src/app/users/users-profile/users-profile-dialog.component.ts
=> MeetupsView: meetup dialog removed from View profile ( fixes #6887)

src/app/teams/teams-reports.component.ts
=> Enterprise- Add Report: Show asterisk for required fields (fixes #6915)

src/app/teams/teams-reports.component.ts
=> Enterprises Add Report: Disable submit until form is valid (fixes #6919)

src/app/shared/couchdb.service.ts, src/app/teams/teams-reports-dialog.component.html
sorry @paulbert looks like its duplicate
=> [#6953] UTC time for report

src/app/teams/teams-view.component.ts
=> TeamsReports: Switch sort direction (fixes #6962)

src/app/teams/teams-reports.component.ts, src/app/teams/teams.utils.ts
=> TeamsReports: Fix dates when edit existing (fixes #6963)

src/app/shared/dialogs/dialogs-form.component.html, src/app/teams/teams-reports.component.ts
=> Enterprise Reports: Validate number fields

src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
Fixes #6883 
Work in progress
Fix member counts on **Report Detail** page
=> ReportsDetail: Fix member count on load (fixes #6883)

src/app/teams/teams-reports.component.ts
=> TeamsReports: Fix end date before start validation (fixes #6912)

src/app/courses/courses.service.ts, src/app/courses/view-courses/courses-view.component.ts
=> CoursesView: Leave/join doesn't work after refresh

src/app/dashboard/dashboard.component.ts
=> myDashboard: Update middlename for fullname (fixes #6891)

src/app/shared/forms/planet-tag-input.component.ts, src/app/shared/forms/tags.service.ts
=> Collections: Update count based on filter

src/app/teams/teams-reports-detail.component.html
=> TeamsReports: Add created & updated date (fixes #6971)

src/app/shared/dialogs/dialogs-prompt.component.html, src/app/shared/dialogs/dialogs-prompt.component.ts, src/app/teams/teams-reports.component.ts
=> TeamsReports: Show correct dates in delete dialog (fixes #6974)

src/app/shared/csv.service.ts, src/app/teams/teams-reports.component.html, src/app/teams/teams-reports.component.ts
=> TeamsReports: Export data to CSV (fixes #6970)

src/app/teams/teams-reports-detail.component.html, src/app/teams/teams-reports-detail.component.ts, src/app/teams/teams-reports-dialog.component.html, src/app/teams/teams-reports.component.html, src/app/teams/teams-reports.component.ts, src/app/teams/teams-view.component.html
=> TeamsReports: Update layout (fixes #6969)

src/app/courses/courses.component.html, src/app/courses/courses.component.ts
=> CertificationsView: Use Courses dialog (fixes #6756)

src/app/community/community.component.html, src/app/community/community.component.ts, src/app/teams/teams.module.ts
=> Community: Add financial reports section (fixes #6978)

src/app/teams/teams-reports.component.html, src/app/teams/teams-reports.component.ts
=> TeamsReports: Dynamic number of columns (fixes #6972)

src/app/courses/courses.service.ts, src/app/courses/view-courses/courses-view-detail.component.html, src/app/courses/view-courses/courses-view-detail.component.ts
**Issues:** #6769
**Description:**
The PR is intended to add creator name and planet name (source) in course detail page,  I don't know why user-detail is not available in the view after binding
=> 6769 creator and planet name fixes #6769

src/app/courses/progress-courses/courses-progress-chart.component.html, src/app/courses/progress-courses/courses-progress-chart.component.ts, src/app/courses/progress-courses/courses-progress-leader.component.html, src/app/courses/progress-courses/courses-progress-leader.component.ts
=> CoursesProgress: Use UserProfileDialog

src/app/shared/dialogs/dialogs-images.component.ts, src/app/shared/forms/planet-markdown-textbox.component.ts
Issue #6852
Show alert, when user tries to add the same image( an image with the same name) to a course, when creating a new course.
=> Add warning that an image with that name, has been already added. Issue #6852

src/app/courses/progress-courses/courses-progress-chart.component.html, src/app/courses/progress-courses/courses-progress-chart.component.ts, src/app/courses/progress-courses/courses-progress-leader.component.html
=> CoursesProgressLearner: Remove avatar (fixes #6994)

.github/workflows/planet-db.yml
Co-authored-by: RJ Padilla <rjpadilla.dev@outlook.com>
=> update db-init workflow

src/app/manager-dashboard/certifications/certifications-add.component.ts, src/app/news/news-list-item.component.ts, src/app/shared/calendar.component.ts
Add locales to the Calendar component
=> localize calendar (fixes #7082)

src/app/users/users-profile/users-profile.component.html, src/app/users/users-profile/users-profile.component.ts, src/app/users/users-profile/users-profile.scss
Fixes #7121 
Create a stylesheet
Add a media query to change the grid to 2 rows and 2 columns for smaller screens
=> responsive profile (fixes #7121)

src/app/resources/view-resources/resources-view.scss
Fixes #7122 
Adding media query to change the grid style for mobile screens
=> responsive resource view

src/app/courses/add-courses/courses-add.scss
Fixes #7133 
Make the add/edit course page responsive
=> responsive course edit (#7134) (fixes #7133)

src/app/resources/resources-add.scss
Fixes #7131 
Make the add/edit resource responsive
=> responsive resource edit (#7132) (fixes #7131)

src/app/users/users-update/users-update.component.html, src/app/users/users-update/users-update.component.ts, src/app/users/users-update/users-update.scss
Fixes #7125 
- Reduce spaces in the user profile edit section using the grid to reposition the elements for smaller screens
- Create stylesheet for user profile edit page
=> responsive user profile edit (#7128) (fixes #7125)

src/app/courses/view-courses/courses-view.scss
Fixes #7129 
Responsiveness for the Courses View with the details placed below the main view
=> Responsive Course View

src/app/community/community.component.html, src/app/community/community.component.ts
Fix for the calendar to display within tabs on mobile screens in the community component.
`On hold pending Landing Page component implementation`
=> Community: Calendar loading within tab - mobile

src/app/community/community.scss
=> community: improve adaptive rendering (fixes #7156)

src/app/courses/progress-courses/courses-progress-leader.component.html, src/app/courses/progress-courses/courses-progress-leader.component.ts
=> courses: export progress button added (fixes #7140)

package.json, src/app/dashboard/dashboard.component.ts
Fixes #7167 
Take note of #4714
=> dashboard: add enterprises in myTeams list (fixes #7167)

package.json, src/app/landing/landing-hero/landing-hero.component.ts, src/app/shared/dialogs/dialogs-video.component.ts, src/app/shared/dialogs/planet-dialogs.module.ts
Allows landing video to play.
Fixes #7175
=> add video dialog component for custom landing page (fixes #7175)

.github/workflows/planet.yml, docker/volumes.yml
=> login: external mounting of large landing video (fixes #7178)

docker/planet/scripts/create_version_json.sh, package.json
Fixes #7202
- add latest and min apk versions to the package.json
- dynamically update the create_version script
=> add myPlanet versions to `package.json` (fixes #7202)

src/app/landing/landing.component.html, src/app/landing/landing.component.ts
- Delete `landing.component.html`
- Move template to the .ts file
=> landing: refactor template (fixes #3175)(fixes #3176)

src/app/shared/planet-filtered-amount.component.ts, src/app/teams/teams.component.html
#7220
- Teams/Enterprises: Display request pending text 
- Courses/Resources: Add spacing in filtered course/resource amounts
=> courses: adding a space in header (fixes #7220)

package.json, src/app/chat/chat.component.html, src/app/chat/chat.component.ts
#7205 
Improved formatting of line breaks & code blocks
=> chat: markdown enabled (fixes #7205)

package.json, src/app/chat/chat.component.html, src/app/chat/chat.component.scss, src/app/chat/chat.component.ts
Fixes #7224 
Improvements to the current chat UI
=> chat: UI update (fixes #7224)

package.json, src/app/chat/chat.component.ts
Fixes #7229 
- Stop spinner on error response in the chat
- Remove console message
=> chat: stop spinner on error response

package.json, src/app/chat/chat.component.ts
=> chat: remove unusused messages variable (fixes #7238)

package.json, src/app/users/users-update/users-update.component.html, src/app/users/users-update/users-update.scss
=> profile: improve form layout (fixes #7248)

package.json, src/app/chat/chat.component.html, src/app/chat/chat.component.ts, src/app/shared/chat-format.directive.ts, src/app/shared/chat-output.directive.ts, src/app/shared/shared-components.module.ts
Move the sanitizeText function from the chat component to a directed for shared use(with courses rating & other chat interfaces/output)
=> chat: implement formatting directive (fixes #7242)

package.json, src/app/courses/courses.component.html, src/app/courses/courses.component.ts, src/app/courses/courses.scss
Make courses table responsive for mobile views
=> courses: refactor towards more responsiveness (fixes #7165)

package.json, src/app/resources/resources.component.html, src/app/resources/resources.scss
Implement responsive view for the courses table  list.
=> resources: more responsive mobile view (fixes #7163)

package.json, src/app/users/users-profile/users-profile.component.html
Fixes #7251 
sets the gender value to lowercase so that the proper svg icon can be referenced.
=> profile: fix icon rendering (fixes #7251)

package.json, src/app/resources/resources.component.html, src/app/resources/resources.component.ts
Fixes #7263 
The manager actions button is cutoff for 1000-1040px.
Handling this edge case from the normal `device-info.service.ts`
=> resources: more responsive toolbar (Fixes #7263)

package.json, src/app/courses/add-courses/courses-add.scss, src/app/shared/forms/planet-step-list.scss
Fixes #7265
- Responsive page layout
- Display the courses steps/steps form below the main form.
- Button alignment
=> courses: more responsive creation page (fixes #7265)

package.json, src/app/dashboard/dashboard-tile.component.html
Fixes #7268
- Add myChat to myDashboard
- Rename My Progress to myProgress
=> home: add myChat link in myLibrary box (fixes #7268)

.github/workflows/deploy.yml, .github/workflows/planet-chat.yml, .github/workflows/planet-db.yml, .github/workflows/planet.yml, package.json
=> actions: bump `actions/checkout` to 4 (fixes #7275)

package.json, src/app/courses/add-courses/courses-add.scss, src/app/courses/courses.component.html, src/app/courses/progress-courses/courses-progress-learner.component.html, src/app/courses/view-courses/courses-view.component.html, src/app/resources/resources-add.scss
Fixes #7274 
- update myProgress text
- remove redundant styles from courses and resources add scss
=> courses: camelcasing myProgress (fixes #7274)

package.json, src/app/dashboard/dashboard.component.html, src/app/dashboard/dashboard.component.ts, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/teams/teams-view.component.ts
Make various courses-view dialogs scrollable with the introduction of the **maxHeight** value
=> courses: new height handling in view dialog (fixes #7278)

package.json, src/app/community/community.component.html, src/app/community/community.component.ts, src/app/community/community.scss, src/app/news/news-list-item.component.ts
Fixes #7294
- Change the news to voices
- Shrink the calendar grid item
- Update the calendar toolbar layout for all dimensions.
Old view
Updated view
=> community: change news to voices (fixes #7294)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.component.ts, src/app/chat/chat-sidebar/chat-sidebar.scss
Fixes #7301
- Make chat titles editable
=> chat: editable titles (fixes #7301)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.ts, src/app/chat/chat-window/chat-window.component.ts, src/app/chat/chat.component.ts
Fixes #7305
- Proper cleanup for subscriptions in the chat-sidebar and chat-window components
- Remove unused onInit in the chat component
=> chat: subscription refactor (fixes #7305)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.component.ts
Fixes #7299
- Implement the search functionality for the chat 
- Record the searches in the search_activities database
=> chat: search functionality (fixes #7299)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.component.ts
Fixes #7315 
- Add the option to use full-text search in the chat search
- Remove the conversations h3
=> chat: add full text search (fixes #7315)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.scss, src/app/chat/chat-window/chat-window.component.html, src/app/chat/chat-window/chat-window.scss, src/app/chat/chat.component.html, src/app/chat/chat.scss
Fixes #7317 
- Update the UI of the chat i.e form container & space container
- Make the sidebar new chat button and search sticky at the top
- Remove space container margin spacing
- General refactor of the chat styling code
Old View:
Updated View:
=> chat: better space usage (fixes #7317)

package.json, src/app/community/community.component.html, src/app/community/community.scss, src/app/news/news-list-item.component.html, src/app/news/news-list-item.component.ts, src/app/news/news-list-item.scss, src/app/news/news-list.component.ts
Fixes #7323 
- Inital message is displayed in full
- New voice button aligned to the right
- ~~News~~  -> Our Voices
- configuration name + Community
=> community: improve news (fixes #7323)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.component.ts, src/app/chat/chat-window/chat-window.component.ts
Fixes #7329 
- Reverse the chat list ordering
- Fix the chats not automatically appearing
- Remove the search using initial query as a result of #7328
=> chat: last chat first chat (fixes #7329)

chatapi/src/models/db-doc.model.ts, chatapi/src/services/chat.service.ts, chatapi/src/utils/db.utils.ts
Fixes #7328 
Set the title in the chatapi for whenever a new chat is created
=> chat: set title initialization (fixes #7328)

package.json, src/app/resources/search-resources/resources-search.component.ts
Fixes #7357
Display the media label
=> resources: improve medium filter (fixes #7357)

package.json, src/app/home/home.component.ts, src/app/shared/user.service.ts, src/app/users/users-archive/users-archive.component.html, src/app/users/users-archive/users-archive.component.ts, src/app/users/users-router.module.ts, src/app/users/users.module.ts
Fixes #7360 
Add a data deletion form to support users requests for data deletion.
=> users: data deletion form (fixes #7360)

chatapi/src/models/db-doc.model.ts, chatapi/src/services/chat.service.ts, chatapi/src/utils/db.utils.ts, package.json, src/app/chat/chat-sidebar/chat-sidebar.component.ts, src/app/chat/chat-window/chat-window.component.ts
Fixes #7369 
For the chat fix the timestamps being properly updated in the db.
=> chat: timestamps saved (fixes #7369)

package.json, src/app/meetups/add-meetups/meetups-add.component.ts
Fixes #7371
Properly initialize the event form during update mode.
=> community: better event update form (fixes #7371)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.component.ts, src/app/chat/chat-sidebar/chat-sidebar.scss
Fixes #7366 
- Have the sidebar open by default for tablets & desktops
- Update the new chat button styling
=> chat: sidebar open by default (fixes #7366)

package.json, src/app/community/community.component.html
Fixes #7377
Fix the community page rendering during tablet mode
=> community: better tablet mode (fixes #7377)

chatapi/src/index.ts, chatapi/src/services/chat.service.ts, package.json
Fixes #7391
Within the API improve the error handling for:
- Empty data object
- Data object is an array
- Content field within data object is empty or not a string
=> chat: better error handling (fixes #7391)

package.json, src/app/courses/courses.component.html, src/app/courses/courses.component.ts
Fixes #7386
Add language filtering for the courses
=> courses: add language filtering (fixes #7386)

package.json, src/app/login/login-form.component.ts
Fixes #7380 
Restrict access for archived users & throw an error.
Note: Username will be locked i.e unable to create a new user with that username.
=> login: restrict archived users (fixes #7380)

chatapi/src/services/chat.service.ts, package.json
Fixes #7393 
Non-string content field in json data object leads to the error with API processing.
=> chat: better error handling (fixes #7393)

package.json, src/app/chat/chat-window/chat-window.scss
Fixes #7395
- Change the dynamic height sizing of the chat window
- Remove some chat-window styles
=> chat: better window styles (fixes #7395)

package.json, src/app/shared/auth-guard.service.ts, src/app/shared/couchdb.service.ts, src/app/shared/dialogs/dialogs-list.service.ts, src/app/shared/dialogs/dialogs-loading.component.ts, src/app/shared/dialogs/planet-dialogs.module.ts, src/app/shared/forms/form-error-messages.component.spec.ts, src/app/shared/forms/planet-selector.component.ts, src/app/shared/forms/planet-step-list.component.ts, src/app/shared/forms/tags.service.ts, src/app/shared/state.service.ts
Fixes #7399
Cleanup the shared components
- Remove unused imports
- Remove empty constructors and unreferenced files
=> actions: less shared components (fixes #7399)

package.json, src/app/users/users-update/users-update.component.html, src/app/users/users-update/users-update.component.ts
Fixes #7376 
Add a `Remove` button to allow users to delete profile images
=> users: add remove of profile images (fixes #7376)

package.json, src/app/courses/courses.component.html, src/app/courses/courses.component.ts, src/app/teams/teams.component.html, src/app/teams/teams.component.ts
Fixes #7415 
Prevent the toolbar from looking squeezed in mobile screens by implementing a toggle to display the search options in a second toolbar row
=> enterprises: more responsive (fixes #7415)

package.json, src/app/home/home.component.html, src/app/shared/planet-language.component.html, src/app/shared/planet-language.component.ts
Fixes #7413 
Improve the mobile navigation and handle the responsiveness issue where the webpage data would exceed the mobile screen size.
=> home: more reactive navigation (fixes #7413)

package.json, src/app/courses/add-courses/courses-add.component.html, src/app/courses/add-courses/courses-add.component.ts
Fixes #7418 
- Displaying the step-container block when step count > 0
- Remove unused imports in the coursesAdd component
=> courses: more responsive creation (fixes #7418)

package.json, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-router.module.ts
Fixes #7427 
Fix broken link when trying to edit achievements from the user profile page
Fix `undefined` birthplace variable showing in template
=> mylife: better achievements birthplace (fixes #7427)

package.json, src/app/teams/teams-view.component.html
Fixes #7429
Courses can be added in enterprises
=> enterprises: courses activated (fixes #7429)

package.json, src/app/users/users-achievements/users-achievements-update.component.html, src/app/users/users-achievements/users-achievements-update.component.ts, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.component.ts
Fixes #7434 
- Remove ability to add resources to the achievements
- Remove display of resources in the achievements page and achievements forms
=> myLife: achievements without resources (fixes #7434)

package.json, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.component.ts
Fixes #7436 
Make the achivements page be downloadble to a pdf document.
=> myLife: print achievements (fixes #7436)

chatapi/src/index.ts, package.json, src/app/chat/chat-window/chat-window.component.ts, src/app/shared/chat.service.ts
Fixes #7453 
Only try to connect to the websocket when streaming is enabled
=> chat: smoother websocket init (fixes #7453)

package.json, src/app/feedback/feedback.component.html, src/app/feedback/feedback.component.ts
Fixes #7456
Responsive feedback toolbar across mobile & tab
=> feedback: responsive toolbar (fixes #7456)

package.json, src/app/feedback/feedback.component.html, src/app/feedback/feedback.component.ts, src/app/users/users.component.html, src/app/users/users.component.ts
=> manager: responsive member navigation (fixes #7456)

package.json, src/app/tasks/tasks.component.ts, src/app/tasks/tasks.service.ts, src/app/teams/teams-view.component.ts, src/app/teams/teams.service.ts, src/app/users/users.service.ts, src/app/validators/custom-validators.ts, src/app/validators/validator.service.ts
Fixes #7460
Clean up on some unused imports
=> all: less imports is more (fixes #7460)

package.json, src/app/shared/forms/form-error-messages.component.ts, src/app/users/users-achievements/users-achievements-update.component.ts, src/app/users/users-achievements/users-achievements.component.html, src/app/validators/custom-validators.ts
Fixes #7474
Add link validation in the myAchievements page and throw an appropriate error message for invalid links.
=> mylife: achievements link validation (fixes #7474)

chatapi/readme.md, chatapi/src/utils/chat-helpers.utils.ts, package.json, src/app/shared/device-info.service.ts
Fixes #7478 
Change from pplx-7b-online(deprecated) to llama-3-sonar-small-32k-online
https://docs.perplexity.ai/docs/model-cards
=> chat: perplexity llama-3-sonor-small-32k-online (fixes #7478)

package.json, src/app/news/news-list-item.component.html, src/app/news/news-list-item.component.ts
Fixes #7490 
In the news truncate the shared messages post similar to the news posts.
=> news: shared chats intros (fixes #7490)

package.json, src/app/users/users-achievements/users-achievements-update.component.ts, src/app/validators/custom-validators.ts
Fixes #7494 
Fixes the link validation for the myLinks
=> mylife: smoother achievements links (fixes #7494)

package.json, src/app/users/users-achievements/users-achievements.component.ts
Fixes #7480 
Updates to the printed achievements
- Better date formatting
- Add Certifications
- Add Links
- Add References
=> mylife: smoother achievements pdf (fixes #7480)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.scss
Fixes #7508 
- Make spacing more consistent
- Improved title character limiting & add ellipsis
- Reduce sidebar icons sizes
- Reduce sidebar width
=> chat: improve sidebar spacing (fixes #7508)

chatapi/src/utils/chat-helpers.utils.ts, docker/chat.env.example, package.json
Fixes #7501
Make the model definition more flexible with configuration option from the env file
=> chat: define model at provider (fixes #7501)

package.json, src/app/shared/chat-output.directive.ts, src/styles.scss
Fixes #7511
Chat UI improvements
- Improve display of various markdown elements: headers, bold, italics, links
- Improve general links display
- Improve code blocks and add copy to clipboard functionality for the code blocks
=> chat: smoother view (fixes #7511)

package.json, src/manifest.json
Fixes #7518 
- Shorten the _short_name_ for the pwa app
=> all: better pwa short name (fixes #7518)

package.json, src/app/dashboard/dashboard.component.html, src/app/dashboard/dashboard.component.ts
Fixes #7536
Update the visit number format
=> dashboard: smoother visit number (fixes #7536)

chatapi/package.json, docker/chatapi/amd64-Dockerfile
Fixes #7543
Fix dependecy issue that makes chat container to crash
=> chatapi: dependency fixes (fixes #7543)

package.json, src/styles.scss
Fixes #7456 
Custom planet scrollbar
=> all: custom scrollbar (fixes #7546)

package.json, src/app/manager-dashboard/reports/reports.component.html
Fixes #7555
Link to report detail in the reports page
=> manager: smoother reports (fixes #7555)

docker/chatapi/amd64-Dockerfile, docker/chatapi/arm-Dockerfile, docker/chatapi/arm64-Dockerfile, package.json
Fixes #7561 
Ensure the `pdftotext` command is available through `poppler-utils` package
=> courses: additional extraction dependency (fixes #7561)

chatapi/src/config/ai-providers.config.ts, chatapi/src/index.ts, chatapi/src/utils/chat-assistant.utils.ts, chatapi/src/utils/chat-helpers.utils.ts, package.json
Fixes #7576
Improves provider check i.e work based on API keys and not the models
=> chat: better api check (fixes #7576)

package.json, src/app/chat/chat.component.ts, src/app/courses/step-view-courses/courses-step-view.component.html, src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/courses/view-courses/courses-view.component.html, src/app/shared/chat.service.ts
Fixes #7578
- Ensure that the courses chat can only be toggled when the courses chat provider is available
- Code improvements for the fetchAIServices
=> courses: enabling context chat (fixes #7578)

chatapi/src/utils/chat-helpers.utils.ts, package.json
Fixes #7580
Ensure only pdf files are processed.
=> chat: smoother non-pdf files (fixes #7580)

docker/planet/nginx/credentials.sh, package.json
Fixes #7583
Add chatapi environment to the "credentials.yml"
=> chat: smoother database credentials (fixes #7583)

package.json, src/app/chat/chat-window/chat-window.component.html, src/app/chat/chat-window/chat-window.component.ts, src/app/chat/chat.component.ts
Fixes #7584
Disable the chat if providers are not set
=> chat: enable on active provider (fixes #7584)

package.json, src/app/chat/chat.component.html, src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/shared/chat.service.ts
Fixes #7591
Chat auto-selection was broken in the latest release. Implement a fix for that
=> chat: smoother default provider (fixes #7591)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.ts, src/app/chat/chat.model.ts, src/app/shared/chat.service.ts
Fixes #7588
Don't show courses chat history in the chat history
=> chat: smoother personal history (fixes #7588)

package.json, src/app/dashboard/dashboard-tile.scss
Fixes #7586
Custom scrollbar for myDashboard page
=> home: smoother horizontal scrollbar (fixes #7586)

chatapi/src/config/ai-providers.config.ts, package.json, src/app/courses/progress-courses/courses-progress-leader.component.ts
Fixes #7598 
Log configuration errors instead of exiting the container for a smoother initialization process.
=> chat: smoother container (fixes #7598)

package.json, src/app/community/community.component.html
Created placeholder text for community services description and links
fixes #7610
=> community: smoother services (fixes #7610)

package.json, src/app/teams/teams-reports.component.html
=> community: smoother reports (fixes #7611)

package.json, src/app/community/community.component.html
added default placeholder text for Our Voices section of Community
Fixes #7615
=> community: smoother voices (fixes #7615)

package.json, src/app/manager-dashboard/manager-aiservices.component.html, src/app/manager-dashboard/manager-aiservices.component.scss
Formatting improvements on mobile: 
Tablet:
and web:
Fixes #7622
=> manager: smoother ai services (fixes #7622)

package.json, src/app/teams/teams-reports.component.html
Fixes #7643 
P.S. Check if reports does exist, and if it does, then check if the length is 0.
=> community: smoother reports (fixes #7643)

package.json, src/app/notifications/notifications.component.html, src/app/notifications/notifications.component.scss, src/app/notifications/notifications.component.ts
Fixes (#7629)
For Mobile ($screen-sm)
For Tablet ($screen-md)
For Desktop
=> all: smoother notifications toolbar (fixes #7629)

package.json, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.scss
Fixes #7632 
For Mobile ($screen-sm)
For Tablet ($screen-md)
For Desktop
=> mylife: smoother achievements navigation (fixes #7632)

package.json, src/app/submissions/submission.component.scss, src/app/submissions/submissions.component.html, src/app/submissions/submissions.component.ts
=> all: smoother submissions list

package.json, src/app/users/users-profile/users-profile.scss
=> all: smoother profile (fixes #7659)

chatapi/src/index.ts, git-hooks/pre-push, package.json, src/app/manager-dashboard/reports/reports-myplanet.component.ts, src/app/manager-dashboard/reports/reports.component.ts, src/app/notifications/notifications.component.ts, src/app/surveys/surveys.component.ts
Fixes #7672
Output the result if ng linters fail
Also fix current linting issues
=> all: smoother linting (fixes #7672)

package.json, src/app/users/users-achievements/users-achievements.scss
=> mylife: smoother achievements (fixes #7652)

package.json, src/app/meetups/add-meetups/meetups-add.component.html, src/app/meetups/add-meetups/meetups-add.component.ts, src/app/shared/dialogs/dialogs-form.component.ts, src/app/submissions/submissions.component.ts, src/app/validators/custom-validators.ts
Red text prevents adding an event with a start date in the past. 
Fixes #7648
=> community: smoother calendar (fixes #7648)

package.json, src/app/resources/view-resources/resources-view.component.html, src/app/shared/dialogs/dialogs-form.component.ts
=> resources: smoother details (fixes #6886)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html
=> manager: smoother report details (fixes #6790)

package.json, src/app/teams/teams-reports-detail.component.html, src/app/teams/teams-reports-detail.component.ts
Made it so you can now see the ending balance
=> teams: smoother reports (fixes #7683)

package.json, src/app/courses/view-courses/courses-view-detail.component.ts, src/app/users/users-profile/users-profile-dialog.component.ts
=> all: smoother profile buttons (fixes #6893)

package.json, src/app/courses/add-courses/courses-add.component.html, src/app/resources/resources-add.component.html
=> courses: smoother form title (fixes #6817)

package.json, src/app/teams/teams-view.component.html
=> teams: smoother tasks list (fixes #5914)

package.json, src/app/teams/teams-member.component.html
=> community: smoother leaders title (fixes #6858)

package.json, src/app/users/users-profile/users-profile.component.html
=> all: smoother profile join date (fixes #5076)

package.json, src/app/manager-dashboard/reports/reports-detail.component.ts
Fixes #7679 
Oct - Nov Filter Range
Just November
=> manager: smoother report steps filter (fixes #7679)

src/app/community/community.component.ts, src/app/shared/database/pouch-auth.service.ts
I fixed the issue where the popup happens every time the community page is refreshed. Now only happens on a new login. 
Still need to add a persistent notification.
=> community challenge: popup only appears on fresh login

src/app/shared/dialogs/dialogs-announcement.component.html, src/app/shared/dialogs/dialogs-announcement.component.ts
Fixes Group Challenge:
2 of my user just finished the challenge, so now it will show $2 out of $500. Also, i change some of the function so that you can change the goal more easily, since its hardcoded right now. (theres 2 function to get and set the goal of the challenges)
=> challenge: dynamic current and target goal

src/app/shared/dialogs/dialogs-announcement.component.html, src/app/shared/dialogs/dialogs-announcement.component.ts
Reverts open-learning-exchange/planet#7718
=> Revert "challenge: dynamic current and target goal"

src/app/shared/dialogs/dialogs-announcement.component.html, src/app/shared/dialogs/dialogs-announcement.component.ts
Reverts open-learning-exchange/planet#7724
=> Revert "Revert "challenge: dynamic current and target goal""

package.json, src/app/health/health-event.component.ts
=> mylife: smoother myhealth limits (fixes #6696)

package.json, src/app/teams/teams-view-finances.component.html, src/app/teams/teams-view-finances.scss
=> enterprises: smoother finances (fixes #6568)

src/app/shared/dialogs/dialogs-announcement.component.html, src/app/shared/dialogs/dialogs-announcement.component.scss
Added Progress Indicators above thermometer (could encourage participation)
Phrases are Below - Let me know if you want to change any of the phrases
For Non-Spanish Speakers:
Goal Percentage = 0 -> "Let's Start!"
Goal Percentage < 25 && >= 0 -> "Good Start!"
Goal Percentage < 75 && >= 25 -> "Keep Going!"
Goal Percentage < 100 && >= 75 -> "So Close!"
Goal Percentage = 100 -> "Challenge Completed!"
=> community challenge: added progress indicators

package.json, src/app/shared/table-helpers.ts, src/app/teams/teams-view.component.html, src/app/teams/teams-view.component.ts
=> enterprises: smoother entries counting (fixes #6950)

package.json, src/app/community/community-link-dialog.component.ts, src/app/community/community.component.ts
fixes #6001 
https://github.com/user-attachments/assets/d3772e90-536b-4c49-98b3-9486a0573b7a
I fixed the issue for the messages when updating the community description. However, still working on updating the success messages for adding links.
=> community: smoother services description (fixes #6001)

package.json, src/app/teams/teams-member.component.html, src/app/teams/teams-member.component.ts
=> teams: smoother tasks (fixes #6673)

package.json, src/app/courses/progress-courses/courses-progress-leader.component.html
=> courses: smoother progress export (fixes #7729)

package.json, src/app/health/health.component.html, src/app/health/health.scss
=> mylife: smoother myhealth data (fixes #6879)

package.json, src/app/landing/landing-home/landing-home.scss, src/styles/calendar.scss
fixes #6796 
@Mutugiii I believe that I fixed the calendar toolbar, are you able to check if it works for super small screens as I'm not able to check that on my laptop
=> community: smoother calendar (fixes #6796)

package.json, src/app/community/community.component.ts
=> community: smoother description (fixes #6460)

README.md, package.json
fixes #7593 
This basically covers everything from step 9 of the internship tutorial and removes the Vagrant usage. 
I also updated the Troubleshooting section with the Mime issue I dealt with in getting my development environment set up. I think there might have been other issues people had, so maybe that section can be further expanded.
=> all: smoother `README.md` (fixes #7593)

package.json, src/app/health/health-event.component.html, src/app/health/health-update.component.html
=> mylife: smoother myhealth form buttons (fixes #6344)

package.json, src/app/feedback/feedback.component.html
fixes  #3823 
[Uploading screen-recorder-fri-nov-15-2024-15-40-41.webm…]()
=> all: smoother feedback search (fixes #3823)

package.json, src/app/courses/step-view-courses/courses-step-view.component.html, src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/exams/exams-view.component.html, src/app/exams/exams-view.component.ts
Fixes #7779
for exams and survey, please check when youre `taking the exams or survey` or `preview`
~~only works for preview for some reason, when taking test or survey, it doesnt work~~
=> courses: smoother steps loading (fixes #7779)

package.json, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.scss
=> mylife: smoother achievements (fixes #7782)

package.json, src/app/shared/forms/planet-markdown-textbox.scss
=> teams: smoother voices creation (fixes #4800)

package.json, src/app/shared/dialogs/dialogs-announcement.component.html, src/app/shared/dialogs/dialogs-announcement.component.ts, src/app/shared/user-challenge-status.service.ts
Fixes #7822 
- Add custom submission value: In this case $5 per submission.
- Ensure $500 limit is set
=> all: smoother challenge validation (fixes #7822)

src/app/chat/chat-sidebar/chat-sidebar.component.ts, src/app/chat/chat.component.ts, src/app/shared/chat.service.ts
handle #7809
refactor code of #7814, i turned the variable into an observable, so that the `chat.component` can listen to it.
=> chat: dynamic ai model label

package.json, src/app/feedback/feedback-view.component.html
Fixes #7825 
The little icons that linked to the relevant course, resource, etc were small and hard to see, so I swapped them for a clearly labeled button.
=> all: smoother feedback buttons (fixes #7825)

package.json, src/app/courses/enroll-courses/courses-enroll.component.html, src/app/courses/enroll-courses/courses-enroll.component.ts
=> courses: add participants export (fixes #7815)

package.json, src/app/courses/step-view-courses/courses-step-view.component.ts
Fixes #7780 
https://www.loom.com/share/02474a6caa9b455f8860b32e35475e07?sid=17d5eb54-9a5c-4b79-a473-4b37615ef20e
To replicate the slow wifi, **if you're on google chrome** -> open your developer tools -> go to network tab -> change your network throttling into fast 4g or slow 4g.
=> courses: smoother steps loading (fixes #7780)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.ts
Fixes #7813 
When creating a new chat, it would be the selected chat.
=> all: smoother challenge chat select (fixes #7813)

package.json, src/app/health/health.constants.ts, src/app/shared/label.component.ts
=> mylife: smoother myhealth form (fixes #7833)

package.json, src/app/teams/teams.component.ts
=> teams: smoother joining (fixes #4530)

package.json, src/app/teams/teams.component.ts
=> teams: smoother deletion snackbar (fixes #7852)

package.json, src/app/teams/teams.component.html
=> enterprises: smoother list checkmark (fixes #5231)

package.json, src/app/shared/dialogs/dialogs-prompt.component.html, src/app/teams/teams-view.component.html
=> teams: smoother document deletion (fixes #4956)

package.json, src/app/shared/dialogs/dialogs-announcement.component.html, src/app/shared/dialogs/dialogs-announcement.component.ts, src/app/shared/user-challenge-status.service.ts
Fixes #7838 
December challenge
- New course
- Updated reward mechanism
=> all: december challenge (fixes #7838)

package.json, src/app/submissions/submissions.component.ts
Fixes #7802
Only problem (possible edge case), if the data is empty, then proceed to add data, then it won't sort anymore. Need to check on this (you would have to reload the page for it to start sorting again)
=> surveys: smoother sorting (fixes #7802)

package.json, src/app/chat/chat-window/chat-window.scss
Fixes #7874
smoother chatbox size
=> chat: smoother textbox size (fixes #7874)

package.json, src/app/courses/view-courses/courses-view.component.html, src/app/courses/view-courses/courses-view.scss, src/app/teams/teams.component.ts
=> courses: smoother steps preview title (fixes #7868)

package.json, src/app/exams/exams-view.component.ts
Fixes #7877 
Fixes infinite loading when going to survey from mySurveys.
=> surveys: smoother loading (fixes #7877)

package.json, src/app/teams/teams.component.ts
=> teams: smoother delete message (fixes #7885)

package.json, src/app/courses/search-courses/courses-search.component.ts, src/app/resources/search-resources/resources-search.component.ts
Fixes #7880
Filter to remove undefined constants that interrupt with the filter icon[Prone in nations with unstable data].
Tested on planet earth[courses & resources]
=> courses: smoother filter list (fixes #7880)

package.json, src/app/resources/resources.component.html
=> resources: smoother buttons (fixes #7889)

package.json, src/app/dashboard/dashboard-tile.component.html
fixes #7886 we will have to open a separate issue for titles with no spaces because they still overflow.
=> dashboard: smoother drag and drop (fixes #7886)

package.json, src/app/courses/view-courses/courses-view.component.html, src/app/courses/view-courses/courses-view.scss
=> courses: smoother toolbar (fixes #7878)

package.json, src/app/courses/progress-courses/courses-progress-leader.component.html
=> courses: smoother progress title (fixes #7906)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.scss
=> manager: smoother reports subheading (fixes #4418)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports.service.ts, src/app/manager-dashboard/reports/reports.utils.ts
Fixes #7896 
Added a chart for chat usage (when chat is created based on months)
=> manager: initial chat reports (fixes #7896)

package.json, src/app/home/home-router.module.ts, src/app/home/home.module.ts, src/app/manager-dashboard/manager-dashboard-router.module.ts, src/app/manager-dashboard/manager-dashboard.component.html, src/app/manager-dashboard/reports/logs-myplanet.component.html, src/app/manager-dashboard/reports/logs-myplanet.component.ts, src/app/manager-dashboard/reports/reports-myplanet.component.html, src/app/manager-dashboard/reports/reports-myplanet.component.ts
Fixes #7816 #7634
- Activate myPlanet logs and access it from manager dashboard
- Implement export functionality for myPlanet reports and logs
=> manager: smoother myplanet logs (fixes #7634)(fixes #7816)

package.json, src/app/shared/forms/planet-tag-input-dialog.component.html
=> resources: smoother collections display (fixes #7772)

package.json, src/app/resources/view-resources/resources-view.component.html, src/app/resources/view-resources/resources-view.scss
=> resources: smoother navigation (fixes #7927)

package.json, src/app/chat/chat-window/chat-window.component.ts
Fixes #7915 
When opening up the chat for the first time, the chat would be clear. Also when switching between user, it would be clear.
=> chat: smoother ux (fixes #7915)

package.json, src/app/exams/exams-view.component.ts
Fixes #7939
everytime you switch your answer, it will recheck for validity
=> courses: smoother multiple choice (fixes #7939)

package.json, src/app/community/community.component.html, src/app/community/community.scss, src/app/shared/calendar.component.ts, src/app/teams/teams-view.component.html
=> community: smoother calendar legend (fixes #6572)

package.json, src/app/shared/forms/planet-tag-selected-input.component.ts
=> resources: smoother collections (fixes #7928)

package.json, src/app/shared/forms/planet-tag-input-dialog.component.html, src/app/shared/forms/planet-tag-input-dialog.component.ts
=> resources: smoother subcollections (fixes #7948)

package.json, src/app/teams/teams-view.component.html, src/app/teams/teams-view.scss
=> teams: smoother title overflow (fixes #7964)

package.json, src/app/meetups/meetups.service.ts
fixes #5401
Now when you delete a recurring event it gives info about how many recurrences you're deleting in the confirmation dialog.
=> community: smoother calendar event deletion (fixes #5401)

package.json, src/app/shared/forms/planet-tag-input-dialog.component.ts
=> resources: smoother collections scrolling (fixes #6280)

package.json, src/app/courses/courses.service.ts, src/app/resources/resources.service.ts
fixes #7954, #7955
Now, it says added/removed from myCourses/myLibrary, instead of sometimes saying dashboard. 
For resources, the resource name is supplied when adding or removing a single resource from myLibrary.
=> resources: smoother snackbar (fixes #7954)(fixes #7955)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.scss
=> chat: smoother placeholder text (#7973)

package.json, src/app/teams/teams-view.scss
=> teams: smoother resources titles (fixes #7978)

package.json, src/app/home/home.component.html
=> all: smoother navigation tooltips

package.json, src/app/courses/courses.scss, src/app/resources/resources.scss
=> resources: smoother collections labels (fixes #7983)

package.json, src/app/tasks/tasks.component.html, src/app/tasks/tasks.component.ts, src/app/tasks/tasks.scss
fixes #5377 
will highlight deadline red if overdue and will highlight deadline yellow if a task is within 24 hours of its assigned due deadline
=> teams: smoother tasks deadlines (fixes #5377)

package.json, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.scss
=> mylife: smoother achievements certifications (fixes #7975)

package.json, src/app/dashboard/dashboard-tile.scss
=> dashboard: smoother icon colors (fixes #7993)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-sidebar/chat-sidebar.scss, src/app/tasks/tasks.component.ts
=> chat: smoother full search (fixes #8004)

package.json, src/app/health/health.component.html
=> mylife: smoother myhealth toolbar (fixes #8008)

package.json, src/app/health/health-event-dialog.component.html
=> mylife: smoother myhealth countdown (fixes #8007)

package.json, src/app/community/community.scss
=> community: smoother leaders tiles (fixes #8005)

package.json, src/app/shared/dialogs/dialogs-announcement.component.scss
=> all: smoother december challenge (fixes #8024)

package.json, src/app/users/users-table.component.html, src/app/users/users-table.scss
fixes #8003 
Matches surveys page buttons.
=> manager: smoother members buttons (fixes #8003)

package.json, src/app/resources/resources.scss
=> resources: smoother list titles (fixes #8030)

package.json, src/app/shared/dialogs/dialogs-announcement.component.ts
Fixes #8044
Dec Challenge date extension
=> all: extend december challenge (fixes #8044)

package.json, src/app/health/health.scss
fixes #8035
Aligned self-exam text regardless of the presence of the information icon
=> mylife: smoother myhealth exams (fixes #8035)

package.json, src/app/health/health-event.component.ts
fixes #8064 
The cancel button appears now.
=> mylife: smoother myhealth dialog (fixes #8064)

package.json, src/app/courses/step-view-courses/courses-step-view.component.html, src/app/courses/step-view-courses/courses-step-view.scss
=> courses: smoother finish button (fixes #8059)

package.json, src/app/news/news-list.component.ts, src/app/shared/forms/planet-tag-input-dialog.component.ts
=> teams: smoother voices titles (fixes #8086)(fixes #8087)

package.json, src/app/teams/teams-reports.component.ts
fixes #8084, #8085
Delete confirmation dialog works now 
Added snackbars for add, edit, delete
=> teams: smoother reports dialogs (fixes #8084)(fixes #8085)

package.json, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.component.ts, src/app/users/users-achievements/users-achievements.module.ts, src/app/users/users-profile/users-profile.component.html, src/app/users/users-router.module.ts
Fixes #8082 
Make the achievements page shareable with a public facing route that requires no auth. Also add a copy button for the link
=> mylife: smoother achievements sharing (fixes #8082)

package.json, src/app/users/users-achievements/users-achievements-update.component.ts
fixes #8071
Made links optional
=> mylife: smoother achievements links (fixes #8071)

package.json, src/app/home/home-router.module.ts
Fixes #8105
Prevent non-admin users from accessing admin routes
=> manager: smoother rights check (fixes #8105)

package.json, src/app/exams/exams-view.component.ts, src/app/users/users-update/users-update.component.ts
Fixes #8108
Fix the surveys routing i.e issue with routing to the 'manager/surveys'
=> teams: smoother surveys routing (fixes #8108)

chatapi/src/utils/chat-helpers.utils.ts, package.json
Fixes #8116 
Only handle the resource attachement if valid(id or attachment is not null)
=> courses: smoother chat context (fixes #8116)

package.json, src/app/users/users-profile/users-profile.scss
fixes #8118
Now long names cannot overflow and push other fields around.
=> dashboard: smoother profile (fixes #8118)

package.json, src/app/users/users-update/users-update.component.ts
=> dashboard: smoother profile edit (fixes #8119)

README.md, package.json, src/app/home/home.component.html
=> all: smoother navigation chat icon (fixes #8134)

package.json, src/app/teams/teams-view.component.html, src/app/teams/teams-view.component.ts
=> teams: smoother member cards (fixes #8113)

chatapi/README.md, chatapi/src/config/ai-providers.config.ts, chatapi/src/index.ts, chatapi/src/models/ai-providers.model.ts, chatapi/src/utils/chat-helpers.utils.ts, package.json, src/app/chat/chat.model.ts, src/app/configuration/configuration.component.ts, src/app/shared/chat.service.ts
Fixes #8140 
Add deepseek support
=> chat: add deepseek support (fixes #8140)

package.json, src/app/teams/teams-view.component.ts
fixes #8148
Now truncation of long names will not cut off the action (accept, reject, remove)
=> teams: smoother snackbar messages (fixes #8148)

package.json, src/app/news/news-list-item.scss
=> teams: smoother voices names (fixes #8112)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html, src/app/chat/chat-window/chat-window.component.ts, src/app/chat/chat-window/chat-window.scss, src/app/news/news-list-item.scss, src/styles.scss
Fixes #8154
- Fix the conversation title editing 
- Fix the conversation query link color
=> chat: smoother title editing (fixes #8154)

package.json, src/app/courses/step-view-courses/courses-step-view.scss
Fixes #8151
Not sure how I feel about this, probabl would work on it more for a bit.
=> courses: smoother steps chat (fixes #8151)

README.md, package.json
Add a description of fix to handle the libseccomp2 error
=> all: smoother `README.md` (fixes #8163)

package.json, src/app/manager-dashboard/reports/logs-myplanet.component.html, src/app/manager-dashboard/reports/reports-myplanet.component.html
=> manager: smoother myplanet reports and logs (fixes #8173)

package.json, src/app/manager-dashboard/requests/requests-table.component.html
fixes #8178
To test without setting up a nation, just go to http://localhost:3000/manager/requests
=> manager: smoother pending communities list (fixes #8178)

package.json, src/app/chat/chat-window/chat-window.component.ts, src/app/news/news-list.component.ts, src/app/shared/chat-output.directive.ts
Fixes #8202
Fix the streaming chunks not displaying.
=> chat: smoother streaming chunks display (fixes #8202)

package.json, src/app/submissions/submission.component.scss, src/app/submissions/submissions.component.html
=> mylife: smoother submissions titles (fixes #8205)

package.json, src/app/courses/add-courses/courses-add.component.ts
=> courses: smoother step creations (fixes #8223)

package.json, src/app/manager-dashboard/manager-dashboard.component.html, src/app/manager-dashboard/manager-dashboard.component.ts
fixes #8243
mobile:
tablet/desktop:
=> manager: smoother dashboard headers (fixes #8243)

package.json, src/app/teams/teams-view-finances.component.html
=> teams: smoother finances navigation (fixes #8262)

package.json, src/app/teams/teams-view-finances.component.html
=> enterprises: smoother finances date filtering (fixes #8260)

package.json, src/app/submissions/submissions.service.ts, src/app/users/users-update/users-update.component.html, src/app/users/users-update/users-update.component.ts
Fixes #8238 
Focus on getting the gender and age post survey, hide other fields but can still be filled
=> teams: smoother survey submission (fixes #8238)

package.json, src/app/home/home.component.html
fixes #8258 
Now nations have the same home icon as communities.
=> all: smoother navigation home icon (fixes #8258)

package.json, src/app/users/users-profile/users-profile.component.html, src/app/users/users-profile/users-profile.component.ts
=> dashboard: smoother profile roles (fixes #3375)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports.utils.ts
=> manager: smoother reports date filter (fixes #8261)(fixes #8265)

package.json, src/app/manager-dashboard/reports/logs-myplanet.component.html, src/app/manager-dashboard/reports/logs-myplanet.component.ts
fixes #8249
Type and version dropdown lists should autopopulate based on what's in the logs.
=> manager: smoother myplanet logs filters (fixes #8249)

package.json, src/app/health/health-update.component.ts
=> mylife: smoother myhealth profiles (fixes #8288)

package.json, src/app/health/health-event.component.ts, src/app/submissions/submissions.service.ts, src/app/teams/teams.service.ts
fixes #8233
Added teams/enterprise info to pdf/csv exports
Shortened date/time in pdf header
=> manager: smoother surveys export (fixes #8233)

package.json, src/app/users/users-achievements/users-achievements-update.component.ts
=> mylife: smoother myachievements form (fixes #8291)

package.json, src/app/courses/add-courses/courses-add.component.ts, src/app/feedback/feedback.directive.ts, src/app/news/news-list-item.component.ts, src/app/shared/auth-guard.service.ts, src/app/shared/calendar.component.ts
Fixes #8284
Authenticate the dialog actions for the open community page
- Reply
- Add Event
- Feedback
=> community: smoother authentication dialogs (fixes #8284)

package.json, src/app/chat/chat-sidebar/chat-sidebar.component.html
fixes #8326
I think removing the mat-icon from the i18n div should fix the issue, but I'm not sure how to test in dev environment
=> chat: smoother button formatting (fixes #8326)

package.json, src/app/manager-dashboard/reports/reports-detail-activities.component.html, src/app/manager-dashboard/reports/reports-detail-activities.component.ts, src/app/manager-dashboard/reports/reports-detail.component.html
fixes #8348
Will add export functionality as a separate PR.
=> manager: smoother report chat (fixes #8348)

package.json, src/app/manager-dashboard/reports/logs-myplanet.component.ts, src/app/manager-dashboard/reports/myplanet-table.component.html
=> manager: smoother myplanet logs sorting (fixes #8335)

package.json, src/app/manager-dashboard/reports/reports-detail-activities.component.ts, src/app/manager-dashboard/reports/reports-detail.component.ts
fixes #8330, #8363, #8364
Courses report data is populating properly now.
Sorting course reports by steps and tests working properly. 
Sorting chat reports by timestamp working properly.
=> manager: smoother reports courses summary (fixes #8330)(fixes #8363)(fixes #8364)

package.json, src/app/manager-dashboard/reports/reports-detail.component.ts
Fixes #8332
Add the report date filtering parameters to the browser url
=> manager: smoother reports dates url (fixes #8332)

package.json, src/app/shared/table-helpers.ts
=> resources: smoother sorting (fixes #8352)

package.json, src/app/manager-dashboard/reports/logs-myplanet.component.ts, src/app/resources/view-resources/resources-viewer.component.ts
Fixes #8356
Support additional file format viewing in planet resource viewer.
=> resources: smoother text viewer (fixes #8356)

package.json, src/app/manager-dashboard/reports/reports-detail.component.ts
Fixes #8369
Fix reports cycling through dates issue.
=> manager: smoother reports reloading (fixes #8369)

package.json, src/app/resources/resources-add.component.html, src/app/resources/resources-add.component.ts, src/app/shared/forms/file-input.component.ts
=> resources: smoother creating attachments (fixes #8359)(fixes #8360)(fixes #8361)

package.json, src/app/configuration/configuration.component.html
added little lower margin in planet configurations toggle
=> manager: smoother configuration form (fixes #8385)

package.json, src/app/shared/state.service.ts, src/app/shared/user-guard.service.ts
Fixes #8397 
Steps to test (pretty much the same as that issue description):
- Go to the community page when not logged in
- Login by clicking on courses or another page that requires authentication (do not refresh the page!)
- Attempt to load a course or the list of users
- Now the page should load!
=> community: smoother login (fixes #8397)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
fixes #8329
The link builder doesn't work on a dev environment, but I think it should be functional on Planet Guatemala for example. Please let me know if that is not the case.
=> manager: smoother reports courses overview export (fixes #8329)

package.json, src/app/news/news-list.component.ts
fixes #8020
Fixed an issue where shared AI chats were not populating the delete confirmation dialog
=> teams: smoother voices deletion (fixes #8020)

package.json, src/app/meetups/add-meetups/meetups-add.component.ts, src/app/validators/custom-validators.ts
fixes #8405
Now we can edit (and add) past meetups.
=> community: smoother calendar meetups (fixes #8405)

package.json, src/app/manager-dashboard/manager-aiservices.component.html, src/app/manager-dashboard/manager-aiservices.component.scss, src/app/manager-dashboard/manager-aiservices.component.ts, src/app/manager-dashboard/manager-dashboard.component.html, src/app/manager-dashboard/manager-dashboard.component.ts
Redirected the chat streaming toggle to ai configurations page.
=> manager: smoother ai configuration streaming (fixes #8396)

package.json, src/app/feedback/feedback.directive.ts
fixes: #8424 
https://github.com/user-attachments/assets/6fa1341d-9eaa-4d56-8a32-7a6a2faba33d
Now the dialog is appearing whenever clicked on feedback.
=> all: smoother feedback dialog (fixes #8424)

package.json, src/app/courses/courses.component.html, src/app/courses/courses.component.ts, src/app/courses/courses.service.ts
fixes: #8436  (partially) - Only the Courses
https://github.com/user-attachments/assets/265ab7f4-21e2-4088-9d5a-b4a73baf63c9
It correctly displays 'Courses Loading ...' instead of no courses found.
=> courses: smoother list loading (fixes #8436)

package.json, src/app/resources/resources.component.html, src/app/resources/resources.component.ts, src/app/resources/resources.service.ts
fixes: #8436 
https://github.com/user-attachments/assets/493b52a2-ebe6-4e9e-82b9-7cb67cfacca3
Now it correctly displays Resources Loading instead of No resources found in the background.
=> resources: smoother detail loading (fixes #8436)

package.json, src/app/shared/beta-then-auth-guard-service.ts
Trying a fix for the login dialog not quite following the expected behavior based on beta settings. Because that issue has only been seen in production need to test with the docker image built for this PR.
=>  login: smoother dialog behaviour (fixes #8432) 

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
fixes #8468
Similar to https://github.com/open-learning-exchange/planet/pull/8465, except I have last 12 months as the default range.
=> manager: smoother reports date filtering (fixes #8468)

package.json, src/app/teams/teams.service.ts
=> teams: smoother joining notifications (fixes #8483)

package.json, src/app/home/home-router.module.ts, src/app/shared/auth-guard.service.ts
Removes the beta requirement for the public community. I left in the `BetaThenAuthComponent` which was only used for this, but I think we should wait to remove that until we are sure we do not need to revert this.
=> community: smoother new landing page (fixes #8482)

chatapi/package.json, chatapi/src/services/chat.service.ts, chatapi/src/utils/chat-assistant.utils.ts, chatapi/src/utils/chat-error.utils.ts, chatapi/src/utils/chat-helpers.utils.ts, chatapi/src/utils/chat.utils.ts, package.json
Fixes #8520
Additional context now taken into account when running streaming(not just initial instructions). 
Additionally did some minor cleanup
=> chat: smoother api streaming context (fixes #8520)

package.json, src/app/news/news-list.component.ts, src/app/news/news.service.ts
fixes #8484
Creating a blank voice via editing is no longer possible.
=> teams: smoother voices editing (fixes #8484)

package.json, src/app/manager-dashboard/reports/logs-myplanet.component.ts
fixes #8501
Default is now 24h
=> manager: smoother myplanet logs default date (fixes #8501)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts
=> manager: smoother reports filter clearing (fixes #8527)

package.json, src/app/manager-dashboard/reports/reports-detail.component.ts
=> manager: smoother reports date filtering (fixes #8526)

package.json, src/app/users/users-achievements/users-achievements.component.html, src/app/users/users-achievements/users-achievements.component.ts, src/app/users/users-achievements/users-achievements.scss
fixes #8515
The whole achievements page loads at once, instead of prematurely loading without certifications.
=> mylife: smoother achievements loading (fixes #8518)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports.utils.ts
=> manager: smoother report chat export (fixes #8328)

package.json, src/app/resources/resources.component.html, src/app/resources/resources.component.ts, src/app/resources/resources.scss
Fixes #8524 
Removing internal scrollbars by switching to table expansion rows
~~On hold for #8523~~
=> resources: smoother list view (fixes #8524)

package.json, src/app/teams/teams-view.component.html
=> teams: smoother join requests and applicants (fixes #8481)

package.json, src/app/users/users-table.component.html, src/app/users/users-table.scss
fixes #8537
Added truncation and a bit of right margin to better format long member names.
=> manager: smoother members list (fixes #8537)

package.json, src/app/submissions/submissions.service.ts
fixes #8545
Made the upper margin for the different types of headers consistent.
=> manager: smoother survey export (fixes #8545)

package.json, src/app/users/users-table.component.ts
fixes: #8543 
Now the user can also search using the fullName and username as well
=> manager: smoother members searching (fixes #8543)

package.json, src/app/submissions/submissions.service.ts
fixes #8569
AI survey analysis now has deeper insights.
=> manager: smoother surveys ai analysis (fixes #8569)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports-health.component.ts
=> manager: smoother empty reports message (fixes #8546)

package.json, src/app/shared/csv.service.ts, src/app/submissions/submissions.service.ts
Now the name become the survey + title name
fix #8561
=> manager: smoother survey export (fixes #8561)

package.json, src/app/dashboard/dashboard-tile.component.ts, src/app/home/home.component.ts, src/app/news/news-list-item.component.ts
Better error handling to avoid getComputedStyle function console errors
=> dashboard: smoother view (fixes #8641)

package.json, src/app/courses/view-courses/courses-view.scss
=> courses: smoother view (fixes #8619)

package.json, src/app/teams/teams-view.component.html
=> teams: smoother members count (fixes #8620)

package.json, src/app/exams/exams-view.component.html
fixes #8655
submit button was broken for grading, but should be fixed now.
=> courses: smoother submissions grading (fixes #8655)

package.json, src/app/dashboard/dashboard.component.html, src/app/health/health.component.html, src/app/users/users-achievements/users-achievements.component.html
=> dashboard: smoother username truncation (fixes #8649)

package.json, src/app/teams/teams.component.ts
=> dashboard: smoother list teams andor enterprises (fixes #8651)

package.json, src/app/users/users-achievements/users-achievements-update.scss
fixes #8665
Added some margin so the bottom of the form is less cramped.
=> mylife: smoother achievements checkbox (fixes #8665)

package.json, src/app/manager-dashboard/certifications/certifications.component.html, src/app/manager-dashboard/certifications/certifications.component.ts
=> mylife: smoother certifications list (fixes #8679)

package.json, src/app/news/news-list.component.html, src/app/news/news-list.component.ts
Fixes #8681 
Auto load voices on scroll -> Replace the load more button workflow
https://github.com/user-attachments/assets/a7a8094e-1fd0-4cb6-9a2d-9bc2f3b1ee9d
=> teams: smoother voices loading (fixes #8681)

package.json, src/app/users/users-profile/users-profile.scss
=> dashboard: smoother profile view (fixes #8660)

package.json, src/app/teams/teams.component.html, src/app/teams/teams.component.ts
fixes #8635
https://github.com/user-attachments/assets/2b4fae62-dbc2-455e-b978-790554a22b99
=> teams: smoother list sorting priority (fixes #8635)

package.json, src/app/teams/teams-view.scss, src/app/users/users-profile/users-profile.component.ts, src/app/users/users-profile/users-profile.scss
=> dashboard: smoother profile memberships (fixes #8693)

README.md, package.json
Fixes #8709
- Fix `start` and `build` scripts allowing to select lang locale in dev/build process
=> all: smoother language dev (fixes #8709)

package.json, src/app/courses/step-view-courses/courses-step-view.component.ts, src/app/shared/ai-prompts.constants.ts, src/app/submissions/submissions.service.ts
Fixes #8698 
- Improve the formatting of the survey AI analysis to support markdown
- Better handling of AI prompt related strings in a shared constants file
=> manager: smoother survey export formatting (fixes #8698)

.github/workflows/planet.yml, package.json
=> actions: smoother prebuild on master (fixes #8717)

package.json, src/app/news/news-list-item.component.html
=> teams: smoother voices labels (fixes #8690)

package.json, src/app/submissions/submissions.service.ts
Fixes #8713
Display the users % as well as the total no responses
=> teams: smoother survey exports pdf charts (fixes #8713)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports.service.ts, src/app/manager-dashboard/reports/reports.utils.ts
Fixes #8758 
Add `voices created`  chart in the reports detail page
=> manager: smoother reports voices added (fixes #8758)

package.json, src/app/submissions/submissions.service.ts
Fixes #8771
- Import scales to fix the pdf export not working on the teams from time to time.
- Fix count inconsistency
=> teams: smoother survey export pdf (fixes #8771)

README.md, package.json
Fixes #8766
Switch from codeclimate badge to Qlty Cloud
=> all: smoother readme qlty badge (fixes #8766)

package.json, src/app/submissions/submissions.service.ts
Fixes #8779
Add a table report for multiplechoice questions.
=> manager: smoother survey pdf exports chart (fixes #8779)

package.json, src/app/exams/exams-view.component.ts
fixes #8801
Now, when other is selected, some input is required (only spaces will not count) to submit.
Also, when other is deselected, if no other choices are selected, submission is not allowed.
=> teams: smoother survey choice other (fixes #8801)

package.json, src/app/exams/exams-view.component.html, src/app/exams/exams-view.scss
Fixes #8796
UI improvement for the `other` button
=> teams: smoother survey choice other input (fixes #8796)

package.json, src/app/manager-dashboard/manager-fetch.component.html, src/app/manager-dashboard/manager-fetch.component.ts
=> manager: smoother fetch list icons (fixes #8815)

package.json, src/app/chat/chat.component.html, src/app/chat/chat.scss
=> chat: smoother provider toggle (fixes #8836)

package.json, src/app/news/news-list-item.component.ts
Fixes #8883
Better null handling of the news expansion
Tested on Planet Learning
=> teams: smoother voices expansion (fixes #8883)

package.json, src/app/resources/resources-add.component.html, src/app/resources/resources-add.scss
=> resources: smoother creation (fixes #8852)

package.json, src/app/dashboard/dashboard.component.ts
=> dashboard: smoother mychat link (fixes #8910)

package.json, src/app/manager-dashboard/reports/logs-myplanet.component.html, src/app/manager-dashboard/reports/reports-myplanet.component.html
fixes #8922
Fixed an issue where the clear button was white when active, instead of blue like the other pages.
=> manager: smoother myplanet log buttons (fixes #8922)

package.json, src/app/manager-dashboard/reports/logs-myplanet.component.html, src/app/manager-dashboard/reports/logs-myplanet.component.ts, src/i18n/messages.spa.xlf
fixes #8962
Added loading message
Also added Spanish translation
=> manager: smoother myplanet logs (fixes #8962)

package.json, src/app/news/news-list-item.component.html, src/app/news/news-list-item.component.ts, src/app/news/news-list-item.scss, src/styles.scss
=> teams: smoother voices names (fixes #8967)

package.json, src/app/community/community.component.html, src/app/community/community.component.ts
Fixes #8983 
- Voices search state persists on login/logout
- Empty search shows `No Voices available`
=> community: smoother filter consistency (fixes #8983)

package.json, src/app/submissions/submission.component.scss, src/app/submissions/submission.scss, src/app/submissions/submissions.component.html, src/app/submissions/submissions.component.ts
=> manager: smoother submissions list names (fixes #8980)

package.json, src/app/community/community.scss
Fixes #9015
Community toolbar no longer leaks to the user achievements toolbar
=> community: smoother navigation style (fixes #9015)

package.json, src/app/manager-dashboard/reports/reports-detail.component.html, src/app/manager-dashboard/reports/reports-detail.component.ts, src/app/manager-dashboard/reports/reports-detail.scss
Fixes #9044
Refactor the reports detail component toolbar template.
=> manager: smoother report details navigation (fixes #9044)

package.json, src/app/news/news-list-item.component.ts, src/app/news/news-list.component.ts
Fixes #9063
Revert `14d924791416570556d1618145aa50cca17e24e1`
=> teams: less voices response is more (fixes #9063)
